### ISSUE TITLE
Use a `dev` branch for development

### ISSUE THREAD

**Issue by housengw** [lf-lang/lingua-franca#1019]
A common pattern I noticed in the `Actions` tab on Github is several consecutive pushes to a branch within a short period of time.
This might clog up the CI resources (or be tedious to cancel)... an alternative is to use a `dev` branch to develop and only push to the branch with a PR once the changes are ready.

**Comment by Soroosh129** [comment]
Would it be possible to use [this](https://github.com/marketplace/actions/cancel-workflow-action) to cancel the previous workflows when a new commit is pushed?

**Comment by housengw** [comment]
Maybe, but the CI history wouldn't be too clean..

**Comment by lhstrh** [comment]
I think automatic cancellation of unfinished workflows is a good idea; a lot of us have been doing this manually, anyway.

**Comment by cmnrd** [comment]
Yes, its a great feature and I am puzzled why GitHub has no built-in support. GitLab supports automatic cancellation and it works great. I also found the Action that Soroush linked a while ago, but I discarded the idea because it seemed like maintaining this could be tricky. But we surely can give it a try.

**Comment by lhstrh** [comment]
@Soroosh129 has contributed a workflow that cancels jobs once a newer job gets spawned in response to an event on the same branch.

**Comment by lhstrh** [comment]
If we want to more aggressively free up resources, we could also use this: https://github.com/marketplace/actions/cancel-workflow-action-for-failed-jobs

That way, if one job fails, all jobs get killed.
