### ISSUE TITLE
cmake build breaks tracing

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#1067]
Hokeun was chasing a mysterious bug where some tracing functions were not being called even though tracing is turned on. The file trace.h has this:
```
#ifdef LINGUA_FRANCA_TRACE
...
void tracepoint_worker_wait_starts(int worker);
...
#else
...
#define tracepoint_worker_wait_starts(...)
...
#endif
```
The file `scheduler_GEDF_NP.c` has a pound include of the above .h file, which, when separately compiled, results in the second definition, regardless of whether tracing is turned on our not.

Tracing used to work when the generated .c file included within it the other needed .c files because it would have, near the top, the following line:
```
#define LINGUA_FRANCA_TRACE
```
But now, that #define is never seen in any separately compiled file.  So we need to find some other way to do this conditional compilation. Note that it is extremely important that tracing have exactly zero overhead when turned off, which is what the above strategy accomplishes. It defines `tracepoint_worker_wait_starts` as an empty macro that takes an arbitrary number of arguments.

The only way I can see to fix this is to change the code generator so that it creates, in addition to a .c file, a .h file with some common name, and then every other LF core file needs to have #include for that generated .h file.  Any other ideas?  Any volunteers to fix this? Perhaps one you who insisted on this separate compilation strategy? :-)

**Comment by lhstrh** [comment]
It's not so much that Cmake breaks anything but that the code generator inserts the define in the wrong place. I believe @hokeun already has a fix.

**Comment by hokeun** [comment]
@lhstrh I tried that solution after our meeting, but I found that the solution didn't solve this bug. So this bug still exists.

**Comment by Soroosh129** [comment]
There is a mechanism to fix this in the CGenerator.
There is simply a `targetConfig.compileDefinitions.put("LINGUA_FRANCA_TRACE", "")` missing.

This will expose the appropriate compile definition to CMake in the generated CMakeLists.txt.

**Comment by Soroosh129** [comment]
> @lhstrh I tried that solution after our meeting, but I found that the solution didn't solve this bug. So this bug still exists.

Could you please elaborate a bit? Does this solution match my comment above?

**Comment by lhstrh** [comment]
> @lhstrh I tried that solution after our meeting, but I found that the solution didn't solve this bug. So this bug still exists.

If you can push this to a branch and issue a (draft) PR, we can help.

**Comment by hokeun** [comment]
Thank you, Edward, Soroush, and Marten!

> There is a mechanism to fix this in the CGenerator. There is simply a `targetConfig.compileDefinitions.put("LINGUA_FRANCA_TRACE", "")` missing.

I worked with @edwardalee on this solution by @Soroosh129 , and it works!

Just for reference, the solution I tried after the scheduling meeting is here: https://github.com/lf-lang/lingua-franca/commit/1827ed8273145d13bd8342b483cfbda796d9313c

The solution is in this PR: https://github.com/lf-lang/lingua-franca/pull/1068
