### ISSUE TITLE
Eliminate large files from git history

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/lingua-franca#1078]
Unfortunately, we have some large (and useless) files trapped in our git history, which makes checking out our repository very slow. We might want to consider filtering these out of our commit log. Here's a short list of the largest blobs:

```
100755 blob a79e2f9c459abbfb8bc6d04320e44e9c43176992 31281186	example/Python/src/Piano/soundfont.sf2
100755 blob 10bfe63f23fe8ce67991aa3e60bc7f9575aa1843 15010928	benchmark/Cpp/Savina/bin/PingPongThreaded
100755 blob 7eef4a0395bc114057217f4ccbd08dfbc6676bf1 14923416	benchmark/Cpp/Savina/bin/PingPong
100644 blob 0e1db5f84e3eec24c3c95e013e546aa550b9594e 3820160	presentations/Lohstroh_etAl_FDL20.pdf
100644 blob b0a9755db9f1cbc46bedf20d66643ace402cec70 3386793	presentations/Lohstroh_Lee_FDL19.pdf
100644 blob 240d6ea796f44e5dfd2edbec69c1c9e31855d438 2688020	xtext/.gradle/5.4.1/javaCompile/classAnalysis.bin
100644 blob f2dc00b6ab2baa6ff16564b0bbddc93516eb5eec 2066662	presentations/Lee_ActorsRevisited_CyPhy.pdf
100644 blob af94b80a47a3d40d76e1f58b9c772f8a4e7b9b41 1704368	lib/pqueue.h.gch
100644 blob 90516fd7ac76a3ec685e046f91eb762e68e20586 1484649	xtext/org.icyphy.linguafranca/.antlr-generator-3.2.0-patch.jar
100644 blob 90516fd7ac76a3ec685e046f91eb762e68e20586 1484649	org.lflang/.antlr-generator-3.2.0-patch.jar
100644 blob 90516fd7ac76a3ec685e046f91eb762e68e20586 1484649	org.icyphy.linguafranca/.antlr-generator-3.2.0-patch.jar
100644 blob 03b276a9b98f4b9ed5fb6003ebc92acbc745aa4f 1180406	presentations/Lohstroh_etAl_CyPhy19.pdf
100644 blob 03b276a9b98f4b9ed5fb6003ebc92acbc745aa4f 1180406	presentations/Lohstroh_CyPhy19.pdf
100644 blob 223626b5e7a2a8f53296c3814196a6a9269fda96 1105562	ray/RayRace.ai
100644 blob 73338d5d4ed2265813d545a7584fd7a0b0b7a463  891867	presentations/Lohstroh_etAl_EMSOFT19.pdf
100644 blob 73338d5d4ed2265813d545a7584fd7a0b0b7a463  891867	presentations/Lohstroh_EMSOFT19.pdf
100644 blob 709ca66fe51de7462276696348fc6b6f05425273  737433	xtext/.gradle/5.4.1/executionHistory/executionHistory.bin
100644 blob 4ab98887c449167f2c3d452aa517e48558518498  737433	xtext/.gradle/5.4.1/executionHistory/executionHistory.bin
100644 blob 2cf85558ce3d0ee89ef8be39b1fc6c97cb6de8a4  737433	xtext/.gradle/5.4.1/executionHistory/executionHistory.bin
```

Note that the soundfont along with the two binary files already accounts for ~`60MB`.

**Comment by lhstrh** [comment]
I would use `git filter-branch --index-filter 'git rm --cached --ignore-unmatch <file>'` for this. Alternatively, there is this tool: https://rtyley.github.io/bfg-repo-cleaner/
In any case, I think this would require a "hard fork" where outstanding PRs wouldn't be able to merge. Is there any other way?

**Comment by cmnrd** [comment]
No, there is no other way. But probably we shouldn't bother. The messing with the repository is very risky and the "fork" (as you describe it), is not worth it. Not only would we need to pause development, but also everyone who has a clone of LF somewhere will get trouble when trying to pull changes (and even more when pushing changes...).

60MB isn't all that big and cloning is also slow because the history is long. Note that one can use `git clone --depth 1` to limit the depth of the cloned history and thus considerably speed up a clone.

**Comment by cmnrd** [comment]
What should we do with this one? Rewriting the history will be a major break for everyone using this repository. We probably have to accept that there are some large files on the history...

**Comment by cmnrd** [comment]
I got curious and made a fresh clone. With 184 MiB (including all submodules) our repository isn't too large. I have seen much worse. And `git clone --depth 1` mitigates the problem entirely.
