### ISSUE TITLE
Remove logic for handling examples from testing framework

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/lingua-franca#1079]
After the examples were relocated to a separate repo, the logic for handling examples in the testin framework is no longer needed.

**Comment by cmnrd** [comment]
Do we still want to test our examples? I noticed that there is currently no CI in the examples repo.

**Comment by cmnrd** [comment]
Oh, I just noticed https://github.com/lf-lang/examples-lingua-franca/issues/1
