### ISSUE TITLE
Code generated for reactions with multi port dependencies not correct

### ISSUE THREAD

**Issue by jhaye** [lf-lang/lingua-franca#1082]
When compiling a Rust LF project where a reaction has a multi port as a dependency, the generated code only refers to it as a simple port. For example, when trying to implement the FilterBank benchmark, I have encountered the problem [here](https://github.com/lf-lang/benchmarks-lingua-franca/blob/main/Rust/Savina/src/parallelism/FilterBank.lf#L319). The generated code looks like this:

```Rust
// --- reaction(startup) -> banks.setF, banks.setH {= ... =}
fn react_0(&mut self,
               #[allow(unused)] ctx: &mut ::reactor_rt::ReactionCtx,
               banks__setF: ::reactor_rt::WritablePort<Matrix<f64>>,
               banks__setH: ::reactor_rt::WritablePort<Matrix<f64>>,) 
{ ... }
```

However, if this were correctly identified as a multi port, it should be a [`WritablePortBank`](https://lf-lang.github.io/reactor-rust/reactor_rt/struct.WritablePortBank.html).

I have dug in the code generator, and the place where this code is generated is in [`ReactorComponent.toBorrowedType`](https://github.com/lf-lang/lingua-franca/blob/master/org.lflang/src/org/lflang/generator/rust/RustReactorEmitter.kt#L384). Apparently in this case the `isMultiport` variable isn't correctly set for this reactor component.

Unfortunately my Kotlin skills aren't good enough yet to properly follow the call graph and identify the underlying issue.

**Comment by oowekyala** [comment]
Ref #806
