### ISSUE TITLE
Smarter default number of threads

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#1096]
Whenever I run an LF program on my laptop, I get by default 16 worker threads. For a small program, this adds a lot of overhead.  It would be easy to analyze the program while calculating levels to come up with a smarter default. That analysis already calculates the depth of the reaction graph.  It could also calculate the width and cap the default number of threads with that number.

**Comment by erlingrj** [comment]
The issue remains for C++ and Rust. For Cpp it would be possible to adress the issue in a similar way. But then we need to create the ReactionInstanceGraph in the CppGenerator also.

In another issue you indicated that this might not be desirable since the Cpp target does that at runtime during boot.

**Comment by lhstrh** [comment]
Inviting @cmnrd and @jhaye to comment on this.

**Comment by jhaye** [comment]
In the Rust runtime we use [rayon](https://crates.io/crates/rayon) to spread work across threads. If no `workers` argument is supplied, it creates a thread pool with the number of threads equal to the number of logical CPUs.

[It is documented](https://docs.rs/rayon/latest/rayon/struct.ThreadPoolBuilder.html#method.num_threads) that this behaviour might change in the future, where if the number of threads is not specified for the tread builder, it could automatically manage the number of threads to maximise performance.

> If num_threads is 0, or you do not call this function, then the Rayon runtime will select the number of threads automatically. At present, this is based on the RAYON_NUM_THREADS environment variable (if set), or the number of logical CPUs (otherwise). In the future, however, the default behavior may change to dynamically add or remove threads as needed.

So we might just have to wait a bit for this issue to fix itself.

**Comment by Soroosh129** [comment]
> Currently the strategy is to use as many workers as there are hardware threads. 

Well, this used to be the strategy in the C runtime as well. The new smarter strategy proposed by @edwardalee and implemented by @erlingrj looks at the maximum width of the reaction graph for a given level and chooses the minimum of that and the number of hardware threads as the default.

I don't think the strategy in the C++ runtime addresses this issue.

**Comment by cmnrd** [comment]
No, indeed it does not. However, I also currently don't see need to implement this strategy as, so farm I didn't see a significant penalty for having more threads. So I am opting for simplicity here. If someone is willing to implement other strategies and shows that there are indeed benefits, I am happy to accept PRs :)

**Comment by edwardalee** [comment]
I think you may not be seeing the overhead because of the benchmark runner. The memory and startup overhead could be significant, particularly for embedded platforms.
