### ISSUE TITLE
Asynchronous connections

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#111]
In a federated LF program (one that is distributed), we need to be able to support connections between reactors are asynchronous in the sense that they get reassigned a new timestamp upon being received using the local physical clock on the receiving machine.  The question is what syntax to use for this. If `a` and `b` are reactor instances in the main reactor, then here are some possibilities:
```
    a.out -> b.in asynchronous;
    a.out -> b.in after realtime;
    a.out -> b.in physical;
    a.out -> b.in via physical action;
```
This would be implemented via a physical action, so I'm leaning towards the third of these. The fourth is the clearest, perhaps, but rather verbose.  Thoughts?

**Comment by cmnrd** [comment]
From the options I like `physical` most. I think also `network` or `networked` could be an option. However, I am wondering whether it makes sense to make this a property of individual connections. Isn't that a property of a reactor instance? I mean, if a reactor instance is located on a remote node, then all its ports need to be connected asynchronously. Maybe something like the following could be done instead:

```
a = local new A();
b = remote new B();
a.out -> b.in;
```

Or is beeing asynchronous something that is optional for remote connections?

**Comment by edwardalee** [comment]
By default, a connection over a network will not be 'physical' in that the timestamp at the receiving end will be the timestamp from the sending end (possibly augmented by a delay).  This will give a deterministic behavior.  The proposed 'physical' keyword is to specify a nondeterministic version. The nondeterministic version does not rely on clock synchronization and does not need a centralized coordinator.

**Comment by lhstrh** [comment]
We could also alter the arrow to signify asynchronous transfer, like:

```
a = local new A();
b = remote new B();
a.out ~> b.in;
```

**Comment by mew2ub** [comment]
I like the `physical` option the most here too. I think the distinction between using the local physical clock and a PTIDES-like notion of model time for time stamping connections maps nicely onto the existing `physical` and `logical` keywords for actions. Especially if we might implement the connection via the corresponding action type. We can get double value out of the keywords.

The squiggly arrow is a good graphical way to designate a different kind of connection. But it doesn't leverage existing concepts like the keywords do. Maybe it could be an alternative syntax?

Is there any value in be allowing non-federated reactors to communicate with each other by this kind of asynchronous connection?

**Comment by edwardalee** [comment]
It could possibly be useful even on a connection within a federate, perhaps.  It can be used to fine tune the meaning of a deadline, or to measure execution times, for example.
