### ISSUE TITLE
User facing utility functions such as `info_print` should also have `lf_` prefix

### ISSUE THREAD

**Issue by housengw** [lf-lang/lingua-franca#1124]
As discussed here: https://github.com/lf-lang/website-lingua-franca/pull/47#discussion_r861307854
There are some user facing util functions that do not yet have an `lf_` prefix

**Comment by lhstrh** [comment]
Should the `lf_*_print prototypes also be listed (or included) in `ctarget.h`?

**Comment by housengw** [comment]
i think so.

**Comment by edwardalee** [comment]
I suggest renaming `info_print` to `lf_print`, rather than just adding a prefix. The others could just get a prefix.

**Comment by lhstrh** [comment]
I like that idea. If we do this I would go for lf_print_error etc (switch order of error and print).
