### ISSUE TITLE
Introduce a thread-safe logging API for Rust

### ISSUE THREAD

**Issue by cmnrd** [lf-lang/lingua-franca#1138]
In analogy to the C and C++ runtimes, the Rust runtime should provide a thread-safe logging API that is visible in reaction scope. This API should also respect the `logging` target property.

**Comment by jhaye** [comment]
I'm almost certain that the existing logging implementation is thread-safe. I'll check later today to confirm.

The reason why output for the test is garbled, is because it writes directly to STDOUT, just like the C++ test I copied it from.

**Comment by cmnrd** [comment]
Ah, ok. If there is already a logging API, then the issue is of course obsolete ;)

**Comment by jhaye** [comment]
As I suspected, this is already the case.
