### ISSUE TITLE
"Required target resource not found" in Epoch 0.2.0

### ISSUE THREAD

**Issue by erlingrj** [lf-lang/lingua-franca#1142]
When opening the HelloWorld in C on Epoch 0.2.0 I get the following warning:

```A required target resource could not be found: /lib/c/reactor-c/core/modal_models/modes.h
Perhaps
   a git submodule is missing or not up to date.
See https://github.com/icyphy/lingua-franca/wiki/downloading-and-building#clone-the-lingua-franca-repository.
Also
   try to refresh and clean the project explorer if working from
   eclipse. - See error log for details
```

Here is a screenshot
![Screenshot from 2022-05-05 08-49-01](https://user-images.githubusercontent.com/21197938/166874728-28b36a9a-c2c0-42db-aee1-88952ac0fa9b.png)

lfc-0.2.0 is working

**Comment by erlingrj** [comment]
Update: As suggested by Marten, I tried the nightly build and there it compiles. Only left with warnings about usage of deprecated info_prin
![Screenshot from 2022-05-05 08-57-33](https://user-images.githubusercontent.com/21197938/166875645-245202ae-5cf7-42b6-bd96-20beab24418e.png)
t

**Comment by lhstrh** [comment]
Thanks! Looks like a problem with our release automation then. I'll look into it. Will make sure it is fixed before we push out a patch (which will also fix these warnings, of course).

**Comment by cmnrd** [comment]
It is more likely my fault... I manually updated the artifacts since they didn't work on java 17. Probably I hadn't checked out the latest submodules.

**Comment by cmnrd** [comment]
@erlingrj I updated the release artifacts. Could you check if this fixes your problem?

**Comment by erlingrj** [comment]
@cmnrd Indeed it does! Thanks for the help
