### ISSUE TITLE
Mutation's trigger cannot be resolved.

### ISSUE THREAD

**Issue by Wonseo-C** [lf-lang/lingua-franca#1177]
Hello,
I added mutation syntax in LF code target by TS([Sieve.ts](https://github.com/lf-lang/reactor-ts/blob/master/src/benchmark/Sieve.ts) -> Sieve.lf),
then I faced a problem that the input port could not be resolved.

The followed image is the LF code and error message.
<img width="259" alt="스크린샷 2022-05-18 오후 1 11 05" src="https://user-images.githubusercontent.com/88364973/168955742-3e5eaed4-ad97-45f5-b765-191b9efdd112.png">
<img width="610" alt="스크린샷 2022-05-18 오후 12 33 01" src="https://user-images.githubusercontent.com/88364973/168955755-21c33446-efee-4fa0-9c4d-1df6f97ebea6.png">

I think that mutation should have an "inp" trigger like this...
<img width="549" alt="스크린샷 2022-05-18 오후 12 33 35" src="https://user-images.githubusercontent.com/88364973/168956070-2e01ab3c-d9de-4103-9ca3-5e73515859ca.png">

But without resolving the mutation's port, I cannot generate the trigger.
<img width="544" alt="스크린샷 2022-05-18 오후 12 33 46" src="https://user-images.githubusercontent.com/88364973/168956109-52ddcabb-0b9c-4fa8-9315-ed3bcca1c98c.png">

**Comment by hokeun** [comment]
@lhstrh Could you please take a look at this issue when you get a chance? Thanks!

**Comment by lhstrh** [comment]
Can you point me to the branch that you're working on?

**Comment by Wonseo-C** [comment]
@lhstrh Do you mean the branch which contains "Sieve.lf"?

**Comment by hokeun** [comment]
> @lhstrh Do you mean the branch which contains "Sieve.lf"?

I think Marten asked the branches that you were on when you got this error, both 1) lingua-franca, and 2) reactor-ts.
@Wonseo-C I guess you were probably on master branches (or your own branch based on the master branch) for both repos? Also, were the branches up-to-date (i.e., did you do git pull)?

It will be helpful for others to reproduce the same error if you share the environment you were in when you got this error.

**Comment by lhstrh** [comment]
You're describing an error thrown by the Lingua Franca compiler. Which version of it are you using? Currently, I don't believe there is support for mutations in any of the code generators, so do you happen to be partway implementing it? If so, which branch should I check out see your progress? I can probably provide a patch to that branch to make this problem go away...

**Comment by Wonseo-C** [comment]
@lhstrh Yes! I changed the TS code generator, and then the last capture image is the generated code.
But, I faced another error, so I solved that problem. Then I'll share the branch that I have been working on...

**Comment by Wonseo-C** [comment]
---
* My workspace branch : https://github.com/Wonseo-C/lingua-franca/tree/choi
(Generate mutation code commit : https://github.com/Wonseo-C/lingua-franca/commit/1f1997e85472601d63b24b5ff4bb7eff0dece2a1)
* Sieve.lf code repo : https://github.com/hyu-iot/lf_benchmark_choi/blob/main/Choi/src/LF/Sieve.lf
---
I think there is some issue in [LinguaFrancaSynthesis.java](https://github.com/lf-lang/lingua-franca/blob/master/org.lflang.diagram/src/org/lflang/diagram/synthesis/LinguaFrancaSynthesis.java)

**Comment by Wonseo-C** [comment]
Another problem was occurred: Mutation effect syntax error
<img width="552" alt="스크린샷 2022-05-25 오후 1 04 50" src="https://user-images.githubusercontent.com/88364973/170177403-e8bb0ac3-0ce6-4e28-a6c9-69744c6f870b.png">
---
<img width="665" alt="스크린샷 2022-05-25 오후 1 06 47" src="https://user-images.githubusercontent.com/88364973/170177626-60426f48-f014-4d2e-b6ca-257673059e81.png">
<img width="663" alt="스크린샷 2022-05-25 오후 1 06 56" src="https://user-images.githubusercontent.com/88364973/170177636-248f0aa3-d9f3-42ef-b1f8-332e3d3c394e.png">

Like this code, there are some differences between the reaction and mutation effects ([VarRef])...
Why are they different, and how do I fix this error? @lhstrh 
(Now I try to implement it without using the writable port.)

**Comment by lhstrh** [comment]
I'll have a look at your branch tomorrow.

**Comment by Wonseo-C** [comment]
### 1. Mutation Effect Problem
![스크린샷 2022-05-30 오후 5 02 09](https://user-images.githubusercontent.com/88364973/170949210-2a19817b-c63e-4c92-b40e-42827f851936.png)
I fixed the mutation effect error by changing [LinguaFranca.xtext](https://github.com/lf-lang/lingua-franca/blob/master/org.lflang/src/org/lflang/LinguaFranca.xtext)... (same as reaction's effect)
Is it the right way? Or do I have to use [VarRef] because the mutation effect has strong intentions about using [VarRef]?

### 2. Implement Mutation in LF
Looking at [Sieve.lf](https://github.com/hyu-iot/lf_benchmark_choi/blob/main/Choi/src/LF/Sieve.lf), and [my working branch](https://github.com/Wonseo-C/lingua-franca/tree/choi)  I entirely implemented mutation. And it was generated well to TS.
But there are some things to discuss...
* [line 76](https://github.com/hyu-iot/lf_benchmark_choi/blob/0b71d081d40bfe8615354231bd27fc395163a572/Choi/src/LF/Sieve.lf#L76): There is an unknown outport, so we should casting type to WritablePort. https://github.com/Wonseo-C/lingua-franca/commit/33c6943da190dbec681a1539d158f1bb23370df7 . And also, it has a problem when generating JS code. There are some uninterpreted part ".getport()". So I deleted this on my hand, then it worked well. Under code is generated JS code.
![스크린샷 2022-05-30 오후 5 32 23](https://user-images.githubusercontent.com/88364973/170952097-4401d37f-c4bb-4e0d-928b-cb0cb0eda996.png)
* [line 70](https://github.com/hyu-iot/lf_benchmark_choi/blob/0b71d081d40bfe8615354231bd27fc395163a572/Choi/src/LF/Sieve.lf#L70), [line 77](https://github.com/hyu-iot/lf_benchmark_choi/blob/0b71d081d40bfe8615354231bd27fc395163a572/Choi/src/LF/Sieve.lf#L77): I'll try to fix "this." to "util." (discussed with my adviser @hokeun). It is the right way?

**Comment by Wonseo-C** [comment]
The final work is on the https://github.com/lf-lang/lingua-franca/pull/1252 PR.
