### ISSUE TITLE
Nondeterministic test failure in Rust

### ISSUE THREAD

**Issue by petervdonovan** [lf-lang/lingua-franca#1184]
While I was fixing whitespace in the tests, I got [this test failure in CI](https://github.com/lf-lang/lingua-franca/runs/6513057606?check_suite_focus=true):
```+---------------------------------------------------------------------------+
    Failed: src/Timers.lf
    -----------------------------------------------------------------------------
    Reason: Test did not pass. Exit code: 101
    Compilation output:
    Generating code for: file:/home/runner/work/lingua-franca/lingua-franca/test/Rust/src/Timers.lf
    ******** mode: STANDALONE
    ******** generated sources: /home/runner/work/lingua-franca/lingua-franca/test/Rust/src-gen/Timers
    --- Current working directory: /home/runner/work/lingua-franca/lingua-franca/test/Rust/src-gen/Timers
    --- Executing command: cargo +nightly build --out-dir /home/runner/work/lingua-franca/lingua-franca/test/Rust/bin -Z unstable-options --message-format json-diagnostic-rendered-ansi
    SUCCESS (compiling generated Rust code)
    Generated source code is in /home/runner/work/lingua-franca/lingua-franca/test/Rust/src-gen/Timers
    Compiled binary is in /home/runner/work/lingua-franca/lingua-franca/test/Rust/bin

    Execution output:
    thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
      left: `1`,
     right: `2`', Timers/src/reactors/timers.rs:37:9
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

    +---------------------------------------------------------------------------+
```
 
This test was not touched in my branch, and I could not reproduce this test failure locally. [The test passed after my next push](https://github.com/lf-lang/lingua-franca/actions/runs/2354124903), even though none of my changes were related to the test.

**Comment by jhaye** [comment]
It could definitely be related, but it's hard to tell.

I could reproduce the failure locally. Running the test 100 times, I got 2 failures. However, they are different:
```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `-1`', Timers/src/reactors/timers.rs:37:9
```

It seems like `shutdown` is triggered before some other reaction can increase the counter.

This issue does not arise when compiling with threading disabled.

**Comment by petervdonovan** [comment]
This might be unrelated, but I just observed a [benchmark test failure in Rust](https://github.com/lf-lang/lingua-franca/runs/7571372767?check_suite_focus=true) in the formatting branch. The benchmark was not reformatted, so a deterministic test failure would be really unexpected in that branch.

**Comment by jhaye** [comment]
The best thing we can do right now to prevent this error from happening when running CI is to hard code the number of workers as 1.

**Comment by jhaye** [comment]
I just ran this with the latest changes 1000 times and succeeded every time. I think it's safe to assume that the issue is gone.
