### ISSUE TITLE
Strange error in the prepare-build-env action

### ISSUE THREAD

**Issue by Soroosh129** [lf-lang/lingua-franca#1193]
I have been seeing the following intermittent error in the CI that seems to be related to the [prepare-build-env action](https://github.com/lf-lang/lingua-franca/blob/master/.github/actions/prepare-build-env/action.yml):

![image](https://user-images.githubusercontent.com/4221770/170287761-bc542b30-0c9d-45ad-bf10-4bd3ad28f3fb.png)

Specifically, it looks like the error is related to [gradle/wrapper-validation-action@v1.0.4](https://github.com/gradle/wrapper-validation-action). 

Here is an example of the CI failing (I think you need to be signed in and have permission to be able to properly follow this link): https://github.com/lf-lang/lingua-franca/runs/6593905594?check_suite_focus=true#step:3:43

**Comment by lhstrh** [comment]
I've seen it too and have been tempted to disable the check, but it's not a bad idea to check the integrity of `gradlew`... I've recently bumped to the latest version, so I'm not sure what else to do....

**Comment by cmnrd** [comment]
I think we can close this one.
