### ISSUE TITLE
Cryptic Error on GitHub Actions: `Error: <!DOCTYPE html>`

### ISSUE THREAD

**Issue by Soroosh129** [lf-lang/lingua-franca#1196]
I have been getting the following error fairly regularly:
![image](https://user-images.githubusercontent.com/4221770/170547520-214210db-2a39-4215-847a-8daa421e17ac.png)

Generally, re-running the CI fixes this issue.

Here is an example of a failing task: https://github.com/lf-lang/lingua-franca/runs/6613476780?check_suite_focus=true#step:3:21

**Comment by petervdonovan** [comment]
I have the same issue in the `vscode-lingua-franca` repo, only on MacOS. This makes me think the problem is unrelated to anything we have done. Surprisingly, I have not seen any relevant bug reports [here](https://github.com/actions/setup-java/issues), though.

**Comment by Soroosh129** [comment]
It looks like an unexpected CloudFlare HTML file is being downloaded instead of the actual thing:
![image](https://user-images.githubusercontent.com/4221770/170549653-0d1aa611-e7df-48d3-9cbd-eab3d0c25f9e.png)

I copied the output of the CI task into a `.html` file and opened it in a browser.

**Comment by lhstrh** [comment]
I saw a commit from @petervdonovan that attempted to address this issue by choosing a different Java distribution? Did it work?
[ff8996](https://github.com/lf-lang/lingua-franca/commit/ff89966b566fbfdeac6a25b7df685dd27f7c8e9e)

**Comment by petervdonovan** [comment]
> Did it work?

No, it did not work. It did not work to revert to an older `setup-java` version, either.
