### ISSUE TITLE
Deadline of 0 is interpreted as no deadline

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#1203]
When you enter a deadline of 0 msec, the deadline never gets violated, at least in the C target.  This is counterintuitive, as a deadline of 0 might be used to test the deadline violation handler.  I suspect that 0 is being used as a flag for no deadline, but it would be better to use something else (e.g. FOREVER?).

**Comment by lhstrh** [comment]
Fixed by @billy-bao (see #1217).
