### ISSUE TITLE
Minor issues with diagrams of modal reactors

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/lingua-franca#1219]
It looks like the state variable isn't rendered quite correctly in the diagram:
![image](https://user-images.githubusercontent.com/19938940/173119911-40db4248-d00a-4c1a-85be-d855e5785d9d.png)

_Originally posted by @lhstrh in https://github.com/lf-lang/lingua-franca/pull/1169#discussion_r894757345_

Also:

The rendering of the `reset` trigger seems a bit off:

![image](https://user-images.githubusercontent.com/19938940/173121919-d5c4b2b9-ace4-4295-ba36-688b01801f62.png)

I would actually like to propose an alternative visual syntax. How about something along these lines:
![image](https://user-images.githubusercontent.com/19938940/173123030-6fa9810b-51de-403c-a57e-f133314b2460.png)

_Originally posted by @lhstrh in https://github.com/lf-lang/lingua-franca/pull/1169#discussion_r894771808_

**Comment by a-sr** [comment]
It seems using unicode characters wasn't the best idea if I cannot assure that all platforms use fonts that implement the required planes.
I will remodel the appearance according to your suggestions.
