### ISSUE TITLE
Minor issues with the syntax of modal reactors

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/lingua-franca#1220]
It appears that a `reset` transition is the default, meaning that is no modifier is given in the transition effect, this is to mean that it is a reset transition. This could be confusing, because it may suggest that a "normal" transition is of a different kind than `reset` or `continue`. We had a similar problem with actions, and decided that it would be better to require a disambiguation from the programmer and thus only allow `logical action` or `physical action`, and not just `action`. I think we should take the same approach here, and enforce this in the validator so we can present a useful error message.

_Originally posted by @lhstrh in https://github.com/lf-lang/lingua-franca/pull/1169#discussion_r894762670_

And:

I'm still a bit on the fence about the `continue` keyword. If refer to this a "history transition" and label it with an "H" in the diagram, then why don't we just use the `history` keyword and avoid all confusion?

_Originally posted by @lhstrh in https://github.com/lf-lang/lingua-franca/pull/1169#discussion_r894763524_

**Comment by a-sr** [comment]
Regarding `reset` as default, I can understand your concerns. However, I am still in favor of having a default without modifier. For actions it always makes a difference whether you choose `physical` or `logical`. This is not the case for transitions. If a mode is only entered once or does not have state variables or timers/actions. Both transitions behave the same. The Furuta pendulum is such an example, where choosing a transition type simply makes no difference. Hence, I think it makes sense to not enforce a specific type, at least for convenience.
I could add a warning/error that if there is a difference, advises the user to explicitly state the type.

**Comment by a-sr** [comment]
I introduced the `continue` keyword because I thought it is more descriptive in terms of the effect. You either reset or continue the target mode.
The term "history transition" and the label "H", was added to appeal to people that are used to statecharts.

I agree, that we should harmonize this. Using `history` is fine with me. I will prepare a PR.
