### ISSUE TITLE
Epoch does not support Raspberry Pi (ARM-based processors)

### ISSUE THREAD

**Issue by ali95123** [lf-lang/lingua-franca#1222]
I would like to have LF on Raspberry Pi 4B, however, it seems currently LF does not support ARM-based processors.

**Comment by lhstrh** [comment]
Do you wish to develop LF code on ARM, or would you like to deploy LF programs on ARM? If the latter, what target did you want to use?

For developing LF on ARM, my guess is that our CLI tools and VS Code extension should work just fine... It's true that our Epoch IDE currently does not support ARM...

**Comment by lhstrh** [comment]
Tagging @a-sr in case he as any insights regarding building Epoch for ARM. I also found this: https://resheim.net/2013/05/running-eclipse-rcp-applications-on.html, but that's rather old documentation.

**Comment by ali95123** [comment]
> Do you wish to develop LF code on ARM, or would you like to deploy LF programs on ARM? If the latter, what target did you want to use?
> 
> For developing LF on ARM, my guess is that our CLI tools and VS Code extension should work just fine... It's true that our Epoch IDE currently does not support ARM...

I want to both develop and deploy LF code on Raspberry Pi. In the worst case, I would be able to deploy LF code on Raspberry Pi. My target language is Python.

**Comment by ali95123** [comment]
> Do you wish to develop LF code on ARM, or would you like to deploy LF programs on ARM? If the latter, what target did you want to use?
> 
> For developing LF on ARM, my guess is that our CLI tools and VS Code extension should work just fine... It's true that our Epoch IDE currently does not support ARM...

I tried to install Epoch (got error: Cannot execute binary file: Exec format error) and run it on Raspberry Pi. I have not tried to deploy an LF code so far.

**Comment by Soroosh129** [comment]
Have you tried the [Eclipse developer setup](https://www.lf-lang.org/docs/handbook/eclipse-oomph)?

**Comment by ali95123** [comment]
> 

Not yet. Will it work?

**Comment by lhstrh** [comment]
The easiest option would be to use our VS Code extension, which has a one-click install: https://marketplace.visualstudio.com/items?itemName=lf-lang.vscode-lingua-franca

Please let us know if this works for you.

**Comment by ali95123** [comment]
I tried VS code on Rasbian OS on Raspberry Pi. I deployed my three assignments (software design for CPS) which were in C target and they worked. However, I am having some struggles with python targets which might be related to some packages or ... to work.

**Comment by Soroosh129** [comment]
I’m glad the VSCode extension worked. I’ve renamed the issue to more accurately reflect the issue.

> However, I am having some struggles with python targets which might be related to some packages or ... to work.

Could you please create a new issue with as much detail as you could give us? Thanks!

**Comment by a-sr** [comment]
> Tagging @a-sr in case he as any insights regarding building Epoch for ARM. I also found this: https://resheim.net/2013/05/running-eclipse-rcp-applications-on.html, but that's rather old documentation.

No, I don't have any experience with Eclipse on ARM. Eclipse itself seems to support ARM, hence, the developer setup might work.

**Comment by lhstrh** [comment]
Closing this issue noting that the solution appears to build on ARM. If there is a demand for releasing a version of Epoch built for ARM, then feel welcome to comment on this issue and we can re-open it. @ali95123: if you could share an experience report that would be useful! Did you end up getting it to work?

**Comment by ali95123** [comment]
Yes. It worked on Raspberry Pi by means of VScode. Also, I could use compiled files and run them on Raspberry Pi.
