### ISSUE TITLE
How many actors can send message to each other?

### ISSUE THREAD

**Issue by ali95123** [lf-lang/lingua-franca#1236]
I want to create a large number of actors and each actor should be able to send message to the rest of actors. Is it the only solution to define many I/O ports? Since it makes it very complicated. Is there a function to route messages between actors?

**Comment by edwardalee** [comment]
See https://www.lf-lang.org/docs/handbook/multiports-and-banks

**Comment by cmnrd** [comment]
In order to address other reactors, you can use the pattern described under "Interleaved Connections" in the handbook. Let us know, if this doesn't apply to your usecase for some reason.

**Comment by ali95123** [comment]
Thanks for your help. I am using the provided link and guidance. Let's see if I can proceed with them.

**Comment by cmnrd** [comment]
Closing this for now. Feel free to reopen if you have more questions.
