### ISSUE TITLE
Epoch welcome page points to wiki, not to web page

### ISSUE THREAD

**Issue by cmnrd** [lf-lang/lingua-franca#1237]
In release 0.2.1 and in the current master version the Epoch welcome page points to our wiki and not to the website. I noticed #1152, so I would expect Epoch to show the website, but apparently this is not what currently happens. Actually, `org.lflang.product/intro/content.xml` correctly points to `https://www.lf-lang.org/`, but the welcome page shows the wiki nonetheless... I suppose we need to also adjust it in some other place. Any ideas where?

**Comment by lhstrh** [comment]
I updated it to point to https://www.lf-lang.org/ but let me know if you think it should point to another page.

**Comment by cmnrd** [comment]
That is a lot better :) Maybe we should consider introducing a dedicated landing page for Epoch. Maybe a section in the handbook? Would be nice if there are some Epoch specific pointers for users to get started.
