### ISSUE TITLE
Determine logical execution time (LET) for each reaction based on immediate downstream

### ISSUE THREAD

**Issue by hokeun** [lf-lang/lingua-franca#1260]
Reference suggested by @Soroosh129 : https://github.com/lf-lang/lingua-franca/blob/3a1f550176af967811b200f28f22b1748f17392e/org.lflang/src/org/lflang/generator/ReactionInstance.java#L163

**Comment by Wonseo-C** [comment]
```    
timer t(0, 100 msec);

logical action a(60 msec):int;
logical action b(40 msec):int;

input x:int;
output y:int;

state count:int(0);

reaction(t) -> y, a, b {=
   	lf_set(y, self->count);
   	self->count++;
	lf_schedule_int(a, 0, 0);
	lf_schedule_int(b, 0, 0);
=}
```

Look at this pr. https://github.com/lf-lang/lingua-franca/pull/1277.
I fix the code to use Timevalue rather than its magnitude. (advised by @Soroosh129 )

Then, I tried to experiment with getting the minimum delay.
In this code, I get 40 ms in "this.LET"

**Comment by Soroosh129** [comment]
@Wonseo-C perhaps it would make sense to add some sort of tests for the newly added `getLET()`?

**Comment by Soroosh129** [comment]
This looks like a transient error in SSL. It should go away with a re-run.

**Comment by Wonseo-C** [comment]
The final work is on the https://github.com/lf-lang/lingua-franca/pull/1292.
