### ISSUE TITLE
Reactions do not consistently trigger banks

### ISSUE THREAD

**Issue by a-sr** [lf-lang/lingua-franca#1278]
If two reactor banks are triggered by the same reaction, the bank that is listed as first effect, will only get a single bank member triggered.

This is an example:
```
target C;

reactor Hello {
    input I:int;
    
    reaction(I) {=
        printf("Hello\n");
    =}
}
reactor World {
    input I:int;
    
    reaction(I) {=
        printf("World\n");
    =}
}

main reactor {
    hellos = new[3] Hello()
    worlds = new[3] World()

    reaction(startup) -> hellos.I, worlds.I {=
        for(int i = 0; i < hellos_width; i++) {
            lf_set(hellos[i].I, true);
        }
        for(int i = 0; i < worlds_width; i++) {
            lf_set(worlds[i].I, true);
        }
    =}
}
```
The output is:
```
World
World
World
Hello
```

Swapping the order of the effects will output 3 x `Hello`, 1 x `World`.
Splitting the reaction into two, one for each bank, yields the correct behavior.

**Comment by edwardalee** [comment]
PR #1289 fixes this.  The problem was a simple indexing issue that failed to take into account the width of the first bank.

**Comment by edwardalee** [comment]
Unfortunately, my fix does not work. Reopening this issue and converting the PR #1289 to a draft.
