### ISSUE TITLE
Pipenv - package versions have conflicting dependencies

### ISSUE THREAD

**Issue by moinakhter** [lf-lang/lingua-franca#1281]
I was using **Lingua-Franca** in an AI project, I was facing some conflict dependencies issues with matplotlib, openai, and padas packages because lingua-franca is using **python-dateutil==2.6.0** version and other packages are using **python-dateutil >= 2.7** or **python-dateutil >= 2.8**. 

To set up the **Pipenv environment** properly without dependencies issues, I have to modify the **Lingua-Franca** source code and copy the _Lingua-Franca Package_ in the project dependencies directory to avoid dependencies conflict.

Is there any other solution available to avoid conflicting dependencies with _**python-dateutil's**_ version?

**Comment by lhstrh** [comment]
@moinakhter, any updates on this? If we can't reproduce it on our side I'm afraid we cannot be of much help.

**Comment by moinakhter** [comment]
@Soroosh129 , @lhstrh , please update the version of python-dateutil library.

 In the **Lingua-franca** it is required **python-dateutil==2.6.0**, in the other python libraries people are using **python-dateutil > 2.7.0** version, I was facing a dependencies conflict issue.
 
I resolved this issue, I am using the **Lingua-franca** package from my project directory instead of the project's environment.

**Comment by cmnrd** [comment]
I was double checking today, but we are not aware of any dependencies on python-dateutil. Are you using Epoch (The Eclipse-based IDE for LF)? It might be that Epoch's python extensions includes an outdated version of python-dateutil.

Could you provide us with a minimal code example and the precise steps that you do? Also which operating system are you using? This would help us to reproduce and fix the issue.

**Comment by moinakhter** [comment]
I am using Ubuntu.

I used Pipenv for the installing packages and creating the environment. pipenv check dependencies. please check attached screenshot of the error, as far as I know it is related to python-dateutil, whenever i am installing Lingua-franca using pipenv it causing error because other package are using `python-dateutil version >= 2.7.0`, Lingua-franca using `python-dateutil==2.6.0`. 

![Screenshot from 2022-07-19 13-23-19](https://user-images.githubusercontent.com/39314469/179730361-773a0f59-7002-4691-af26-59d8ffdcc1fd.png)

**Comment by cmnrd** [comment]
Ok, now I understand the confusion. You are using the [lingua-franca](https://pypi.org/project/lingua-franca/) python package. This is another project and not related to our work.
