### ISSUE TITLE
Visual Studio Code needs Java 17

### ISSUE THREAD

**Issue by janettecardoso** [lf-lang/lingua-franca#1373]
The main page says "All Lingua Franca tools require Java 17 or up".
I followed the instructions for VSC here:
https://www.lf-lang.org/docs/handbook/code-extension?target=c
I did "ext install lf-lang.vscode-lingua-franca", clicked on the icon, and did ctrl-shift-P
(did not see Lingua Franca: build), and I have these msgs:
- "command 'klighd-vscode.diagram.open' not found"
- "Java version 17 is required for Lingua Franca diagrams and code analysis, but the version detected on your system is 18.0.2."

So, it seems that only 17 will work with Visual Studio Code, or I missed something? It works well with Epoch.

**Comment by lhstrh** [comment]
Thanks for reporting this, Janette! I'm actually not sure whether the check in VS Code or the documentation needs to be updated. We'll figure this out and can back to you.

**Comment by lhstrh** [comment]
We fixed this in https://github.com/lf-lang/vscode-lingua-franca/pull/83, which will be included in the next release.
