### ISSUE TITLE
Epoch is not usable on Wayland with screen scaling enabled

### ISSUE THREAD

**Issue by cmnrd** [lf-lang/lingua-franca#1388]
When opening Epoch on my laptop using Wayland and with screen scaling enabled on a 4K monitor, it looks like this:
![Screenshot_20220930_103021](https://user-images.githubusercontent.com/6460123/193327356-c4036a1b-8958-4935-9fc8-502d66593da4.png)

I can work around the problem by setting screen scaling to 100%, but it doesn't really solve the problem because then I can barely see the text. I am not sure if this is a problem on our end or rather a problem with Eclipse in general. Perhabs @a-sr can comment on this?

**Comment by a-sr** [comment]
I have heard before that high DPI displays caused problems with Eclipse in the past but this black bock for the diagram looks new to me.
Sorry, I have no idea how to approach this issue.

**Comment by cmnrd** [comment]
Since I mostly use the Code plugin it is not a big problem for me. Most likely there is not much we can do anyway and we should probably not bother. I just wanted to open this so that the problem is documented.

**Comment by lhstrh** [comment]
I actually experience similar problems with both Eclipse and IntelliJ. They seem to come up particularly when there is an external screen involved.... No scaling issues with VS Code so far.
