### ISSUE TITLE
CLI arg validation

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/lingua-franca#1429]
Currently, CLI arguments are passed on to the code generator as properties almost blindly. It should validate arguments in `Lfc.java` (and add unit tests that cover that code).

**Comment by oowekyala** [comment]
While #1467 adds some tests, there is still no thorough validation of all arguments. It's tedious to do with Apache CLI, it would be easier if we implement #1468

**Comment by oowekyala** [comment]
Yes, I think the tests are in a much better place now, thanks to PRs like #1534 and #1686.
