### ISSUE TITLE
Gradle build failing due to 403 error

### ISSUE THREAD

**Issue by schoeberl** [lf-lang/lingua-franca#1435]
Maybe this is an issue of my local setup, but the build with gradle failed with following issue:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'lingua-franca'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve com.google.guava:guava:[10.0.1,14.0.1].
     Required by:
         project : > org.xtext:xtext-gradle-plugin:3.0.0 > org.eclipse.xtend:org.eclipse.xtend.lib:2.9.0 > org.eclipse.xtext:org.eclipse.xtext.xbase.lib:2.9.0
         project : > org.xtext:xtext-gradle-plugin:3.0.0 > org.eclipse.xtend:org.eclipse.xtend.lib:2.9.0 > org.eclipse.xtend:org.eclipse.xtend.lib.macro:2.9.0
      > Failed to list versions for com.google.guava:guava.
         > Unable to load Maven meta-data from https://plugins.gradle.org/m2/com/google/guava/guava/maven-metadata.xml.
            > Could not GET 'https://jcenter.bintray.com/com/google/guava/guava/maven-metadata.xml'.
               > Read timed out
```
However, compilation with ```mvn``` worked.

**Comment by schoeberl** [comment]
As expected, I got the same issue when opening lingua-franca with IntelliJ.

**Comment by lhstrh** [comment]
The nightly build also started failing with the same error today: https://github.com/lf-lang/lingua-franca/actions/runs/3358762219/jobs/5566112989

Looks like some server misconfiguration...

**Comment by hokeun** [comment]
We're experiencing a similar issue here. FYI, @Jakio815 @DukiChoi.

**Comment by hokeun** [comment]
Could this be because of the old gradle version? https://stackoverflow.com/questions/68255521/could-not-get-https-google-bintray-com-maven-metadata-xml-received-stat

**Comment by lhstrh** [comment]
The version of Gradle that we use is pretty new. We use `7.5.1`.

**Comment by lhstrh** [comment]
Also see https://github.com/xtext/xtext-gradle-plugin/issues/209

**Comment by lhstrh** [comment]
Looks like the JCenter outage has been resolved and building works again.
