### ISSUE TITLE
cross compilation issue

### ISSUE THREAD

**Issue by schoeberl** [lf-lang/lingua-franca#1444]
I am trying to get LF (again) running on Patmos. Using ```__patmos__```, which the Patmos C compiler sets, in ```platform.h``` to select the POSIX version of LF threading. However, I run ```cmake``` under Linux. Looks like ```cmake``` is doing some platform detection resulting in not using the POSIX in the LF-generated C code.

**Comment by cmnrd** [comment]
This seems to be closer related to the C code generation and build than to cmake. @petervdonovan can you help with this?

**Comment by petervdonovan** [comment]
It isn't totally clear to me what is happening since I do not know which branch this code is in/whether the changes are pushed. However the problem could be [here](https://github.com/lf-lang/reactor-c/blob/5b772a5322b46b0738fcbd31e33f1175fde3c236/core/platform/lf_linux_support.c#L36) or [here](https://github.com/lf-lang/reactor-c/blob/5b772a5322b46b0738fcbd31e33f1175fde3c236/core/platform/Platform.cmake#L3). Just editing the header files will be insufficient since different function implementations need to be linked depending on the platform.

**Comment by schoeberl** [comment]
I am working from plain master, not from a branch.

**Comment by schoeberl** [comment]
Two things I find quite confusing: (1) the generated code in src-gen contains two copies of the C code and header files, and (2) even when I specify ```threading: false```, there is code included with pthread library calls.

The current status with some manual tweaking is that I can compile but have link errors.

Shall we start a new lf_embedded_support.c/h for embedded systems like FlexPRET, Patmos, and others?

**Comment by petervdonovan** [comment]
> (1) the generated code in src-gen contains two copies of the C code and header files

I'm not sure why that would happen. Every project that we compile from the same `src` directory has its own subdirectory in the `src-gen` directory, and each of those subdirectories has its own copy of the runtime inside. So it's normal for there to be duplication in `src-gen`, just not in the subdirectory in `src-gen` that is specific to the compiled `.lf` file.

> (2) even when I specify threading: false, there is code included with pthread library calls.

All the code should be copied, all the time, but not all the code should be linked into the executable. We use both CMake and the preprocessor to determine which code gets included, but I have been trying to avoid using conditional file copying for that purpose. Are you saying that the pthread library calls are actually being linked?

> Shall we start a new lf_embedded_support.c/h for embedded systems like FlexPRET, Patmos, and others?

@erlingrj knows more about this question than I do. For now, I think our strategy has been to use bash scripts to reach into the runtime and do an alternative build process? I think [this repository that Erling worked on (link)](https://github.com/erlingrj/lf-xmos) is an example, including the bash script and XMOS-specific platform support files.

**Comment by erlingrj** [comment]
I havnt "completed" the support for any new platform but looked at bare-metal on NRF52, multi-threading on XMOS and zephyr. The changes that are required for a new platform to be integrated with LFC is, AFAIK, the following:

1. LFC changes: The platform must be added as a target property:
```
target C {
  platform: Patmos
 }
```
This should make the LFC define a Cmake flag called CMAKE_SYSTEM_NAME and set it to "Patmos"

2. core/platform/platform.cmake
This file is included by the CMakeLists.txt and it looks at CMAKE_SYSTEM_NAME and sets the variable LF_PLATFORM_NAME which is added to the sources. Here lf_patmos_support.c should be added.

3. lf_patmos_support.c/h
The API defined in platform.h must be implemented in lf_patmos_support.c. If you have a pthread implementation you can just `#include "lf_POSIX_threads_support.c"`. This is what lf_linux_support.c does

**Comment by edwardalee** [comment]
This is useful enough information that I've started a wiki page:

https://github.com/lf-lang/lingua-franca/wiki/Supporting-a-new-platform-in-the-C-target

Please update that page as you learn more about how to do this.

**Comment by schoeberl** [comment]
> > (1) the generated code in src-gen contains two copies of the C code and header files
> 
> I'm not sure why that would happen. Every project that we compile from the same `src` directory has its own subdirectory in the `src-gen` directory, and each of those subdirectories has its own copy of the runtime inside. So it's normal for there to be duplication in `src-gen`, just not in the subdirectory in `src-gen` that is specific to the compiled `.lf` file.

No, the duplication is within a single LF program. The platform C and include files are copied twice, actually the whole core folder exists twice: one directly in the generated project and a second time under the folder include.

> 
> > (2) even when I specify threading: false, there is code included with pthread library calls.
> 
> All the code should be copied, all the time, but not all the code should be linked into the executable. We use both CMake and the preprocessor to determine which code gets included, but I have been trying to avoid using conditional file copying for that purpose. Are you saying that the pthread library calls are actually being linked?

OK, got it. For the first try, I will then just not include x_threads_support.c

> 
> > Shall we start a new lf_embedded_support.c/h for embedded systems like FlexPRET, Patmos, and others?
> 
> @erlingrj knows more about this question than I do. For now, I think our strategy has been to use bash scripts to reach into the runtime and do an alternative build process? I think [this repository that Erling worked on (link)](https://github.com/erlingrj/lf-xmos) is an example, including the bash script and XMOS-specific platform support files.

Thanks for the pointer, will use that information.

I will collect what I find in that Wiki.

**Comment by petervdonovan** [comment]
> No, the duplication is within a single LF program. The platform C and include files are copied twice, actually the whole core folder exists twice: one directly in the generated project and a second time under the folder include.

That sounds like the https://github.com/lf-lang/reactor-c/issues/25, which was fixed by a PR that was merged 16 days ago. You might want to check that you are using the latest version of `lingua-franca/master` with the `reactor-c` Git submodule updated (`git submodule update`)

**Comment by lhstrh** [comment]
Came here to say :point_up:

**Comment by schoeberl** [comment]
Update: with a crude compilation setup and hacking of generated files Patmos says "Hello in LF". At the moment just single-threaded. But that should be good for WCET analysis.

**Comment by schoeberl** [comment]
It is on the way.
