### ISSUE TITLE
Level assignment for the C target is not as expected with after delays

### ISSUE THREAD

**Issue by erlingrj** [lf-lang/lingua-franca#1446]
![image](https://user-images.githubusercontent.com/21197938/199370280-4b7c6d58-45d0-49ba-99e5-32344facf001.png)

Levels assigned are:

Sensor Reaction=0
Processing Reaction=1
Actuator Reaction=1

I expected them all to have the same level. It seems as if the problem has to do with the inserted Delay Reactors which each adds two reactions which gets strange levels:

Delay Reactor 1 (presumably between Sensor and Processing):
reaction_1=0
reaction_2=1

Delay Reactor 2 (Between Processing and Actuator)
reaction_1=0
reaction_2=2

I can try to fix this, but thought I'd ask to see if there is any comment on why it behaves like this.

**Comment by erlingrj** [comment]
This might be a misunderstanding from my side. I am using single-threaded target. It seems as if reactions are added to the `reaction_q` in "level-order". So actually at any time, you can always execute anything on the reaction queue. Thus it makes sense to order them based on the deadline not the index.

**Comment by edwardalee** [comment]
The definition of the deadline of a reaction is as follows: The deadline of a reaction is the minimum of the declared deadline of that reaction and the deadline of each downstream reaction. In other words, the "declared deadline" does not necessarily equal the deadline.

**Comment by edwardalee** [comment]
Regarding the level, the reason that the reactions in Processing and Actuator have level 1 is because the "after" delays are transformed into reactors, each of which has two reactions. One of those reactions needs to inherit the deadline of the Actuator reaction.

**Comment by erlingrj** [comment]
The current implementation of "after" is a bit unfortunate because:
1) We are not able to infer that a reaction has a LET when its only effect has an after delay.
2) We increase reaction invocation latency for the reactions triggered by the after delay.

Might be worth to consider changing after-delay from syntactic sugar to language primitive
