### ISSUE TITLE
Weird build errors occur when `src-gen` is not deleted prior to recompiling

### ISSUE THREAD

**Issue by petervdonovan** [lf-lang/lingua-franca#1460]
Example: https://github.com/lf-lang/reactor-c/issues/121

This does not occur every time. Perhaps it only happens when you switch to a different submodule version or when the previous build failed, but definitely there are various build errors that happen only when the `src-gen` directory is not deleted before compiling.

This issue was probably introduced by #1299 and its companion PRs. Originally I wanted to pretend that everything was fine and say that having to always delete the `src-gen` directory is normal, but whenever something goes wrong this bug is just one more thing that everyone has to check, so it can be a time sink.

My best guess is that the fix will involve adding a clean step in `CCompiler.java`. This should be done carefully because deleting things unnecessarily can make builds slower by making it impossible to reuse old results (although this effect should be measured -- I don't understand everything that CMake is doing).

**Comment by axmmisaka** [comment]
I discussed with professor @edwardalee today and it appears that the issue typically happens when recompiling after `lfc` is recompiled, which is, imo, expected (I don't know but I guess if you `make` a project partly with`gcc` and the rest with a fork it's not guaranteed to work); 
My plan is to compare the jar file timestamp with the generated file timestamp and recompile if the jar is newer, but your input will be appreciated.

**Comment by petervdonovan** [comment]
> the issue typically happens when recompiling after lfc is recompiled, which is, imo, expected 

Oh, great! I hope that's all it is. Yes, if that plan is not hard to implement, then it sounds like a good idea.

**Comment by cmnrd** [comment]
Can you elaborate on why it is expected that the build breaks after lfc is rebuild? Unless the bundled reactor-c or the way we generate cmake files changed, rebuilding with cmake should not be a problem. And even then most changes should not cause problems. Only if for instance a file is deleted or moved in reactor-c, I would expect problems, as then the source tree in src-gen differs from the expected tree. Note that the C++ code  is build in a very similar way and I haven't seen such problems in quite a while.

Is there a way to reproduce this error? And have you analyzed why the build fails? It seems to me that there is another problem lurking here and deleting src-gen probably just masks it instead of solving it.

**Comment by petervdonovan** [comment]
No, I have not examined this problem in depth and am not sure off the top of my head exactly how to reproduce it. Given what you mentioned about moving and deleting files, it sounds like the problem could just be that this problem was observed when switching branches from the version of `reactor-c` before the build refactoring to the newer version of `reactor-c`, in which case the problem will just go away on its own as people stop doing work on those old `reactor-c` versions.

**Comment by axmmisaka** [comment]
> Can you elaborate on why it is expected that the build breaks after lfc is rebuild? Unless the bundled reactor-c or the way we generate cmake files changed, rebuilding lfc and then recompiling an LF program should not be a problem. And even if reactor-c changes, most changes should not cause problems. Only if for instance a file is deleted or moved in reactor-c, I would expect problems, as then the source tree in src-gen differs from the expected tree. Note that the C++ code is build in a very similar way and I haven't seen such problems in quite a while.
> 
> Is there a way to reproduce this error? And have you analyzed why the build fails? It seems to me that there is another problem lurking here and deleting src-gen probably just masks it instead of solving it.

I was trying to reproduce it but currently I had no luck; from my conversation with Prof. Lee and https://github.com/lf-lang/reactor-c/issues/121 I think branch checkout was done and some major changes on both repos (lf and reactor-c) might be expected; worst case (I suspect) in different branches the generated C file is incompatible with reactor-c; my current plan is `git-bisect` to reproduce it and try to `diff` what’s in `src-gen`

**Comment by cmnrd** [comment]
Actually I stand corrected. I did observe the same problems today while working on reactor-cpp and tracked it down. It turns out that the method `FileUtil.copyInputStream()` was broken if the `skipIfUnchanged` option was set. I assume that @petervdonovan also set this flag to true in his refactoring of the C build process. I am not 100% sure if it really is the same issue, but chances are high that #1490 also fixes the problems in C.

I found these steps to reproduce the problem in the C++ target. It likely also applies to C:
1. Build an lf program using lfc.
2. Modify one file in `org.lflang/src/lib/cpp/reacor-cpp`.
3. Rebuild lfc
4. Build the same lf pogram again without cleaning. The file that was modified in 2. will now be empty in the src-gen directory.

**Comment by edwardalee** [comment]
This bug is not fixed. In fact, it seems to have gotten worse. I no longer need to make any modifications in the source code.  All I need to do is compile an LF file, which compiles successfully, and then change the target properties to add
```
target C {
   logging: DEBUG
}
```
Then recompiling fails. E.g.:
```
$ lfc src/DelayArrayWithAfter.lf 
Generating code for: file:/Users/eal/lingua-franca-master/git/lingua-franca/test/C/src/DelayArrayWithAfter.lf
...
[ 80%] Building C object core/CMakeFiles/core.dir/reactor_common.c.o
/Users/eal/lingua-franca-master/git/lingua-franca/test/C/src-gen/DelayArrayWithAfter/core/tag.c:201:38: error: expected ')'
    LF_PRINT_DEBUG("Physical time: " PRINTF_TIME
                                     ^
/Users/eal/lingua-franca-master/git/lingua-franca/test/C/src-gen/DelayArrayWithAfter/core/tag.c:201:5: note: to match this '('
    LF_PRINT_DEBUG("Physical time: " PRINTF_TIME
    ^
/Users/eal/lingua-franca-master/git/lingua-franca/test/C/src-gen/DelayArrayWithAfter/core/../include/core/utils/util.h:210:35: note: expanded from macro 'LF_PRINT_DEBUG'
                    lf_print_debug(format, ##__VA_ARGS__); \
                                  ^
/Users/eal/lingua-franca-master/git/lingua-franca/test/C/src-gen/DelayArrayWithAfter/core/tag.c:229:20: error: unknown type name '_lf_time_type'
instant_t _lf_time(_lf_time_type type) {
                   ^
/Users/eal/lingua-franca-master/git/lingua-franca/test/C/src-gen/DelayArrayWithAfter/core/utils/util.c:79:3: error: expected function body after function declarator
) ATTRIBUTE_FORMAT_PRINTF(3, 0);
  ^
1 error generated.
/Users/eal/lingua-franca-master/git/lingua-franca/test/C/src-gen/DelayArrayWithAfter/core/tag.c:251:21: error: use of undeclared identifier 'LF_LOGICAL'
    return _lf_time(LF_LOGICAL);
                    ^

... and many more
```

**Comment by cmnrd** [comment]
I cannot reproduce this. Changing the logging property and recompiling without cleaning works fine for me.

**Comment by edwardalee** [comment]
It's perfectly reproducible for me. Are you working in master?

**Comment by petervdonovan** [comment]
I also failed to reproduce. I
1. ran `git pull` while in the `master` branch
2. ran `build-lfc -c`, 
3. `cd`'d into `test/C`
4. deleted `src-gen` and `fed-gen`
5. ran `lfc src/DelayArrayWithAfter.lf` to successfully compile `DelayArrayWithAfter.lf`
6. inserted the line `logging: DEBUG` into `DelayArrayWithAfter.lf`
7. ran `lfc src/DelayArrayWithAfter.lf` to successfully compile `DelayArrayWithAfter.lf` a second time
8. double-checked that I was on the latest `master` by again running `git pull origin master`
9. double-checked that my submodules were up to date (they were)
10. ran `bin/DelayArrayWithAfter` to check that it had indeed been successfully compiled with debug logging

**Comment by cmnrd** [comment]
@edwardalee Do you maybe use a different version of reactor-c? Maybe there is an actual bug in the debug prints in your reactor-c version.

**Comment by cmnrd** [comment]
Since you are likely running on Mac OS, I double checked tried compilation with clang 14, but also this works fine on my end.

**Comment by edwardalee** [comment]
Yes, I'm using a different reactor-c, but if there were an actual bug, the compile would still fail after removing src-gen.  Perhaps to replicate you also have to make a change in the C code in a reaction.  Every time I make such a change, I have to remove src-gen.

**Comment by petervdonovan** [comment]
I could not reproduce after modifying a reaction body, setting `logging: DEBUG`, compiling `DelayArrayWithAfter.lf`, checking out `token-payload-free` in `reactor-c`, modifying `port.c` in `reactor-c`, rebuilding LFC, re-compiling `DelayArrayWithAfter.lf`, modifying a reaction body, re-compiling `DelayArrayWithAfter.lf`, removing the line `logging: DEBUG`, recompiling, adding `logging: DEBUG` back, recompiling, checking out `token-payload-free` in `lingua-franca`, rebuilding LFC, recompiling `DelayArrayWithAfter.lf`, removing `logging: DEBUG`, recompiling, modifying a reaction body and adding `logging: DEBUG` back, recompiling. The issue just does not appear for me.

**Comment by edwardalee** [comment]
Ok, thanks. Let's shelve this for now. Must be some quirk in my setup.

**Comment by cmnrd** [comment]
@edwardalee You are running on MacOS, right? Do we have anyone who could double check if this works on MacOS or not? I could imagine that there are some OS specific and non-obvious quirks in the way we write files.

**Comment by lhstrh** [comment]
Sounds like the same issue reported in https://github.com/lf-lang/lingua-franca/issues/1592

**Comment by cmnrd** [comment]
Yes, it seems to be the same problem. But I don't understand why it only occurs for some users.
