### ISSUE TITLE
Stop unpacking Rust runtime into src-gen

### ISSUE THREAD

**Issue by oowekyala** [lf-lang/lingua-franca#1471]
This is not useful and can actually be harmful. Recently, the benchmark runner also filled nearly 600 GiB of disk space with copies of the runtime, because it's copied for every benchmark program:
![Pasted image 20221114120225](https://user-images.githubusercontent.com/24524930/201664665-feeb5a25-b3f9-46cd-9214-180e875984f2.png)

AFAICT, there is no use to it because Cargo has to download other dependencies from the internet anyway, so it's not like having a local copy allows LFC to run offline. Copies also prevent reusing build artifacts with a cache system like sccache.

**Comment by lhstrh** [comment]
Wow :scream: disk space is cheap, but not that cheap.

**Comment by cmnrd** [comment]
Note that with the benchmark runner, this is mostly because of a (historic) defect in its design. I opened https://github.com/lf-lang/benchmarks-lingua-franca/issues/52.
