### ISSUE TITLE
Javadoc author tags are invalid HTML

### ISSUE THREAD

**Issue by oowekyala** [lf-lang/lingua-franca#1477]
I see everywhere in the codebase these `@author` tags surrounded by braces:
https://github.com/lf-lang/lingua-franca/blob/efcab96605ed068995c3b7d837c6354fa270ed84/org.lflang/src/org/lflang/TargetProperty.java#L58

This is invalid HTML
```
/home/clem/Documents/LF/lingua-franca/org.lflang/src/org/lflang/TargetProperty.java:58: error: malformed HTML
 * @author{Marten Lohstroh <marten@berkeley.edu>}
                           ^
```
 breaks intellij's Javadoc lexer:

![image](https://user-images.githubusercontent.com/24524930/202469384-8773f1d0-9262-4159-a054-3e39902dc2f3.png)

and is rendered improperly:
![image](https://user-images.githubusercontent.com/24524930/202471094-558f0888-30e6-4dea-a7d3-2b70ade0add5.png)

The proper way to write these author tags is without braces, and escaping the <> characters in the email
```java
@author Marten Lohstroh &lt;marten@berkeley.edu&gt;
```
(or using javadoc's `{@literal ...}` taglet, but this is uglier IMO.)

I think we should bulk replace these at some point.

**Comment by axmmisaka** [comment]
I prefer using `{@literal}` as it is native (switch to `&lt;` should be easy, but this looks undoubtedly ugly......)
Alternatively, we just don't let people put email on `@author`; after all, our emails are available at lots of places.....
Please see https://github.com/lf-lang/lingua-franca/tree/axmmisaka/fix-javadoc-author-email

Plus when I run `./gradlew javadoc` I can't seem to find author in generated docs...... interesting

**Comment by lhstrh** [comment]
@axmmisaka: I saw a recent commit somewhere that addresses this, but no corresponding PR?

**Comment by lhstrh** [comment]
BTW, we can also leave out the email addresses...

**Comment by axmmisaka** [comment]
> @axmmisaka: I saw a recent commit somewhere that addresses this, but no corresponding PR?

I made a new branch but not PR because I don't know 1. if this is satisfactory and 2. if we want to do this (instead of just removing all emails)

**Comment by lhstrh** [comment]
Posting the PR is a way to find out :-) You can ask for reviews...

**Comment by lhstrh** [comment]
I brought this up doing our weekly meeting, and it seemed nobody minded it if we just strip the email addresses.

**Comment by axmmisaka** [comment]
Since #1486 was merged long ago I think this can be closed.
