### ISSUE TITLE
ClockSync failures

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/lingua-franca#1512]
Due to unpredictable timing on GitHub Actions, the ClockSync test fails very often. Should we just remove this test?

**Comment by edwardalee** [comment]
Ok with me to remove this test.

**Comment by lhstrh** [comment]
We have similar problems with the federated tests, and I often don't understand why they fail. Here's the most recent example: https://github.com/lf-lang/reactor-c/actions/runs/3752075463/jobs/6373828518
