### ISSUE TITLE
Handle target properties in federations

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/lingua-franca#1560]
If a federated reactor is declared in a file with target properties, what does this mean for federates? My inclination is to have target properties be scoped by the file (this is also how we plan to have multi-target interactions), but this may soon change once we have a package manager and an external declaration of target properties in a project file. Tagging @revol-xut, @cmnrd, @erlingrj, and @arengarajan99.

**Comment by cmnrd** [comment]
I think build properties should be scoped by the project/package with potential refinements for specific sources, which is indeed what we are working on with lingo.

**Comment by lhstrh** [comment]
Just to describe what we do now: we create a configuration based on the target properties found in the main resource, overridden by whatever comes in over the command-line (which, it it is supplied as JSON, could come from `lingo`), and then overridden by whatever target properties might exist in the file in which the class of the federate is located (if this is not the same file as the main resource).

**Comment by cmnrd** [comment]
Shouldn't the command line arguments take precedence over all federates? It seems weird to let cli arguments override properties in the main file, but not for imported files. This can be pretty hard to reason about.

**Comment by lhstrh** [comment]
You are right. Will fix this in #1817.
