### ISSUE TITLE
bank_index parameter is not getting set

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#1567]
The bank_index parameter is no longer being set in a federate that is a member of a bank.
See: https://github.com/lf-lang/examples-lingua-franca/blob/main/C/src/Patterns/FullyConnected_00_Broadcast.lf

The messages printed, "Hello from node 0" should be "Hello from node 1" for federate 1.

**Comment by lhstrh** [comment]
I don't seem to be able to reproduce this. I'm getting this output:
```
---- Start execution at time Sun Mar 19 00:23:25 2023
---- plus 337365528 nanoseconds.
---- Using 4 workers.
Hello from node 3!
Hello from node 0!
Hello from node 2!
Hello from node 1!
Node 1 received messages from 0, 1, 2, 3, 
Node 2 received messages from Node 0 received messages from 0, 1, 2, 3, 
Node 3 received messages from 0, 1, 2, 3, 
0, 1, 2, 3, 
---- Elapsed logical time (in nsec): 0
---- Elapsed physical time (in nsec): 677,615
```

**Comment by edwardalee** [comment]
Looks like this has been fixed.
