### ISSUE TITLE
Icon annotation gives validation errors

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#1569]
If you create the following LF file:
```
target C
@icon("Variables.png")
reactor Variables {}
```
and then compile it with `lfc`, you get:
```
1 | target C
2 | @icon("Variables.png")
  |       ^^^^^^^^^^^^^^^ File extension 'png"' is not supported. Provide any of: ico, png, jpeg, gif, bmp
```
Note that the trailing quotation mark is included. I tried to fix this, but it just led to another error in the same validation code.

**Comment by lhstrh** [comment]
I vaguely recall this feature was quietly removed due to a refactoring. Perhaps @a-sr knows more...

**Comment by cmnrd** [comment]
afaik the icon feature does not work at the moment. Nonetheless, the issue here is an actual bug in the validator.

**Comment by a-sr** [comment]
Icons work but only in Eclipse and not in VSCode (https://github.com/kieler/KLighD/issues/146) and they will stop working as soon as #1482 is merged. I will reactivate then when the required feature is implemented in Klighd.
