### ISSUE TITLE
Building TypeScript files is slow

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/lingua-franca#1610]
Most of the time is wasted during installation `(p)npm install`. It is unclear why it takes so long (`npm install` in `reactor-ts` is not slow). What dependencies are causing the long wait?

**Comment by axmmisaka** [comment]
I tried some TS examples on Ubuntu in https://github.com/lf-lang/examples-lingua-franca and the `npm install` time is, imo, reasonable (given that `npm install` works like the video below I wouldn't say it's too slow); I did saw TS CICD is still running on MACos when Windows/Ubuntu finished running; are there any examples that are particularly worrying?

Uploading 348be066-f46a-11e8-8038-0a580a4b2d84.mp4…

**Comment by lhstrh** [comment]
Interestingly, something funny happens to `jest` with these changes...

**Comment by axmmisaka** [comment]
Speaking of that change, do you think building CICD to auto update `packages.json` would be a good idea?

**Comment by lhstrh** [comment]
Also, see https://github.com/lf-lang/lingua-franca/pull/1611.

**Comment by lhstrh** [comment]
> Speaking of that change, do you think building CICD to auto update `packages.json` would be a good idea?

Do you mean a bot to suggest dependency updates?

**Comment by lhstrh** [comment]
It occurs to me that most of the installation overhead is due to `babel`. We started using `babel` because `tsc` had performance issues and it was considered good practice to only run the type checker when really needed. There were also a few nice-to-have experimental language extensions that were only available through babel at the time. We should probably re-evaluate this choice and revert back using `tsc` to output our `.js` files. @axmmisaka is this something you'd be willing to look into?

**Comment by axmmisaka** [comment]
> > Speaking of that change, do you think building CICD to auto update `packages.json` would be a good idea?
> 
> Do you mean a bot to suggest dependency updates?

Yes, like a…… Dependabot



> It occurs to me that most of the installation overhead is due to `babel`. We started using `babel` because `tsc` had performance issues and it was considered good practice to only run the type checker when really needed. There were also a few nice-to-have experimental language extensions that were only available through babel at the time. We should probably re-evaluate this choice and revert back using `tsc` to output our `.js` files. @axmmisaka is this something you'd be willing to look into?

If `babel` installation is slow it might be because of cache, but I think `tsc` works better for a research project (iirc `babel`‘S advantages are mostly considered front-end facing); that said, considering the reason we included ts, using `ts-node` might be a better idea

I definitely want to look into this (babel to tsc), although I fear most of this change will be related to conversation between contributors (to switch or not to switch) and the actual switching will not cause much issue

**Comment by lhstrh** [comment]
I guess one reason not to rely on ts-node is that it would make it more difficult for users to write something they can readily publish on npm.
