### ISSUE TITLE
Test the arguments of all our command line tools

### ISSUE THREAD

**Issue by cmnrd** [lf-lang/lingua-franca#1641]
The bug fixed in https://github.com/lf-lang/lingua-franca/pull/1631 showed that our current CLI tests are merely smoke tests and not sufficient to detect if arguments are passed properly and have the intended effect. We should add thorough tests for all command line arguments.

**Comment by patilatharva** [comment]
Would it be possible to run a select few unit tests from `org.lflang.tests` using the existing `CliToolTestFixture`? Or do you think we should just write new tests specifically for the CLI?

**Comment by cmnrd** [comment]
I think so, yes. When writing the issue, I forgot that @oowekyala already made a start at this.  I think it only makes sense to build on this and add tests for all the command line arguments. Most important is, that the tests indeed verify the outcome of the argument.
