### ISSUE TITLE
Federated programs all deadlock in master

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#1646]
I just pulled master, and none of the federated programs work anymore.  They all deadlock.  Any idea what recent change to master would cause this?

Unfortunately merged master into the branch I'm working with, tracing-federates, which means I'm dead in the water.

**Comment by edwardalee** [comment]
Maybe hold off on this. May be a configuration error on my part.

**Comment by edwardalee** [comment]
OK, looks like master is not using reactor-c/main. It is using some other branch, where the only substantive difference is that that other branch has the following line in core/CMakeLists.txt:
```
define(EXECUTABLE_PREAMBLE)
```
Tagging @petervdonovan .  Why does omitting this line cause all federated programs to deadlock?  Can we fix this so master works with reactor-c/main?

**Comment by petervdonovan** [comment]
I apologize for letting `lingua-franca/master` get out of sync with `reactor-c/main`. `define(EXECUTABLE_PREAMBLE)` will be in `main` ASAP.

**Comment by lhstrh** [comment]
Can this be closed?

**Comment by petervdonovan** [comment]
Yes if we merge https://github.com/lf-lang/reactor-c/pull/179, which is passing its tests

**Comment by petervdonovan** [comment]
Okay, I just went ahead and merged reactor-c#179. It was just a couple lines of change, and it was closely tied to another PR in this repo that is already merged.
