### ISSUE TITLE
Produce an error message if 'extends' is used in a target that does not support it

### ISSUE THREAD

**Issue by cmnrd** [lf-lang/lingua-franca#1652]
AFAIK, the inheritance mechanism is only supported by the C target (and probably the Python target). However, using the `extends` keyword in another target does not produce an error message. We should add a simple validator rule that produces a useful error for all targets that do not explicitly support inheritance.

**Comment by lhstrh** [comment]
Hi @yugborana, thanks for offering help! The proper place to put this check would probably be [Target.java](https://github.com/lf-lang/lingua-franca/blob/master/org.lflang/src/org/lflang/Target.java) (for targets to report whether they support inheritance) and [this method](https://github.com/lf-lang/lingua-franca/blob/4c4b4119b41590876abad97f4a0bb0d9cb1751d9/org.lflang/src/org/lflang/validation/LFValidator.java#LL831C67-L831C67).

**Comment by yugborana** [comment]
ok but I am not well versed with inheritance mechanism.  May be I could help if you could add specifically there? Sorry for disturbance, I am a beginner in this

**Comment by lhstrh** [comment]
The point here is not to work on the inheritance mechanism itself, but to throw produce an error message in the validator when the `extends` keyword is being used while the target does not support inheritance. If you are interested in implementing support for inheritance in the targets that currently do not support it, that would be welcomed as well, but that would be another issue.

**Comment by yugborana** [comment]
ok I think I will not be able to contribute in this issue
