### ISSUE TITLE
I can't use epoch generated the target code in windows system

### ISSUE THREAD

**Issue by zhuyipeng** [lf-lang/lingua-franca#1658]
`Specify --help for usage, or press the help button on the CMake GUI.
ERROR: CMake Error: The source directory "D:/UserData/z003n71c/workspace/epoch_workspace/CompositeRobot/src-gen/Main" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
ERROR: D:\UserData\z003n71c\workspace\epoch_workspace\CompositeRobot\src\Main.lf line 1
Error in imported file: D:\UserData\z003n71c\workspace\epoch_workspace\CompositeRobot\src\Main.lf
Compiled binary is in D:\UserData\z003n71c\workspace\epoch_workspace\CompositeRobot\bin
Generating code for: platform:/resource/CompositeRobot/src/Main.lf
******** mode: EPOCH
******** generated sources: D:\UserData\z003n71c\workspace\epoch_workspace\CompositeRobot\src-gen\Main
Cleaning D:\UserData\z003n71c\workspace\epoch_workspace\CompositeRobot\src-gen\Main\build
--- Current working directory: D:\UserData\z003n71c\workspace\epoch_workspace\CompositeRobot\src-gen\Main\build
--- Executing command: bash --login -c "cmake -DLF_REACTION_GRAPH_BREADTH=3 -DLF_THREADED=1 -DNUMBER_OF_WORKERS=0 -DSCHEDULER=GEDF_NP -DLOG_LEVEL=2 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=D:/UserData/z003n71c/workspace/epoch_workspace/CompositeRobot -DCMAKE_INSTALL_BINDIR=bin D:/UserData/z003n71c/workspace/epoch_workspace/CompositeRobot/src-gen/Main -DCMAKE_SYSTEM_VERSION="10.0""
CMake Error: The source directory "D:/UserData/z003n71c/workspace/epoch_workspace/CompositeRobot/src-gen/Main" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
ERROR: CMake Error: The source directory "D:/UserData/z003n71c/workspace/epoch_workspace/CompositeRobot/src-gen/Main" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
ERROR: D:\UserData\z003n71c\workspace\epoch_workspace\CompositeRobot\src\Main.lf line 1
Error in imported file: D:\UserData\z003n71c\workspace\epoch_workspace\CompositeRobot\src\Main.lf
Compiled binary is in D:\UserData\z003n71c\workspace\epoch_workspace\CompositeRobot\bin
`

**Comment by edwardalee** [comment]
How to reproduce this?

**Comment by lhstrh** [comment]
We unfortunately can't use this bug report without any instructions for reproducing the problem.
