### ISSUE TITLE
Support Generics for C-Target

### ISSUE THREAD

**Issue by mkhubaibumer** [lf-lang/lingua-franca#1671]
LF Reactor grammar is not bound by Target Language Grammar. We should be able to support Generics even in C-Target for Lingua Franca

- [x] Attach the type argument information to an object that is used in the CGenerator (`ReactorInstance`?) (see `c-templates`)
- [x] Run the C reactor code generation process (`generateReactorClass` etc.) not on reactor classes, but on reactor classes paired with specific combinations of type parameters. (In `c-templates`, these are `TypeParameterizedReactor`s).
- [ ] Mangle all non-static names according to type parameters. To do this it is necessary to pass around the type parameters and pass them to the functions that generate the names.
- [ ] Get the C tests to pass

**Comment by petervdonovan** [comment]
Edited the description at the top with some action items. I already got started on the first three items. I anticipate that only the last item should take a long time to accomplish.
