### ISSUE TITLE
Library files no longer work in federated execution

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#1685]
The following used to work before the fed-gen branch was merged and no longer works:
```
target C {
    files: "/lib/c/reactor-c/util/sensor_simulator.h",
    timeout: 1s
}
reactor Foo {
    reaction(startup) {=
        lf_print("Hello World");
    =}
}
federated reactor {
    f = new Foo()
}
```
The `sensor_simulator.h` file is not found.

**Comment by lhstrh** [comment]
We used to copy the runtime on a per-file basis, but stopped doing this soon as we relied more on CMake. We now copy all the files and then let CMake sort out which files to actually compile, so this `files` directive seems redundant to me. That said, we probably have to add a `cmake-include` property that references `util/sensor_simulator.h`. 

In the examples repo, I see this line occur a few times:
```
Rhythm/SensorSimulator.lf
9:        "/lib/c/reactor-c/util/sensor_simulator.h",

Rhythm/RhythmDistributed.lf
35:        "/lib/c/reactor-c/util/sensor_simulator.c", "/lib/c/reactor-c/util/sensor_simulator.h",

Rhythm/Rhythm.lf
33:        "/lib/c/reactor-c/util/sensor_simulator.h",

experimental/Safety/Cutter.lf
6:        "/lib/c/reactor-c/util/sensor_simulator.h"
```
Let me try to get one of these examples to work...

**Comment by lhstrh** [comment]
Update: it looks like we don't copy the `util` directory. These examples have heaps of other errors though. I'll look into why the `files` property isn't handled as expected for federated programs...

**Comment by lhstrh** [comment]
I've taken a look at the implementation of `copyUserFiles` (which only has an implementation in `CGenerator` and is empty for all other code generators) and `CUtil.copyFileOrResource`. Clearly, the file `/lib/c/reactor-c/util/sensor_simulator.h` is intended to be retrieved from the class path, but the code that is supposed to handle this does so with an entirely different path: `/home/marten/lf-lang/examples-lingua-franca/C/fed-gen/Cutter/src-gen/eStop/sensor_simulator.h`, which makes no sense.

**Comment by lhstrh** [comment]
Working on a fix.
