### ISSUE TITLE
Type checking on ganged connections is incorrect

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#1692]
The following simple test case reports mismatched types, which is incorrect:
```
target C
reactor A {
    output request:int
    input response:float
}

reactor B {
    input request:int
    output response:float
}

main reactor {
    c1 = new A();
    c2 = new A();
    m1 = new B();
    m2 = new B();
    
    c1.request, m1.response -> m1.request, c1.response
    c2.request, m2.response -> m2.request, c2.response
}
```

**Comment by cmnrd** [comment]
I still think that the entire type checking for the C target is incorrect. It is merely based on comparing strings of type names. Mismatching strings, however, do not indicate mismatching types in C. A type can have many aliases. Even worse: matching strings do not indicate that two things are of the same type either. For instance we could have two reactors that use a `#undef` and `#define` to set the same macro to different types in the preambles of different reactors that are later connected.

So should we really try to do the job of the target compiler here? Or should the solution rather be to eliminate this naive type checking?

**Comment by cmnrd** [comment]
I am also wondering if it should be considered legal to mix ports of different types in the same connection statement. The C++ target assumes that all ports in the same connection statement have the same type. Consequently, the presented example also fails to compile for C++. In the C++ target, the connection operator is fully implemented at runtime and it works by creating two lists of port references, one each for the left hand side ports and right hand side ports, that it then connects. For this we need to know the precise types of the ports, and there is no simple way to do this if each port can have a different type.

**Comment by edwardalee** [comment]
I would be OK with eliminating the type checking (or converting it to warning) and letting the compiler do its thing.

**Comment by edwardalee** [comment]
Based on the discussion, I think this falls into the category of "won't fix".

**Comment by lhstrh** [comment]
Are you sure? I thought the action item was to turn errors into warnings?
