### ISSUE TITLE
Stop using `xtext-gradle-plugin`

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/lingua-franca#1693]
It is no longer maintained and we should switch to [org.xtext.builder](https://plugins.gradle.org/plugin/org.xtext.builder). Also see 53fcbd718837235dc60ca48a8a67aced5965c284.

**Comment by lhstrh** [comment]
@a-sr, is this the right take away?

**Comment by a-sr** [comment]
Sounds right to me.
And if it works I don't see a problem.

**Comment by cmnrd** [comment]
I don't think this works. As far as I understand, the [org.xtext.builder](https://plugins.gradle.org/plugin/org.xtext.builder) plugin is meant for users of an xtext DSL. So they can generate code from their DSL calling the xtext-based compiler of that DSL. Apparently, this plugin does not support generating java code from the xtext grammar.

**Comment by cmnrd** [comment]
Probably. I tried it ant it actually didn't do anything... it didn't even complain when using a non-existing language. I am closing this, as I think the current setup is fine and we also don't rely on an outdated xtext plugin (as far as I can tell), we use a custom task instead.
