### ISSUE TITLE
Correspondence tag appears in error message

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#1701]
The following minimal program:
```
target C
main reactor {
    reaction(startup){=
        lf_set(out)
    =}
}
```
generates the following error message from `lfc`:
```
/Users/eal/lingua-franca-intellij/test/C/src/Bug.lf:4:160: error: too few arguments provided to function-like macro invocation
    /*Correspondence: Range: [(3, 8), (3, 19)) -> Range: [(0, 0), (0, 11)) (verbatim=true; src=/Users/eal/lingua-franca-intellij/test/C/src/Bug.lf)*/lf_set(out)
                                                                                                                                                               ^
```
It used to be, I think, that the leading "Correspondence" comment was used to construct a more accurate error report, like this:
```
- error: use of undeclared identifier 'lf_set'
    lf_set(out)
      ^
```
In fact, that is what my version of Epoch generates (which is not up to date with master), so this mechanism has been recently broken.

**Comment by petervdonovan** [comment]
"too few arguments provided to function-like macro invocation" seems like a pretty accurate error report to me.

It is bad that the `Correspondence` tag appears in the error message, however, because it is supposed to have been removed from the generated code. We never did use these tags for error reporting in the C target.

**Comment by lhstrh** [comment]
It’s not inaccurate, but it would be better to treat this kind of error
specially because it has to do with incomplete LF code (missing elements
from the reaction signature).

**Comment by edwardalee** [comment]
No, I think the error message is fine.  The issue I'm raising is about how is presented.  It has the temporary tracking comments in it.
