### ISSUE TITLE
Preamble scoping issues

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#1704]
Recent changes (bodiless reactions?) have caused some things that used to work with preambles to no longer work.

## First
The functions in scope for preambles is no longer the same as for reactions.
Minimal example:
```
target C
preamble {=
    void test(void) {
        lf_print("Hello World");
    }
=}
main reactor {
    reaction(startup) {=
        test();
        lf_print("Works fine here.");
    =}
}
```
The first `lf_print` give a compile error `implicit declaration of function` followed by `conflicting types for 'lf_print'`. The second `lf_print` works fine.

## Second

Local preambles are not visible in the reactor.
Minimal example:
```
target C
main reactor {
    preamble {=
        typedef int foo;
    =}
    state x:foo = 0
    reaction(startup) {=
        lf_print("State is %d", self->x);
    =}
}
```
This gives the following compile error:
```
error: unknown type name 'foo'
foo x;
^
In file included from /Users/eal/lingua-franca-intellij/test/C/src-gen/Bug/bug197855654_main.c:4:
/Users/eal/lingua-franca-intellij/test/C/src/Bug.lf:6:5: error: unknown type name 'foo'
    foo x;
    ^
```

**Comment by petervdonovan** [comment]
This seems related to #1705 and I think the solution will be the same.

**Comment by edwardalee** [comment]
I have issued [PR 137](https://github.com/lf-lang/lf-lang.github.io/pull/137) on the website repository that documents the new behavior.  It is certainly more restrictive than the previous design, but once I understood it, I really agree that this is the right way to go. Nice job!
