### ISSUE TITLE
include directory copied into src tree

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#1709]
If I create a clean directory `X` with a subdirectory `src` containing any simple LF program `Hello.lf` and, in directory `X`, run:
```
lfc src/Hello.lf
```
then the directory `X` acquires a new directory called `include` that duplicates the contents of the directory `src-gen/Hello/include`.

Is this deliberate? What is the use case for this directory?  How and where should we document this?

**Comment by petervdonovan** [comment]
The use case is that the user can include these header files and use them in their C code. For example, a reaction may call a library function that needs to read from a port, or that needs to access the state variables of the self struct. It is possible to imagine that this could make it easier to work around our semantics, but it is something that we have discussed and, I think, agreed might have some valid use cases.

**Comment by edwardalee** [comment]
Ah, ok, that makes sense.  It will need to documented, but I guess that will be part of documenting the bodiless reactions.
