### ISSUE TITLE
Segmentation fault error during federated execution caused by multiport

### ISSUE THREAD

**Issue by jackykwok2024** [lf-lang/lingua-franca#1717]
```
target Python;

reactor ClientReactor {
    input global_parameter
    output updated_parameters
    
    reaction(startup) {=
        global_parameter = 0
     =}
     
     reaction(global_parameter) -> updated_parameters {=
        print(global_parameter.value)
        global_temp = global_parameter.value + 1
        updated_parameters.set(global_temp)
    =}
}

reactor ServerReactor{
    output global_parameter
    input[2] updated_parameters  
    
    reaction(startup) -> global_parameter{=
        global_temp = 0
        global_parameter.set(global_temp)
    =}
    
    reaction(updated_parameters) -> global_parameter{=
        global_temp = updated_parameters[0].value + updated_parameters[1].value
        print(global_temp)
        global_parameter.set(global_temp)
    =}
}

federated reactor{
    clients = new [2]ClientReactor()
    Server = new ServerReactor()
    (Server.global_parameter)+ -> clients.global_parameter after 0
    clients.updated_parameters -> Server.updated_parameters 
}
```

![image](https://user-images.githubusercontent.com/77720778/234999827-b3c8cf59-da56-4f9d-973a-59064ab0d222.png)

**Description:** I encountered a segmentation fault when executing the provided code in a federated setting. However, the same code works without any issues when running in an unfederated setting. The error appears to be caused by the use of multiport for federated execution.

**ClientReactors Output**
startup reaction of both clients seems to be fine:
![image](https://user-images.githubusercontent.com/77720778/235621925-a656b884-3b7f-4432-bad3-d994b986290f.png)
![image](https://user-images.githubusercontent.com/77720778/235622013-d5c6c1b0-39c8-4c0c-aacd-ba520afd2910.png)

**ServerReactor Ouput**
![image](https://user-images.githubusercontent.com/77720778/235621712-892666b1-5ad4-4176-beac-37189cae60a6.png)

**The problems seems to be caused by the convert_C_port_to_py function**
![image](https://user-images.githubusercontent.com/77720778/235622252-56fe5b4e-2a10-4539-a2f3-ca85dc524737.png)

**Comment by lhstrh** [comment]
Suggested fix in https://github.com/lf-lang/lf-python-support/pull/25 but needs to be applied to reactor-c because the files moved. Tagging @petervdonovan.

**Comment by petervdonovan** [comment]
Resolved by https://github.com/lf-lang/reactor-c/pull/218
