### ISSUE TITLE
Add support for `files` target property to other targets

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/lingua-franca#1722]
Currently, the `files` target property is only supported by the C target, but the new implementation as per #1700 should work for any code generator that extends `GeneratorBase`. Optimistically, only a check in the validator needs to be changed. C versions of the relevant test files, which should be added for the other targets, can be found in `test/C/src/target/`.

**Comment by cmnrd** [comment]
What exactly is the new behavior of the `files` property? In the past, it only copied files from src to src-gen. Is this still the case? So far, I have not seen a compelling use-case for why this copying is actually needed. Therefore, the property is not supported at the moment in the C++ target, and I still don't see what it would add.

**Comment by lhstrh** [comment]
Yes, copying is still all it does.

**Comment by cmnrd** [comment]
In that case, I don't see the need to support the files property in the other targets. In the C++ target, additional files are simply resolved relative to the src directory and hence no copying is needed. Also in the remaining targets I haven't seen the need to copy files over.

**Comment by lhstrh** [comment]
Won't fix.
