### ISSUE TITLE
[C-Generics] [Validator] Typename missmatch

### ISSUE THREAD

**Issue by mkhubaibumer** [lf-lang/lingua-franca#1770]
With the recent changes for C-Generics branch which is now in master. There's a big issue in Validator

The Validator is simply text matching the Generic TypeName and isn't allowing us to compile the code at all

So if i have something like this

```
reactor A<T1> {
  input in:T1;
}

reactor B<T2> {
  output out:T2;

  timer t(0, 1sec);
  reaction(t) -> out {=
    lf_set(out, rand());
  =}
}


main reactor {
  a = new A<int>();
  b = new B<int>();

  b.out -> a.in;
}
```
![Screenshot 2023-05-23 at 8 34 08 PM](https://github.com/lf-lang/lingua-franca/assets/119607707/5d451eb4-720e-4fb3-a484-74871ef7877a)

**Comment by petervdonovan** [comment]
Okay, no problem. I intended to address this case, but it looked like the approach that I used did not work properly. Will implement a fix and add a test.
