### ISSUE TITLE
Federate waits indefinitely when authentication is turned on for the federate while RTI is not built with authentication option

### ISSUE THREAD

**Issue by Jakio815** [lf-lang/lingua-franca#1777]
CMake's `find_package(OpenSSL REQUIRED)` fails in Mac environment. It can be checked in `test/C/federated/SimpleFederatedAuthenticated.lf`.

When running `./gradlew runlfc`, the code executes the CMake as below after code generation.

```
cmake -DEXECUTABLE_PREAMBLE= -DLF_REACTION_GRAPH_BREADTH=4 -DLF_THREADED=1 -DWORKERS_NEEDED_FOR_FEDERATE=2 -DNUMBER_OF_WORKERS=0 -DNUMBER_OF_FEDERATES=2 -DSCHEDULER=NP -DFEDERATED= -DFEDERATED_CENTRALIZED= -DFEDERATED_AUTHENTICATED= -DLOG_LEVEL=4 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX=/home/jake/project/clean-lf/test/C/fed-gen/SimpleFederatedAuthenticated -DCMAKE_INSTALL_BINDIR=bin -DLF_FILE_SEPARATOR="/" /home/jake/project/clean-lf/test/C/fed-gen/SimpleFederatedAuthenticated/src-gen/federate__fed2
```

However, this fails in Mac environment with this error.

```
CMake Error at /usr/local/Cellar/cmake/3.10.0/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_INCLUDE_DIR)
```

It fails even if OpenSSL is installed, and I checked CMake works when compiling other C code using OpenSSL library.

I am finding the problem, but let me know if there are any ideas.

**Comment by hokeun** [comment]
> Seems there is also a bug in the cmake build because the build succeeds, and the code runs and deadlocks.

@edwardalee I just tried SimpleFederatedAuthenticated.lf on my Mac and realized that I had the same deadlock-like issue on my computers, but I was able to fix that by re-building the RTI with a cmake option, `-DAUTH=ON` and rerunning the test.

Could you please try it again after re-building the RTI with the following command?:
```
mkdir build && cd build
cmake -DAUTH=ON ../
make
sudo make install
```

@Jakio815 I think we should output a proper error message when the RTI is built without the `-DAUTH=ON` option. Maybe we should add code for outputting the error in the RTI. The output message should be like "the RTI should be built with the DAUTH option..."

**Comment by edwardalee** [comment]
Oh, interesting.  I tried this and it worked, but I get the following warnings upon compiling the RTI:
```
/Users/eal/lingua-franca-intellij/org.lflang/src/lib/c/reactor-c/core/federated/RTI/rti_lib.c:1607:5: warning: 'HMAC' is deprecated [-Wdeprecated-declarations]
    HMAC(EVP_sha256(), _RTI.federation_id, federation_id_length, buf_to_check, 1 + fed_id_length + NONCE_LENGTH,
    ^
/usr/local/include/openssl/hmac.h:45:1: note: 'HMAC' has been explicitly marked deprecated here
DEPRECATEDIN_3_0(unsigned char *HMAC(const EVP_MD *evp_md, const void *key,
^
```
Is it possible to get rid of these warnings?

Also, is it possible to error out with a suitable error message rather than just deadlocking?
