### ISSUE TITLE
Problems with KlighD package

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/lingua-franca#1796]
![image](https://github.com/lf-lang/lingua-franca/assets/19938940/919bce6f-4980-4267-8d45-a0801492e83c)

For more information, see https://github.com/lf-lang/lingua-franca/actions/runs/5115682451/jobs/9197178827

**Comment by cmnrd** [comment]
I fixed this on master by falling back to http instead of https. But it is not a real solution of course...

**Comment by a-sr** [comment]
The certificate is valid again. You can switch back to https.

**Comment by cmnrd** [comment]
Great! I switched back to https on master.
