### ISSUE TITLE
Show reaction names in diagrams

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/lingua-franca#1856]
After merging #1853, I suggest that we deprecate the `@label` attribute and instead use the name given in the declaration (if there is one). The code generators can also benefit from this and make the generated code more readable by making use of this.

**Comment by cmnrd** [comment]
The reaction name should also be shown in the diagrams (instead of the current label).

**Comment by cmnrd** [comment]
Since we decided to keep the `@label` attribute (see discussion in https://github.com/lf-lang/lingua-franca/pull/2016), this issue only requires displaying the reaction names in the diagrams in order to be fixed.
