### ISSUE TITLE
Multiple definitions of the ports when using generics in the C target

### ISSUE THREAD

**Issue by erlingrj** [lf-lang/lingua-franca#1860]
This example program falis in the target C compiler:
```
target C;

reactor R<T> {
    input in: T
}

main reactor {
    r1 = new R<int>()
    r2 = new R<int>()
}
```

The problem is that struct representing the input port of the generic `R` is generated twice. I am guessing that the two instances of R, even though using the same template argument, get different TypeParameterizedReactor objects

**Comment by petervdonovan** [comment]
Yep, I'll work on this.
