### ISSUE TITLE
Should STP violation with no handler be a fatal error?

### ISSUE THREAD

**Issue by petervdonovan** [lf-lang/lingua-franca#1875]
Do we want this error to result in an instantaneous crash? Currently, it does not.

```
Federate 1: ERROR: STP violation occurred in a trigger to reaction 1, and there is no handler.
**** Invoking reaction at the wrong tag!
```

Reasons for:
- The current behavior conceals bugs in our integration tests because programs can terminate with zero exit code even though they exhibited nondeterministic behavior that compromises functional correctness.
- The current behavior would similarly conceal severe bugs in production as well.

Reasons against:
- If you want to run a program indefinitely (maybe for months or years) using decentralized coordination using a standard internet connection, then even if it is correctly designed it will occasionally crash due to outliers in network latency. To avoid these crashes, should the programmer have to sprinkle STP violation handlers throughout their program? I am not sure what coding practices would be recommended in order to get such programs to work properly. For example, maybe it is good enough to only use the handlers with reactions that access output ports, i.e., reactions that appear in the top level of a federate, and to never connect child reactors to the outside of the federate without an intermediate reaction that has an STP handler.

Probably we do not need a crystal ball in order to figure out what is the right thing to do right now. If we later decide that fail-fast-by-default is no longer what we want, we can revert back to the current behavior.

**Comment by lhstrh** [comment]
I think that if it doesn't have a handler, it should not let the program crash. The demands on consistency are completely application specific. In our regression tests, we can use handlers to let the program fail.

**Comment by edwardalee** [comment]
I'm ok with not exiting as long as we are sure that decentralized coordination is being used.  An STP violation with centralized coordination is a fatal error that reveals a bug in the RTI-federate protocol.

**Comment by petervdonovan** [comment]
I think that we can close this now that this question has been answered. We already do treat STP violations in centralized coordination as fatal errors, and after following @edwardalee's suggestions in the `remove-unordered-reactions` branch we will no longer have these invalid error messages in our tests.
