### ISSUE TITLE
Unable to build Lingua Franca compiler with Java 20

### ISSUE THREAD

**Issue by Guangyu-Joshua-Feng** [lf-lang/lingua-franca#1886]
I originally set up the build environment for the main branch with Java 20 and gradle 8.2. However, when I tried to run the command “./gradlew build”, it showed that “ERROR AbstractClassMirror - resource is empty: java:/Objects/java.lang.Object” (screenshot below). I tried cleaning the build and rebuilding it but it didn’t help. After quite a bit of debugging effort, I found that it seemed to be an issue related to the Java version. I resolved the issue by having Java fall back to Java 17. 
![Java20](https://github.com/lf-lang/lingua-franca/assets/52182553/6e500e21-f6a0-41ec-9adc-22e8670ca253)

**Comment by lhstrh** [comment]
The version of `gradle` doesn't really matter because we use `gradlew` (which automatically installs the correct version of `gradle` based on the project configuration). We should be able to build with Java 17 _and up_, so 20 _should_ not be a problem. We'll look into it. Thanks for the bug report!

**Comment by MoezBHH** [comment]
Xtext does support 11 and 17 only.
from here: https://github.com/eclipse/xtext/issues/2680

**Comment by lhstrh** [comment]
It should be noted that even though compilation with > Java 17 is problematic due to the limitations of Xtext, running `lfc` with a higher Java version should not be a problem. I will adjust the https://www.lf-lang.org/docs/handbook/developer-setup to state Java 17 as a requirement.
