### ISSUE TITLE
`--json` argument is not properly handled by `lfc`

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/lingua-franca#1909]
Example:
```
lfc --json="{\"src\":\"/home/marten/lf-lang/lingo/sandbox/src/Main.lf\"}"
```
=>
```
lfc: fatal error: Invalid JSON string:
 {src:/home/marten/lf-lang/lingo/sandbox/src/Main.lf}
```

**Comment by lhstrh** [comment]
The problem here is that in a development setup, `lfc` goes through Gradle, which strips all the quotes from the JSON string.

When using `./build/install/lf-cli/bin/lfc` directly, this does not occur.

**Comment by lhstrh** [comment]
The problem is something like [this](https://discuss.gradle.org/t/javaexec-strips-double-quotes-from-property-values-on-windows/15053) but I haven't been able to find a solution to it.

**Comment by lhstrh** [comment]
Actually, we might be better off using stdin instead of CLI arguments to accept JSON data...

**Comment by revol-xut** [comment]
I am confused about this because normally the json also needs to include a `out` and `properties` field.

Should lfc if `out` is not specified drop the files in the current working directory ?

**Comment by lhstrh** [comment]
> I am confused about this because normally the json also needs to include a `out` and `properties` field.
> 
> 
> 
> Should lfc if `out` is not specified drop the files in the current working directory ? 

This is not about the contents of the json, this is about the json itself not being formatted properly. It turns out that Gradle messes with the quotes in the dev version of lfc...

**Comment by axmmisaka** [comment]
for reference: https://discuss.gradle.org/t/javaexec-strips-double-quotes-from-property-values-on-windows/15053
