### ISSUE TITLE
Diagram Synthesis fails wih IllegalArgumentException when enabling "Reactor State Variables"

### ISSUE THREAD

**Issue by cmnrd** [lf-lang/lingua-franca#1930]
Steps to reproduce:
1. Create a program that contains state variables
```
target Cpp

main reactor Example {
    state foo: int = 42
}
```
2. Enable the "Reactor State Variables" option in VS code

**Comment by soerendomroes** [comment]
It seems to be a problem in the model.[
Here](https://github.com/lf-lang/lingua-franca/blob/081351ecd7b6a41d3272852c575d278ab1bd9457/core/src/main/java/org/lflang/ast/FormattingUtil.java#L82) something tries to infer the target of an `InitializerImpl` which is an EObject but not a `Model`.

**Comment by cmnrd** [comment]
Oh, right. This actually looks like a bug in `FormattingUtil`. @petervdonovan could you take a look at this? I assume that the diagram synthesis renders a string from a state variable to print in the diagram, but it fails because it cannot in infer the target.
