### ISSUE TITLE
Reactors cannot have the same name as the LF file.

### ISSUE THREAD

**Issue by erlingrj** [lf-lang/lingua-franca#1945]
I find it a little confusing that I cannot have a file named "MyReactor.lf" with the following contents:
```
target C;
reactor MyReactor {}
main reactor {}
```
It is fine as long as I dont have the main reactor there. But when I introduce it there is a naming conflict:
```
lfc: error: Name conflict with main reactor.
--> src/MyReactor.lf:4:9
  |
3 | 
4 | reactor MyReactor{}
  |         ^^^^^^^^^ Name conflict with main reactor.
  |
5 | 

lfc: fatal error: Aborting due to previous error
```

**Comment by cmnrd** [comment]
This is the current intended behavior. The main reactor has an implicit name, which is equal to the file name.

**Comment by erlingrj** [comment]
What is the reason for introducing that naming constraint though? If I for instance am creating some library reactor. E.g. `AddReactor` in a file called, naturally, `AddReactor.lf`, say I would like to compile a simple test program. It would be natural to just add a main reactor to that file, instantiate an AddReactor and drive its inputs. But for this to work I must rename the reactor or the file. I agree that it makes sense to think of the main reactor as being named the file name. But is this naming constraint really necessary?

**Comment by erlingrj** [comment]
We could e.g. prepend the reactor name with Main or something?

**Comment by cmnrd** [comment]
I don't think the naming constraint is strictly necessary, but it wouldn't be trivial to change it. We currently use the main reactor name as the name for the binary. To implement your proposal, we would need to separate the binary name and the main reactor name. I believe this requires changing all the code generators. Also, we have a quite complex algorithm checking for binary name conflicts within a single `src` directory, which we would probably need to rethink.

**Comment by erlingrj** [comment]
OK, that's fair enough. I will close it, if it turns into a bigger problem we can think about it. Thanks for feedback
