### ISSUE TITLE
Move the C-related tracing utilities to reactor-c

### ISSUE THREAD

**Issue by erlingrj** [lf-lang/lingua-franca#1946]
After the discussion at todays Package meeting we concluded that the tracing utilities should be moved from the `util` directory of `lingua-franca` and into `reactor-c`. We also concluded that copying the executables into `lingua-franca/bin` is not the right place for them. We could use `/usr/local/bin` which is where the RTI is installed.

**Comment by erlingrj** [comment]
The documentation at the website must also be updated

**Comment by cmnrd** [comment]
Completed by https://github.com/lf-lang/lingua-franca/pull/1948, https://github.com/lf-lang/lf-lang.github.io/pull/151 and https://github.com/lf-lang/reactor-c/pull/259.
