### ISSUE TITLE
Cannot use after delay with user-defined types

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#1958]
If you use a typedef to define type and import a file with the type defined in a file-scoped preamble, the type is not made available to the generated delay reactors.  This makes it very difficult (impossible?) to use after delays with user-defined types unless everything is one file.

To reproduce, put the following into a file `GenDelay.lf`:

```
target C

preamble {=
  #ifndef GEN_DELAY
  #define GEN_DELAY
  typedef int message_t;
  #endif
=}

reactor Source {
  output out: message_t
  reaction(startup) -> out {=
    lf_set(out, 42);
  =}
}

reactor Sink {
  input in: message_t
  reaction(in) {=
    lf_print("Received %d at time %lld", in->value, lf_time_logical_elapsed());
  =}
}
```

Then put this into another file, e.g. `GenDelayTest.lf`:

```
target C
import Source, Sink from "GenDelay.lf"

main reactor {
  source = new Source()
  sink = new Sink()
  source.out -> sink.in after 10 ms
}
```

The file fails to compile with this error:

```
llij/test/C/src-gen/GenDelayTest/./include/GenDelayTest/_lf_GenDelay_49429363.h:39:5: error: unknown type name 'message_t'
    message_t value;
    ^
/Users/eal/lingua-franca-intellij/test/C/src-gen/GenDelayTest/./include/GenDelayTest/_lf_GenDelay_49429363.h:55:5: error: unknown type name 'message_t'
    message_t value;
    ^
In file included from /Users/eal/lingua-franca-intellij/test/C/src-gen/GenDelayTest/__lf_gendelay_49429363.c:3:
/Users/eal/lingua-franca-intellij/test/C/src-gen/GenDelayTest/./__lf_gendelay_49429363.h:13:5: error: unknown type name 'message_t'
    message_t value;
```

**Comment by cmnrd** [comment]
I am lacking some understanding about the implementation of C preambles here, but it seems like the C++ implementation could serve as a good template. After all preambles in conjunction with modular code generation have been working and tested for some years now.

> Note that we often get name collisions anyway. I find that usually need to guard everything in a file-level preamble with #ifndef, as I did in this case:

I find this strange. Why not guard the preamble automatically in the code generator? In the C++ target, every public preamble becomes a header file and the include guards are added automatically. There is also no hashing needed, as they can be named uniquely within one program. Making a preamble visible, then means that the corresponding header gets included. This can be done completely automatically.

**Comment by petervdonovan** [comment]
> Why not guard the preamble automatically in the code generator?

As I said, that is what we do. It would be helpful to have a minimal reproduction that shows why our mechanism does not work.

> There is also no hashing needed, as they can be named uniquely within one program.

I'm not sure what this means. The purpose of hashing is to provide a unique name to include guard. Also, hashing is just an implementation detail that the user does not usually need to worry about, so although I'm sure there are other ways to do this, I am not sure what would be wrong with the current approach.

**Comment by petervdonovan** [comment]
> Why not guard the preamble automatically in the code generator?

As I said, that is what we do. It would be helpful to have a minimal reproduction that shows why our mechanism does not work.

> There is also no hashing needed, as they can be named uniquely within one program.

I'm not sure what this means. The purpose of hashing is to provide a unique name to include guard. Also, hashing is just an implementation detail that the user does not usually need to worry about, so although I'm sure there are other ways to do this, I am not sure what would be wrong with the current approach.

**Comment by edwardalee** [comment]
An example that fails to compile without manually guarding the preamble can be found in the leader-election branch of the playground-lingua-franca repo.  The file is examples/C/src/leader-election/NRP_FD.lf.  If you remove the guard in the preamble, then lfc reports this:

```
In file included from /Users/eal/git/playground-lingua-franca/examples/C/src-gen/leader-election/NRP_FD_Partitioning/_nrp_fd_partitioning_main.c:3:
In file included from /Users/eal/git/playground-lingua-franca/examples/C/src-gen/leader-election/NRP_FD_Partitioning/./_nrp_fd_partitioning_main.h:4:
/Users/eal/git/playground-lingua-franca/examples/C/src-gen/leader-election/NRP_FD_Partitioning/./__lf_gendelay_1afb4029.h:7:3: error: redefinition of enumerator 'heartbeat'
  heartbeat,
  ^

etc.
```

Sorry, I don't have a more minimal example.
