### ISSUE TITLE
Require labels

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/lingua-franca#1972]
It takes a long time to sift through all PRs to ensure that they are all properly labeled in order for the release notes to come out right. We should make this a prerequisite for merging instead. We can use this action: https://github.com/marketplace/actions/require-labels

**Comment by cmnrd** [comment]
Independent of whether we want to use the action to require labels, we should make checking labels part of the review and merge process.

**Comment by cmnrd** [comment]
I am not opposing the action ;) I just think the first step should be to have a written down checklist for PRs and a guideline on how to assign labels (including the meaning of each label). Or do we have that somewhere already?
