### ISSUE TITLE
Single line reactions should not be inlined

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#1975]
I'm finding the formatter's insistence on inlining single-line reactions problematic.  It results in two languages being on the same line and it's rather hard to see what is going on.  Consider the following very simple TypeScript example:

```
  reaction(t) -> i.x {= i.x = 42 =}
```

I find this hard to read.  Given that the formatter already inserts quite a few blank lines, this policy does not seem to be justified by reducing the number of lines (or else we should change that policy and not insert blank lines).  Can we change this to allow:

```
  reaction(t) -> i.x {=
    i.x = 42
  =}
```

**Comment by lhstrh** [comment]
I'm fine with either way...
