### ISSUE TITLE
Cannot connect Cpp "array ports" and normal ports in single connection statement

### ISSUE THREAD

**Issue by erlingrj** [lf-lang/lingua-franca#1977]
This program fails:
```
target Cpp;

reactor Source {
    output out: int[1024]
    output other: bool
}


reactor Sink {
    input in: int[1024]
    input other:bool
}

main reactor {
    src = new Source()
    sink = new Sink()

    src.out, src.other -> sink.in, sink.other
}
```
It appears to expect all of the ports involved in the connection to be of `std::array<int,1024>`. Splitting it up into two separate connections works fine

**Comment by edwardalee** [comment]
This is also not allowed in the C target.
The ports all have to have the same type.

**Comment by erlingrj** [comment]
Aha, I was not aware of this limitation. I will close this then
