### ISSUE TITLE
Language server has trouble with generics

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#1978]
It appears that the language server has trouble with generics:

<img width="895" alt="image" src="https://github.com/lf-lang/lingua-franca/assets/8513334/a351abdf-fab3-4f1a-be61-993a1672c8a3">

The code compiles with no problem.

**Comment by lhstrh** [comment]
Which version of the extension are you using?

**Comment by edwardalee** [comment]
The Prerelease version. But when I double checked this, I saw this:

<img width="990" alt="Screen Shot 2023-08-30 at 4 41 03 PM" src="https://github.com/lf-lang/lingua-franca/assets/8513334/edcb909f-43d8-4bbf-87cf-f8aabddad62b">

I clicked on "Reload Required" and the problem went away... ???

Anyway, closing this.
