### ISSUE TITLE
lfc gives no clue how to run TypeScript code

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#1986]
When compiling a TypeScript target program, lfc used to print something like this, as shown [here](https://www.lf-lang.org/docs/handbook/a-first-reactor?target=ts#structure-of-an-lf-project):

```
#####################################
To run the generated program, use:

    node ...path-to-project.../src-gen/Minimal/dist/Minimal.js

#####################################
```

It no longer prints any such thing, leaving the programmer to guess what to do next.

Better yet, it should generate a shell script in `bin`, as the Python target does currently, to invoke the program.

**Comment by hokeun** [comment]
I'm looking into this.

**Comment by lhstrh** [comment]
Great! Let's opt for generating a script in `bin`, like we do with Python. Should be an easy fix.
