### ISSUE TITLE
reactor::Info() vs reactor::log::Info()

### ISSUE THREAD

**Issue by erlingrj** [lf-lang/lingua-franca#2054]
In the [docs](https://www.lf-lang.org/docs/handbook/target-language-details?target=cpp#log-and-debug-information) it says we can use `reactor::Info()` to log data to stdout. However, I am only able to use `reactor::log::Info()`. I have tried adding `#include "reactor-cpp/logging.hh` which didnt help.

Am I missing something or are the docs out-of-date?

**Comment by cmnrd** [comment]
The docs are wrong... Its a bit strange though, because as far as I remember the logging stuff was always in the `ractor::log` namespace.

**Comment by erlingrj** [comment]
I fixed it here: https://github.com/lf-lang/lf-lang.github.io/pull/173/
