### ISSUE TITLE
Spurious warning about deprecated syntax

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#2056]
The Python test [ModalCycleBreaker.lf](https://github.com/lf-lang/lingua-franca/blob/7af2e84953ddfe9cfeea606ddbaf7762f0faf5c1/test/Python/src/modal_models/ModalCycleBreaker.lf#L58) contains the following syntax in the main reactor:

```
  test = new TraceTesting(events_size = 1, trace = (  // keep-format
    0,1,0,
    100000000,1,1,
    100000000,1,2,
    100000000,1,3,
    100000000,1,4,
    200000000,1,6,
    100000000,1,7,
    100000000,1,8,
    100000000,1,9
  ), training = False)
```

This generates the following warning:

```
lfc: warning: This syntax is deprecated in the Python target, use an equal sign instead of parentheses for assignment.
 --> src/modal_models/ModalCycleBreaker.lf:58:52
   |
57 |   modal = new Modal()
58 |   test = new TraceTesting(events_size = 1, trace = (  // keep-format
   |                                                    ^ This syntax is deprecated in the Python target, use an equal sign instead of parentheses for assignment.
   |
59 |     0,1,0,

lfc: info: Code generation finished.
```

However, the syntax is correct and up-to-date.

**Comment by cmnrd** [comment]
> However, the syntax is correct and up-to-date.

The warning is actually correct. We used to interpret `(...)` as a list. And if you check the generated code, it converts the `(...)`expression to a list using Python's `[...]` syntax. We decided to deprecate this syntax as it is largely misleading. In Python, `(...)` denotes a tuple, not a list.

I think we should actually follow up and remove this old syntax rule for good.
