### ISSUE TITLE
Possible flakiness in `DistributedPhysicalActionUpstreamLong`

### ISSUE THREAD

**Issue by petervdonovan** [lf-lang/lingua-franca#2061]
See [this test run](https://pipelinesghubeus2.actions.githubusercontent.com/pWAm7d4bTvSPaPtQpsdHJsH5IyOeQKx8uNmpEVH4ZI9BC4OKKY/_apis/pipelines/1/runs/14354/signedlogcontent/25?urlExpires=2023-10-16T08%3A01%3A57.9291140Z&urlSigningMethod=HMACV1&urlSignature=YrA5JctWRwRMqz3ad0%2BXxFLe3Dfbd6E67PyJRQtyxjc%3D).

Observed in the target properties refactoring. It is unlikely that refactoring target properties would lead to a flaky failure; there have been build issues, but usually those manifest at compile time.

**Comment by lhstrh** [comment]
Does #2140 provide a fix?

**Comment by petervdonovan** [comment]
It seems likely. Let's just reopen this if we find that it recurs after merging #2140.
