### ISSUE TITLE
Problem compiling for zephyr platform

### ISSUE THREAD

**Issue by naichenzhao** [lf-lang/lingua-franca#2064]
I am trying to compile the code for zephyr on  0.5.2-SNAPSHOT and it seems to be looking for a file (CompileDefinitions.txt) that doesn't seem to exist.

``` 
(base) naichenzhao@Naichens-MacBook-Pro application % west lf-build src/Blinky.lf -w "-b nucleo_f446re -p always"
Executing lfc command: `lfc -c -n src/Blinky.lf`
lfc: info: Generating code for: file:/Users/naichenzhao/Desktop/lf-west/application/src/Blinky.lf
lfc: info: Generation mode: STANDALONE
lfc: info: Generating sources into: /Users/naichenzhao/Desktop/lf-west/application/src-gen/Blinky
Cleaning /Users/naichenzhao/Desktop/lf-west/application/bin
Cleaning /Users/naichenzhao/Desktop/lf-west/application/include
lfc: info: Code generation finished.
Traceback (most recent call last):
  File "/Users/naichenzhao/opt/anaconda3/bin/west", line 8, in <module>
    sys.exit(main())
  File "/Users/naichenzhao/opt/anaconda3/lib/python3.9/site-packages/west/app/main.py", line 866, in main
    app.run(argv or sys.argv[1:])
  File "/Users/naichenzhao/opt/anaconda3/lib/python3.9/site-packages/west/app/main.py", line 111, in run
    self.run_command(argv)
  File "/Users/naichenzhao/opt/anaconda3/lib/python3.9/site-packages/west/app/main.py", line 385, in run_command
    self.run_extension(args.command, argv)
  File "/Users/naichenzhao/opt/anaconda3/lib/python3.9/site-packages/west/app/main.py", line 467, in run_extension
    self.cmd.run(args, unknown, self.topdir, manifest=self.manifest,
  File "/Users/naichenzhao/opt/anaconda3/lib/python3.9/site-packages/west/commands.py", line 194, in run
    self.do_run(args, unknown)
  File "/Users/naichenzhao/Desktop/lf-west/scripts/lf_build.py", line 97, in do_run
    with open(f"{srcGenPath}/CompileDefinitions.txt") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'src-gen/Blinky/CompileDefinitions.txt'
(base) naichenzhao@Naichens-MacBook-Pro application % 

```

**Comment by erlingrj** [comment]
Thanks a lot for reporting this @naichenzhao. I had forgotten to update the lf-west-template. Please check out the most recent commit, and the documentation-update here: https://github.com/lf-lang/lf-lang.github.io/pull/174

In short, you should replace your command with:
```
west lfc src/Blinky.lf --build "-b nucleo_f446re -p always"
```

And it should work. Please let me know if you run into other problems.

**Comment by naichenzhao** [comment]
I re-downloaded the nightly version of lfc. Im not sure if its an issue on my end, but it seems I am getting a different error.

<img width="670" alt="Screenshot 2023-10-24 at 2 36 01 PM" src="https://github.com/lf-lang/lingua-franca/assets/49353868/8695f962-b83f-4f01-8a5f-d9fb4d28419b">

**Comment by erlingrj** [comment]
I have changed the layout of `lf-west-template` now. So the example apps should be located in:
`apps/HelloWorld/` and `apps/NrfBlinky`. It looks like you have the old structure? Could you try pulling the latest version of `lf-west-template` and use the newest project layout. The command to run, from the root of the repo would be:
`west lfc apps/HelloWorld/src/HelloWorld.lf --build "-b nucleo_f446re -p always"`

**Comment by erlingrj** [comment]
See [here](https://github.com/lf-lang/lf-lang.github.io/pull/175) for the most up-to-date docs. Please let me know if anything is unclear in them.

**Comment by naichenzhao** [comment]
Yeah, that's my bad. It works now, thank you very much.

**Comment by lhstrh** [comment]
Thanks for the fixes, @erlingrj, and thanks for confirming, @naichenzhao.
