### ISSUE TITLE
Double-freeing of tokens when exposed to frequent aynchronous lf_schedule_int

### ISSUE THREAD

**Issue by erlingrj** [lf-lang/lingua-franca#2081]
I have been trying to debug an elusive bug I found in a federated program which I think is related to race conditions in the token handling. I was not able to exactly reproduce it in an un-federated setting. But I was able to create a very simple program that ends up with double-freeing tokens and sometimes yielding segmentation fault: `SIGSEGV (address boundary error)`. I suspect that this is a symptom of the same underlying problem I am facing with the federated program.

To reproduce:

```
target C {
  timeout: 10 msec
}

reactor WithPhy {
  preamble {=
    #include "platform.h"
    void* ping(void* actionref) {
      for (int i = 0; i<100; i++) {
        lf_schedule_int(actionref, 0, i);
      }
      return NULL;
    }
  =}
  physical action a:int

  reaction(startup) -> a {=
    lf_thread_t thread_id;
    lf_thread_create(&thread_id, ping, a);
  =}

  reaction(a) {= =}
}

main reactor {
  w = new WithPhy()
}
```
 
 This program schedules a 100 physical actions right after one another. Adding sleeps between the schedulings seems to solve the issue. It alternates between working, but throwing a: `WARNING: Token being freed that has already been freed: 0x7f2490000f70` and seg faulting.
 
 This particular warning means that `lf_done_using` is invoked on a token that already has a ref-count of zero.
 
 There are a few token errors which currently are just printed as warnings. I think these should be considered as errors and halt the program and thus any tests with such warnings will fail.

**Comment by erlingrj** [comment]
I found the race condition and have a proposed fix here: https://github.com/lf-lang/lingua-franca/pull/2082

**Comment by erlingrj** [comment]
It solves the federated issue also. This bug might also have caused other federated tests to be flaky. The reason why this is surfacing now is that I recently disabled some throttling algorithm on the sockets. Previously, messages sent between federates where throtteled and spaced out. Sending was blocked until the previous messages was ACK'ed. Now we just send them without waiting for ACK. So we can now have the scenario that the a federate has mulitple messages in his socket that he reads out and schedules one after the other. This triggered the very unlikely thread-ordering that I am reproducing here

**Comment by lhstrh** [comment]
Wow. Amazing detective work! Will have a look at your fix.
