### ISSUE TITLE
Distinct labels flagged as duplicate

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/lingua-franca#2087]
This bug has been found by @lsk567. The following code yields the error `Duplicate AttrParm 'value'`:

```
reactor Source {
  output out: int
  timer t(1 nsec, 10 msec)
  state s: int = 0

  @label(value="Foo")
  reaction(startup) {= lf_print("Starting Source"); =}

  @label(value="Bar")
  reaction(t) -> out {=
    lf_set(out, self->s++);
    lf_print("Inside source reaction_0");
  =}
}
```

AFAIK, this should be equivalent to the following code, which does not yield errors:

```
reactor Source {
  output out: int
  timer t(1 nsec, 10 msec)
  state s: int = 0

  @label("Foo")
  reaction(startup) {= lf_print("Starting Source"); =}

  @label("Bar")
  reaction(t) -> out {=
    lf_set(out, self->s++);
    lf_print("Inside source reaction_0");
  =}
}
```
The problem appears to me that uniqueness checks are done at the level of the `eContainer`, and while the attributes are associated with the syntactic element they precede, which are different, they in the same container. There must be a way to override this behavior but I'm not sure how. Perhaps @a-sr knows?

**Comment by a-sr** [comment]
We already use an adjusted [uniqueness validator for LF](https://github.com/lf-lang/lingua-franca/blob/master/core/src/main/java/org/lflang/validation/LFNamesAreUniqueValidationHelper.java), so this would be the point of entry to fix this. The error is created by `checkDescriptionForDuplicatedName` (from [NamesAreUniqueValidationHelper](https://github.com/eclipse/xtext-core/blob/72785e6e409eb1d07fee1a4f3da53cb248d671b3/org.eclipse.xtext/src/org/eclipse/xtext/validation/NamesAreUniqueValidationHelper.java#L169)), so we need to override this method, but I have to take a closer look at how it works.

**Comment by lhstrh** [comment]
Ah, I was looking at that class but didn't understand which method we needed the override. Thanks!

**Comment by lhstrh** [comment]
The `checkDescriptionForDuplicatedName` is deprecated. Are you sure this is the method to override?

**Comment by a-sr** [comment]
Yes, I checked it with the debugger. Apparently,  the fact that we use a costomized implementation [leads us into the deprecated API](https://github.com/eclipse/xtext-core/blob/72785e6e409eb1d07fee1a4f3da53cb248d671b3/org.eclipse.xtext/src/org/eclipse/xtext/validation/NamesAreUniqueValidationHelper.java#L99-L100) but don't ask me why they implemented it like this.

**Comment by lhstrh** [comment]
The implementation looks a bit opaque to me. Would you know how to fix it?

**Comment by a-sr** [comment]
Not yet, I would have to take a closer look, but I can do that.

**Comment by lhstrh** [comment]
@a-sr, have you been able to find out anything regarding this issue?

**Comment by a-sr** [comment]
It turns out to be a bit more tricky than I thought, but I am on it.

**Comment by a-sr** [comment]
It turned out easier than I thought, see #2147
