### ISSUE TITLE
Duplicate CLI flags: `--trace` and `--tracing`

### ISSUE THREAD

**Issue by petervdonovan** [lf-lang/lingua-franca#2115]
It appears to me that we have two flags to enable tracing, where one is called `--trace` and the other is called `--tracing`. Are both necessary? This is not a big deal, but it probably is easy to fix.

**Comment by lhstrh** [comment]
How so? Looking at the output of `lfc --help`, I only see `--tracing`.

**Comment by petervdonovan** [comment]
You're right. I was using an older version of LFC when I observed this.
