### ISSUE TITLE
YOLOv5 Example - No module named 'cv2'

### ISSUE THREAD

**Issue by vinzbarbuto** [lf-lang/lingua-franca#2127]
Hello,

I've been working on practicing with Lingua France while attempting to execute the Python [YOLOv5 example](https://github.com/lf-lang/playground-lingua-franca/tree/main/examples/Python/src/YOLOv5). I've made sure to install all the required dependencies as suggested, and I've double-checked them. However, when I run the code, I still encounter an error in the terminal: `from cv2 import cv2 ModuleNotFoundError: No module named 'cv2'`.

I'm wondering if I might be missing something in the library import. Could someone please assist me with this? Any help would be greatly appreciated.

Regards,
Vincenzo

**Comment by erlingrj** [comment]
Could this be because you have multiple Python installations and cv2 is not installed for the version Lingua Franca is using?

**Comment by cmnrd** [comment]
See discussion in https://github.com/lf-lang/playground-lingua-franca/issues/91.
