### ISSUE TITLE
Mechanism to collect output from federated programs

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#2129]
In CI, for the federated tests, the stdout is not shown for all federates and the RTI.  It seems that CI randomly picks just one of the federates or the RTI and displays that output only.

This is making it nearly impossible to debug an issue where I'm getting test failures only in MacOS in CI that I cannot reproduce on my Mac.

**Comment by lhstrh** [comment]
We execute a federated program using the launch script. Whether you do this in CI or on your own machine, you'll have trouble collecting output from the individual federates. Either the launch script has to be in charge of this, or there has to be a mechanism to retrieve output from the filesystem after a federation is done executing. Both seem useful, but neither are currently implemented.

**Comment by lhstrh** [comment]
@edwardalee: this has been addressed in #2140, right?

**Comment by edwardalee** [comment]
Yes, #2140 introduced a -l option to the executable script that creates separate log files for each federate.
