### ISSUE TITLE
Watchdogs sometimes fail on program termination

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#2150]
The one and only test for watchdogs is in `test/C/src/concurrent/failing/Watchdog.lf`.  This test sometimes fails in CI for what seems to be a very simple reason: The background watchdog thread that is waiting for the timeout can time out after the program has terminated and has completed at least part of its termination sequence, which includes freeing memory devoted to the event queue. This thread then tries to schedule something on the event queue, resulting in a segmentation fault or worse.

**Comment by lhstrh** [comment]
@edwardalee, has this been resolved, or are there more changes necessary?

**Comment by edwardalee** [comment]
This was resolved by @erlingrj in [PR 341 of reactor-c](https://github.com/lf-lang/reactor-c/pull/341).
