### ISSUE TITLE
Docker support should include orchestration on multiple nodes

### ISSUE THREAD

**Issue by petervdonovan** [lf-lang/lingua-franca#2153]
We discussed this yesterday and seemed to agree that generating Ansible scripts is an appealing possible solution.

As an easy first step, and as an escape hatch in case someone wants to use an orchestration tool that we do not (yet) support, it might be helpful to provide an easy way to run `docker build` or `docker buildx` on all the generated Dockerfiles, and also to output a list of the names of all the resulting images. This way, the resulting images are all available on the user's system, and they can then be used in a mostly non-LF-specific external workflow that works with local Docker images.

**Comment by lhstrh** [comment]
We could just run `docker compose build`. And put `docker compose up` in the generated binary. Would that address this?

**Comment by petervdonovan** [comment]
I am not sure due to my lack of Docker expertise, but judging from the documentation it looks like that might solve this, yes.
