### ISSUE TITLE
Federated compilation with the clean flag does not work correctly

### ISSUE THREAD

**Issue by erlingrj** [lf-lang/lingua-franca#2171]
If I do a clean compile of a federated program ( `lfc -c`) the generated binary from the first federate will be cleaned when this command invokes `lfc` on the second federate and so on.  So the generated bash script will not be successful since it will not find all binaries it needs in `fed-gen/bin`

**Comment by lhstrh** [comment]
This is a known bug and we'll fix it soon. I think there may be a duplicate issue about this already.
