### ISSUE TITLE
Remove the deprecated list syntax

### ISSUE THREAD

**Issue by cmnrd** [lf-lang/lingua-franca#2202]
We decided to deprecate the interpretation of a comma-separated list of expressions enclosed in `(` and `)` as a list, in favor of using the corresponding expressions and syntax rules in the target language. E.g., we would use `{0, 1, 2, 3}` in C/C++ or `[0, 1, 2, 3]` in Python. I think it is time to drop this old rule, also because it may cause confusion (see https://github.com/lf-lang/lingua-franca/issues/2056).

In particular, we would remove this syntax for `AssignmentInitializer` from the grammar:
```
    | '='? parens?='(' (exprs+=Expression (','  exprs+=Expression)* (trailingComma?=',')?)? ')'
```

**Comment by lhstrh** [comment]
Yes, this seems like the right thing to do to me.
