### ISSUE TITLE
Tracing of federates no longer works in master

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#2207]
When I set tracing: true in federated/AfterDelays.lf and then run fedsd, I get complete garbage:

<img width="1197" alt="image" src="https://github.com/lf-lang/lingua-franca/assets/8513334/3f51c730-d30b-4422-bd96-ee420dcf8efd">

**Comment by lhstrh** [comment]
Is this a problem with the captured data or with the processing of it?

**Comment by edwardalee** [comment]
NVM.  I had to rebuild the tracing utilities...
