### ISSUE TITLE
The order in which reaction are defined causes the detection of nonexistent loops

### ISSUE THREAD

**Issue by sbgaia** [lf-lang/lingua-franca#2218]
I have implemented a top-level reactor, `TReactor`, which uses an internal reactor `DDelay`, to delay two updates on its outputs. The code of the two reactors is the following:

- TReactor
```
target Python 

import DDelay from "DDelay.lf"

reactor TReactor{
    input i_a
    input i_b
    output o_a
    output o_b
    dd = new DDelay()

    reaction(i_a) -> dd.i_a{=
    =}
    reaction(i_b) -> dd.i_b{=
    =}
    reaction(dd.o_a) -> o_a{=
    =}
    reaction(dd.o_b) -> o_b{=
    =}
}
```
- DDelay
```
target Python

reactor DDelay{
    input i_a
    input i_b
    output o_a
    output o_b
    logical action d_a
    logical action d_b

    reaction (i_a) -> d_a{=
    =}

    reaction (d_a)-> o_a{=
    =}

    reaction (i_b) -> d_b{=
    =}

    reaction (d_b)-> o_b{=
    =}
}
```

This works without any problem and is rendered correctly in VS Code:
![TReactor](https://github.com/lf-lang/lingua-franca/assets/42733642/5af3c892-4c09-4597-867d-57cf2708f3ea)

If I change the order in which I define the reactions within the reactor `TReactor` LF detects a nonexistent cycle. I have also tried to compile the code manually and the same error is detected. Here is the piece of code causing the error and its rendering in VS Code: 

```
target Python 

import DDelay from "DDelay.lf"

reactor TReactor{
    input i_a
    input i_b
    output o_a
    output o_b
    dd = new DDelay()

    reaction(i_a) -> dd.i_a{=
    =}

    reaction(dd.o_b) -> o_b{=
    =}

    reaction(i_b) -> dd.i_b{=
    =}

    reaction(dd.o_a) -> o_a{=
    =}
}
```
![TReactor_](https://github.com/lf-lang/lingua-franca/assets/42733642/0853f1b6-a8f0-4a80-813f-fa063f6e6043)

**Comment by edwardalee** [comment]
This is a real cycle.  Keep in mind that within any reactor, at any given tag, reactions must execute in the order they are declared.  Suppose that the logical action in DDelay has an event at tag _g_, and input `i_b` has an event at the same tag.  At that tag, 2 has to execute before 3.  2 cannot execute before 4, which has to execute after 3, which has to execute after 2.

**Comment by sbgaia** [comment]
Ok, I think I got that. I thought that since there is a logical event between reactions 3 and 4 within the reactor `DDelay,` the minimum time at which we can schedule an event is by calling schedule(0), which schedules the action at the next tag. 
This looks like defining a delay of time 0 between an input and an output of two reactors (which can be used to solve a cycle problem). Am I confusing the two things?

**Comment by edwardalee** [comment]
I think it's more helpful to think of it this way:  If reactions 3 and 4 within `DDelay` are both enabled at the same tag, which should execute first?  The assumption made in LF is that all reactions in a reactor share state (they all have access to the same state variables), and consequently, it matters which executes first.  If you leave this unspecified, then you get nondeterminism. The solution in LF is 3 will always execute before 4.  This has nothing to do with the logical action between them.

**Comment by sbgaia** [comment]
Ok, I got it. Thanks a lot for your kind explanation!

**Comment by lhstrh** [comment]
The causality loop is caused by the following dependencies:
- `DDelay.3` -> `DDelay.4`
- `TReactor.3` -> `DDelay.3`
- `TReactor.2` -> `TReactor.3`
- `DDelay4` -> `TReactor.2`
You can remove the logical action altogether and you would still have this loop. What you could do to resolve the cycle, is to switch the order of `TReactor.3` and `TReactor.2` or `DDelay.4` and `DDelay.3`. In fact, the compiler should show a message that suggests something along those lines.
