### ISSUE TITLE
Clock-sync: off does not work

### ISSUE THREAD

**Issue by erlingrj** [lf-lang/lingua-franca#2246]
Currently, we cannot disable clock-sync if docker is enabled.

```
target C {
  docker: true,
  clock-sync: off
}
reactor R1 {
  reaction(startup) {=
  =}
}
federated reactor {
  r1 = new R1()
  r2 = new R1()
}
```

Fails to forward the clock sync option to the generated programs in `fed-gen`.

**Comment by lhstrh** [comment]
Nice catch, thanks @erlingrj!

**Comment by lhstrh** [comment]
I noticed that the forwarding of the `clock-sync` property to the generated federates works fine, and yet the generated `CMakeLists.txt` include `set(LF_CLOCK_SYNC 1 CACHE STRING "")`.

**Comment by lhstrh** [comment]
Same effect when `docker: false`

**Comment by petervdonovan** [comment]
> I noticed that the forwarding of the `clock-sync` property to the generated federates works fine, and yet the generated `CMakeLists.txt` include `set(LF_CLOCK_SYNC 1 CACHE STRING "")`. (Result obtained in `pre-build-cmd` branch.)

That appears to be the intended behavior. See Erling's comment in CMakeLists.txt:
> [define(LF_CLOCK_SYNC) # 1 for OFF, 2 for INIT and 3 for ON.](https://github.com/lf-lang/reactor-c/blob/587a8f9498b69bc82f404e432f881d7bb0bcf383/core/CMakeLists.txt#L159)

This makes sense in light of [this](https://github.com/lf-lang/reactor-c/blob/587a8f9498b69bc82f404e432f881d7bb0bcf383/include/core/federated/clock-sync.h#L39-L42):
```c
#define LF_CLOCK_SYNC_OFF 1
#define LF_CLOCK_SYNC_INIT 2
#define LF_CLOCK_SYNC_ON 3
```

And if I go to the runtime and add a `printf` to show the value of `LF_CLOCK_SYNC`, and I run the program that was posted at the top of this issue, I get the following output:
```
[+] Running 3/0
 ✔ Container ClockSyncOff-rti           Created                                                                           0.0s 
 ✔ Container ClockSyncOff-federate__r1  Recreated                                                                         0.1s 
 ✔ Container ClockSyncOff-federate__r2  Recreated                                                                         0.1s 
Attaching to ClockSyncOff-federate__r1, ClockSyncOff-federate__r2, ClockSyncOff-rti
ClockSyncOff-rti           | RTI: Federation ID: 1
ClockSyncOff-federate__r1  | CLOCK_SYNC: 1
ClockSyncOff-federate__r2  | CLOCK_SYNC: 1
```

And even if I add a `printf` in the clock synchronization code to see if it is being executed, I don't see the message in the `printf`, so it looks like the clock synchronization code is indeed NOT being executed.

So I'm not sure how to reproduce the problem that was reported. As far as I can tell, everything is fine. Feel free to re-open this issue if there's something I missed.
