### ISSUE TITLE
Files specified under the files target property should be included in the docker image

### ISSUE THREAD

**Issue by erlingrj** [lf-lang/lingua-franca#2278]
If you specify something with `files: "my_file.txt"`, and also specifies `docker: true` then those files should be included in the resulting docker image. This requires changing the code-generated Dockerfile to copy over those files.

**Comment by lhstrh** [comment]
Confirmed that this now works.

**Comment by lhstrh** [comment]
Actually, I just realized that I might be misinterpreting the issue; there are two stages: build and a run stage. I've confirmed that files are available at the build stage, but not at the run stage... Do files need to be available at the run stage?

**Comment by lhstrh** [comment]
As discussed with @petervdonovan, the solution would be to add `COPY` statements for all entries in the `files` target properties to copy them from the build phase to the run phase.

**Comment by edwardalee** [comment]
Files may be needed at run time. They could be data files (eg audio, AI parameters, etc)

**Comment by lhstrh** [comment]
Yes, we figured: @petervdonovan already created a fix: #2327.
