### ISSUE TITLE
Diagrams won't respond to click when expand/contract was expected

### ISSUE THREAD

**Issue by rcakella** [lf-lang/lingua-franca#2279]
This issue pertains to diagram rendering of LF application in VSCode. If reactor layout is already expanded due to "Expand reactors by default" option, they won't contract on click as expected. Vice-versa has also been observed with reactors not expanding when they were supposed to. 

Environment: OSX, LF 0.7 extension installed with KLighD Diagrams v0.4.2.

**Comment by lhstrh** [comment]
@rcakella: I was able to reproduce this, but after I reloaded the extension (VS Code indicated that it had to), the problem went away. Could you try to reload? If you're unsure how to do this, you can also go to the extension and hit the "Switch to Pre-Release Version" button -- it will prompt you to reload right after.

**Comment by lhstrh** [comment]
@rcakella, @elgeeko1 confirmed that reload fixes the problem. Let me close the issue for now. If it reappears or somehow isn't solved on your end, please reopen.
