### ISSUE TITLE
Compilation of programs for the Pololu 3pi+ 2040 robot broke with the 0.7.0 release

### ISSUE THREAD

**Issue by NiklasRentzCAU** [lf-lang/lingua-franca#2282]
With the newest release of Lingua Franca 0.7.0, the compilation of programs for the Pololu 3pi 2040 robot throws errors and does not compile correctly anymore. I tested one of the programs of the [Embedded Systems Lab](https://www.lf-lang.org/embedded-lab/Sensors.html), specifically the [AccelerometerDisplay.lf](https://github.com/lf-lang/lf-3pi-template/blob/main/src/AccelerometerDisplay.lf) example with both the 0.6.0 and 0.7.0 versions of the VS Code extension and the lfc tool. Both old versions 0.6.0 compile fine, while the 0.7.0 versions show this in the output and the error log (taken from the VS Code extension):

[CMakeError.log](https://github.com/lf-lang/lingua-franca/files/15296141/CMakeError.log)
[CMakeOutput.log](https://github.com/lf-lang/lingua-franca/files/15296142/CMakeOutput.log)

```
Cleaning /home/nre/git/lf-3pi/include
Cleaning /home/nre/git/lf-3pi/src-gen/AccelerometerDisplay/build
--- Current working directory: /home/nre/git/lf-3pi/src-gen/AccelerometerDisplay/build
--- Executing command: cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/home/nre/git/lf-3pi -DCMAKE_INSTALL_BINDIR=bin -DLF_FILE_SEPARATOR="/" -DLF_SOURCE_DIRECTORY="/home/nre/git/lf-3pi/src" -DLF_PACKAGE_DIRECTORY="/home/nre/git/lf-3pi" -DLF_SOURCE_GEN_DIRECTORY="/home/nre/git/lf-3pi/src-gen/AccelerometerDisplay" /home/nre/git/lf-3pi/src-gen/AccelerometerDisplay
-- The C compiler identification is GNU 10.3.1
-- The CXX compiler identification is GNU 10.3.1
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/arm-none-eabi-gcc
-- Detecting C compiler ABI info
Using PICO_SDK_PATH from environment ('/home/nre/git/lf-3pi/pico-sdk')
PICO_SDK_PATH is /home/nre/git/lf-3pi/pico-sdk
Defaulting PICO_PLATFORM to rp2040 since not specified.
Defaulting PICO platform compiler to pico_arm_gcc since not specified.
PICO compiler is pico_arm_gcc
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/arm-none-eabi-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/arm-none-eabi-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Build type is Release
Defaulting PICO target board to pico since not specified.
Using board configuration from /home/nre/git/lf-3pi/pico-sdk/src/boards/include/boards/pico.h
-- Found Python3: /usr/bin/python3.10 (found version "3.10.12") found components: Interpreter 
TinyUSB available at /home/nre/git/lf-3pi/pico-sdk/lib/tinyusb/src/portable/raspberrypi/rp2040; enabling build support for USB.
BTstack available at /home/nre/git/lf-3pi/pico-sdk/lib/btstack
cyw43-driver available at /home/nre/git/lf-3pi/pico-sdk/lib/cyw43-driver
-- Including sources for single-threaded runtime.
-- Including the following sources: tag.c, clock.c, port.c, mixed_radix.c, reactor_common.c, lf_token.c, environment.c, reactor.c, utils/vector.c, utils/pqueue_base.c, utils/pqueue_tag.c, utils/pqueue.c, utils/util.c, utils/hashset/hashset.c, utils/hashset/hashset_itr.c
-- Applying preprocessor definitions to platform...
-- LF_SINGLE_THREADED=1
-- LOG_LEVEL=2
-- NUMBER_OF_WATCHDOGS=0
-- Applying preprocessor definitions...
-- LF_REACTION_GRAPH_BREADTH=3
-- LF_SINGLE_THREADED=1
-- LOG_LEVEL=2
-- NUMBER_OF_WATCHDOGS=0
-- LF_SOURCE_DIRECTORY="/home/nre/git/lf-3pi/src"
-- LF_SOURCE_GEN_DIRECTORY="/home/nre/git/lf-3pi/src-gen/AccelerometerDisplay"
-- LF_PACKAGE_DIRECTORY="/home/nre/git/lf-3pi"
-- LF_FILE_SEPARATOR="/"
-- Configuring incomplete, errors occurred!
See also "/home/nre/git/lf-3pi/src-gen/AccelerometerDisplay/build/CMakeFiles/CMakeOutput.log".
See also "/home/nre/git/lf-3pi/src-gen/AccelerometerDisplay/build/CMakeFiles/CMakeError.log".
Pico W Bluetooth build support available.
lwIP available at /home/nre/git/lf-3pi/pico-sdk/lib/lwip
mbedtls available at /home/nre/git/lf-3pi/pico-sdk/lib/mbedtls
CMake Error at CMakeLists.txt:56 (target_link_libraries):
  Cannot specify link libraries for target "core" which is not built by this
  project.

```

Executing from lfc results in very similar errors.

**Comment by erlingrj** [comment]
Could you see if this PR fixes your problem? https://github.com/lf-lang/lingua-franca/pull/2283

**Comment by NiklasRentzCAU** [comment]
There are still issues after testing a manual build. I have not manually built LF before, so please verify that my build process was correct: I checked out your branch, made sure to update the git submodules via `git submodule update --init --recursive` and built the project with `./gradlew build`. Then I unpacked the snapshot-CLI from the `build/distributions` folder and re-tried the compilation, now with this new error message after the same general configuration messages on the console:

```
-- Configuring incomplete, errors occurred!
See also "/home/nre/git/lf-3pi/src-gen/AccelerometerDisplay/build/CMakeFiles/CMakeOutput.log".
See also "/home/nre/git/lf-3pi/src-gen/AccelerometerDisplay/build/CMakeFiles/CMakeError.log".
TinyUSB available at /home/nre/git/lf-3pi/pico-sdk/lib/tinyusb/src/portable/raspberrypi/rp2040; enabling build support for USB.
BTstack available at /home/nre/git/lf-3pi/pico-sdk/lib/btstack
cyw43-driver available at /home/nre/git/lf-3pi/pico-sdk/lib/cyw43-driver
Pico W Bluetooth build support available.
lwIP available at /home/nre/git/lf-3pi/pico-sdk/lib/lwip
mbedtls available at /home/nre/git/lf-3pi/pico-sdk/lib/mbedtls
CMake Error at robot-lib.txt:2 (target_link_libraries):
  The keyword signature for target_link_libraries has already been used with
  the target "AccelerometerDisplay".  All uses of target_link_libraries with
  a target must be either all-keyword or all-plain.

  The uses of the keyword signature are here:

   * CMakeLists.txt:70 (target_link_libraries)

Call Stack (most recent call first):
  CMakeLists.txt:88 (include)
```

Something in the CMakeLists.txt file still seems to be off, but I have never worked with it to really understand the message.

**Comment by erlingrj** [comment]
Yes, this build process works. An even more convenient way is to just use `bin/lfc-dev`. You can use that in place of `lfc` and what it does is to first call gradle and possibly recompiles itself if there are any changes in the repo.

The CMake error is because in our Cmake system we are now using PUBLIC/PRIVATE keywords when adding compile defs or linking targets. Can you try with this version of the lab: https://github.com/lf-lang/lf-3pi-template/pull/5

**Comment by lhstrh** [comment]
Also getting
```
_rp2040_support.h:10:10: fatal error: pico/stdlib.h: No such file or directory
   10 | #include <pico/stdlib.h>
      |          ^~~~~~~~~~~~~~~

```

**Comment by edwardalee** [comment]
I'm trying to help here, despite finding cmake to be a total mystery, but I ran into other problems. First, I've issued a PR (https://github.com/lf-lang/reactor-c/pull/440) that fixes erroneous CMake syntax.  But this just took me to this problem:
```
$ lfc-dev src/AccelerometerDisplay.lf
lfc: info: Generating code for: file:/Users/edwardlee/git/lf-3pi-template/src/AccelerometerDisplay.lf
...
CMake Error at CMakeLists.txt:51 (target_link_libraries):
  Cannot specify link libraries for target "core" which is not built by this
  project.
```
Suggestions for how to get past this problem?

**Comment by erlingrj** [comment]
I believe this issues should have been addressed by Samules recent merges to `lingua-franca` and `reactor-c`. The fix in your PR, Edward, is not related to the error reported here

**Comment by erlingrj** [comment]
@NiklasRentzCAU could you try out latest version of `lingua-franca` and do `git submodule update`

**Comment by NiklasRentzCAU** [comment]
I updated my master branch and the submodule and built the project as above, now yet another issue shows up during compilation:

```
CMake Error at low_level_platform/impl/CMakeLists.txt:64 (if):
  if given arguments:

    "DEFINED" "NUMBER_OF_WORKERS" "AND" "GREATER" "2"

  Unknown arguments specified
Call Stack (most recent call first):
  core/CMakeLists.txt:90 (include)
```

The related CMakeLists.txt file in src-gen/AccelerometerDisplay/low_level_platform/impl/CMakeLists.txt:64 around that line is generated to look like this:

```
    if (DEFINED NUMBER_OF_WORKERS AND ${NUMBER_OF_WORKERS} GREATER 2)
        message(FATAL_ERROR "RP2040 can have at most 2 workers (one per core).\
            Number of requested workers is ${NUMBER_OF_WORKERS}.")
    endif()
```

I did not add any property related to the number of workers in the C target declaration, only the usual `single-threaded: true` line, if that is related.

**Comment by edwardalee** [comment]
This issue is fixed in https://github.com/lf-lang/reactor-c/pull/440.

**Comment by edwardalee** [comment]
I have issued two more PRs, one in [lingua-franca](https://github.com/lf-lang/lingua-franca/pull/2303) and one in [reactor-c](https://github.com/lf-lang/reactor-c/pull/441).  Together with @erlingrj 's [fix in lf-3pi-template](https://github.com/lf-lang/lf-3pi-template/pull/5/files), I was able to get the AccelerometerDisplay.lf program to compile.

**Comment by lhstrh** [comment]
@edwardalee, you mention https://github.com/lf-lang/lf-3pi-template/pull/5/files but that's a draft PR which doesn't pass the tests. I don't get the full picture here. Could it be that there is a circular dependency in the tests not passing?

**Comment by edwardalee** [comment]
I don't understand CMake well enough to be able to explain this magic, but the code does not compile without the change in  https://github.com/lf-lang/lf-3pi-template/pull/5/files.  I've gone ahead and pushed this change to main and closed the draft PR.  I would not expect the tests to pass because building rp2040 code is broken with changes needed in both [lingua-franca master](https://github.com/lf-lang/lingua-franca/pull/2303) and [reactor-c](https://github.com/lf-lang/reactor-c/pull/441).

**Comment by NiklasRentzCAU** [comment]
@edwardalee Thank you, you fixes also solve all compilation problems on my machine as well. Tomorrow I can test if the compiled program actually executes correctly on the Pololu robots as well, but this looks promising.
