### ISSUE TITLE
Issue regarding target python 

### ISSUE THREAD

**Issue by chauncygu** [lf-lang/lingua-franca#2310]
When I finished generated code and ran Python code with `python /Users/shangding/Documents/mycode/lingua_franca/test_program/src-gen/first_reactor/first_reactor.py`, It happens errors:
`Traceback (most recent call last):
  File "/Users/shangding/Documents/mycode/lingua_franca/test_program/src-gen/first_reactor/first_reactor.py", line 7, in <module>
    from LinguaFrancafirst_reactor import (
SystemError: initialization of LinguaFrancafirst_reactor did not return an extension module` 

The source code within `first_reactor.lf` is as follows:

`target Python

main reactor {
  reaction(startup) {=
    print("Hello World.")
  =}
}`

On my laptop, C can work well, but Python has the above issue.

**Comment by edwardalee** [comment]
This is the same issue as #2298.  We really need to revert the change referenced there.
