### ISSUE TITLE
Rust Test Failing on Master Branch

### ISSUE THREAD

**Issue by Depetrol** [lf-lang/lingua-franca#2376]
The `rs-benchmark-tests` is failing on the master branch. See [rs-benchmark-tests / benchmark-tests](https://github.com/lf-lang/lingua-franca/actions/runs/10015370692/job/27686691993#step:13:2175) in [this](https://github.com/lf-lang/lingua-franca/actions/runs/10015370692) run.

**Comment by cmnrd** [comment]
Fixed via https://github.com/lf-lang/benchmarks-lingua-franca/pull/65
