### ISSUE TITLE
Align the meaning of the 'threads' target property across targets.

### ISSUE THREAD

**Issue by cmnrd** [lf-lang/lingua-franca#290]
Currently we have two targets supporting multi-threaded execution: C and C++. The number of worker threads utilized by the runtime can be configured with the `threads=N` target property. However, `threads=0` has a different meaning in the two targets. In C++, `threads=0` tells the runtime to choose the optimal number of worker threads (currently this is the number of hardware threads in the executing system). In C, `threads=0` is the default and tells the compiler to use the unthreaded runtime. If `threads` is set to one or more, the compiler will use the threaded runtime and utilize the given amount of worker threads.

Since `threads` has a double meaning in C (specifying the number of worker threads and switching between threaded and unthreaded runtime), I think we should introduce a new C-specific target property `multi-threaded` (or `threaded`) to switch between runtimes,  and give `threads` (in particular `threads=0`) the same meaning as in C++. The default would be `multi-threaded=false` and explicitly setting `multi-threaded=true` would enable multi-threaded execution. In case of multi-threaded execution, `threads=N` can further set the number of worker threads to `N`. There should be an additional sanity check ensuring that `multi-threaded=false` and `threads=N` cannot be used in conjunction.

**Comment by oowekyala** [comment]
Is there a use case for using the multi-threaded runtime with a single thread? It looks like you could avoid some complexity if you didn't support this, and used threads=0 for auto-selection, threads=1 for single-threaded, threads=n > 1 for multi-threaded, the selected runtime being an implementation detail.

**Comment by cmnrd** [comment]
I guess that could also be an option. For C, the default would then be `threads=1`, meaning unthreaded runtime. However, I think it is desirable to make the difference between the two C runtimes more explicit. The runtime selection also has some implications that are not so obvious and not just an implementation detail. For instance, the unthreaded C runtime does not support physical actions.

**Comment by oowekyala** [comment]
Ok thanks for explaining!

**Comment by edwardalee** [comment]
A cleaner solution would be that the target property could be:
```
   threads: auto
   threads: 0       // No threads. Unthreaded runtime.
   threads: 1 or more   // Number of threads.
```

**Comment by lhstrh** [comment]
I like @edwardalee's suggestion. That said, perhaps we should use `workers` instead of `threads`?

**Comment by cmnrd** [comment]
I find @edwardalee's suggestion a bit problematic, because it mixes types (string and int). I would prefer to keep the parsing simple, which also helps for processing the `--threads` CLI flag in the generated binary with a standard framework, but I don't feel too strong about this.

> That said, perhaps we should use workers instead of threads?

Could you explain why you prefer `workers`? I am not sure how it works in C, but in C++ the number of threads is equal to the number of workers.

**Comment by lhstrh** [comment]
In C, if `threads=N`, we have one coordinating thread, and `N` workers...

**Comment by cmnrd** [comment]
Ok. In C++ there is no distinction between worker and scheduler (or coordination thread) anymore. All workers are equal and any worker can become the scheduler, which significantly reduces the synchronization required.

I am not sure what to do here. But I think I still prefer `threads`. We could document that there is an additional coordination thread in the C runtime.

Also what worries me a bit about @edwardalee's suggestion is that it makes the distinction between two different implementations of the C runtime and its consequences implicit. I think physical actions are an important language feature and enabling or disabling it should be more explicit than just by selecting the number of threads.

**Comment by edwardalee** [comment]
Note that physical actions without threads make no sense.
They are required to be scheduled from outside any reaction.

Edward

---------
Edward A. Lee
EECS, UC Berkeley
***@***.***
http://eecs.berkeley.edu/~eal

**Comment by cmnrd** [comment]
I think physical actions make sense even without threads, since there are other mechanism for implementing asynchronous behavior. For instance, physical actions could be scheduled from interrupt routines. But that is another debate...

Putting this note aside, my point is that it is not obvious to a user why physical actions would work for `threads=1` and not for `threads=0`. I would even argue that `threads=0` does not make sense, because there is always one thread. I think a separate C-specific property for selecting the runtime would be clearer and also avoid conflicts in aligning the meaning of `threads` to other targets. After all, the overloaded meaning of `threads` for C, is the main reason why its implementation differs in C++.

**Comment by lhstrh** [comment]
Based on our discussion yesterday, the proposal is to have the following two target properties: `threading = on | off` (if supported, default is `on`) and `workers = [int]`. We will deprecate `threads` because it is ambiguous its meaning overloaded. By the time that we end up implementing preemption (where we the size of the thread pool has to outnumber the workers), we could add an extra parameter for that (may be `thread-pool-size = [int]`).
