### ISSUE TITLE
Create an automated release workflow

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/lingua-franca#338]
We should have a script that will make it easier to update our version numbers. Here are the relevant commits https://github.com/icyphy/lingua-franca/commit/18743feabe5ea6247ff55125bc15c52217ccc908 https://github.com/icyphy/lingua-franca/commit/db1602f6da608dfd4a4b91adc766c66ecd2793aa that show the locations that have to be touched.

The script could take two arguments: the current version string and the new version string. The script should first perform a dry run and show all the changes. If the user confirms the changes are OK, commit them.

**Comment by lhstrh** [comment]
On a related note, there exist some files in the repository that should not be committed accidentally contributors unless they are updating the base configuration (potentially as part of a version update). These files should be listed in `.gitignore` and only (forcefully) updated when this is really the intention. Let's first try to come up with an exhaustive list:
 - `org.lflang.targetplatform/org.lflang.targetplatform.target`
 - ...

**Comment by lhstrh** [comment]
@a-sr mentioned: Gradle/Eclipse might have functionality for this. Python script exists for Kieler.

**Comment by a-sr** [comment]
This is the Python script for setting the version in Kieler: https://git.rtsys.informatik.uni-kiel.de/projects/KIELER/repos/semantics/browse/build/scripts/version.py

**Comment by lhstrh** [comment]
A private `release-tools` repository has been instantiated, and I'm working on an automated workflow that bumps version numbers, updates release notes, runs tests, create tags, and creates releases.

**Comment by lhstrh** [comment]
I found out that OSGi does not allow versions like `0.1.0-beta`; it only allows `0.1.0` or `0.1.0.qualifier` (the latter is synonymous with `-SNAPSHOT` in Maven). This means that until we are done publishing prereleases, we should just stick with `0.1.0.qualifier` (OSGi) and `0.1.0-SNAPSHOT` (Maven). The workflows I started working on will not be usable until we are ready for `0.1.0`. This means we should move the completion of this task to our next milestone. We'll just publish `0.1.0-beta` manually.

**Comment by lhstrh** [comment]
How does this look for an automatically generated change log? Note that the first couple links don't work because the release hasn't been tagged yet. I encourage everyone to have a careful look the log below and correct/improve any PR or issue titles that are unclear. We can also do a better job categorizing PRs by labeling them. Any PRs that should not be included can be marked as such add the `exclude` label to them (more specifically, PRs that have any of the following labels are excluded: `trivial, duplicate, question, invalid, wontfix, ci, exclude`.

# Changelog

## [v0.1.0](https://github.com/lf-lang/lingua-franca/tree/v0.1.0) (2022-03-17)

[Full Changelog](https://github.com/lf-lang/lingua-franca/compare/v0.1.0-beta...v0.1.0)

**Implemented enhancements:**

- Tokens with destructors [\#973](https://github.com/lf-lang/lingua-franca/issues/973)
- Add a `-v` / `--version` flag to `lfc` [\#927](https://github.com/lf-lang/lingua-franca/issues/927)
- Running `lfc` on non-LF files results in uninformative error messages [\#919](https://github.com/lf-lang/lingua-franca/issues/919)
- Docker generation does not support the `files` target property [\#887](https://github.com/lf-lang/lingua-franca/issues/887)
- Preconfigure Epoch with example projects [\#374](https://github.com/lf-lang/lingua-franca/issues/374)
- In banks of reactors, bank\_index is not a proper parameter [\#343](https://github.com/lf-lang/lingua-franca/issues/343)
- Align the meaning of the 'threads' target property across targets. [\#290](https://github.com/lf-lang/lingua-franca/issues/290)
- Preempt keyword for reactions [\#280](https://github.com/lf-lang/lingua-franca/issues/280)

**Fixed bugs:**

- Maven build is broken [\#1033](https://github.com/lf-lang/lingua-franca/issues/1033)
- FilterBank benchmark in C++ has cycles [\#1031](https://github.com/lf-lang/lingua-franca/issues/1031)
- Dependency cycle detection does not seem to work  [\#1024](https://github.com/lf-lang/lingua-franca/issues/1024)
- Error reporting in Epoch is broken [\#994](https://github.com/lf-lang/lingua-franca/issues/994)
- Epoch fails to highlight errors on codegen [\#966](https://github.com/lf-lang/lingua-franca/issues/966)
- Some cargo errors are not reported in LF [\#936](https://github.com/lf-lang/lingua-franca/issues/936)
- Files without main don't compile if they have imports [\#913](https://github.com/lf-lang/lingua-franca/issues/913)
- Invalid time literal causees IllegalArgumentException [\#908](https://github.com/lf-lang/lingua-franca/issues/908)
- Reactor extending itself causes StackOverflowError [\#907](https://github.com/lf-lang/lingua-franca/issues/907)
- Having multiple unnamed main reactors causes nullPointerException [\#905](https://github.com/lf-lang/lingua-franca/issues/905)
- \[Python\]\[Federated\] Error when set connection not reacted [\#872](https://github.com/lf-lang/lingua-franca/issues/872)
- Catch errors from the TS type checker in the `examples` category [\#405](https://github.com/lf-lang/lingua-franca/issues/405)

**Closed issues:**

- CI workflow is broken? [\#1036](https://github.com/lf-lang/lingua-franca/issues/1036)
- EclipseErrorReporter reports errors in the wrong file [\#1030](https://github.com/lf-lang/lingua-franca/issues/1030)
- Epoch fails on valid file [\#1027](https://github.com/lf-lang/lingua-franca/issues/1027)
- List modal reactor tests in own category [\#1020](https://github.com/lf-lang/lingua-franca/issues/1020)
- Use a `dev` branch for development [\#1019](https://github.com/lf-lang/lingua-franca/issues/1019)
- Spurious warnings in Epoch [\#1016](https://github.com/lf-lang/lingua-franca/issues/1016)
- merge `JavaAstUtils` and `ASTUtils` [\#1003](https://github.com/lf-lang/lingua-franca/issues/1003)
- LSP tests randomly failing [\#953](https://github.com/lf-lang/lingua-franca/issues/953)
- Very strange error in C tests [\#932](https://github.com/lf-lang/lingua-franca/issues/932)
- Kotlin classes do not get build by `buildLfc` task \_unless\_ the `clean` task is also run ... [\#930](https://github.com/lf-lang/lingua-franca/issues/930)
- Use the same implementation of deque accross all C benchmarks [\#765](https://github.com/lf-lang/lingua-franca/issues/765)
- Use the BenchmarkRunner reactor in all C benchmarks [\#764](https://github.com/lf-lang/lingua-franca/issues/764)
- Build both Epoch with maven and lfc with gradle in our CI workflow [\#575](https://github.com/lf-lang/lingua-franca/issues/575)
- C syntax for referencing parameters and state variables [\#82](https://github.com/lf-lang/lingua-franca/issues/82)

**Merged pull requests:**

- Removed broken dependency on `org.eclipse.xpand.feature.group` [\#1050](https://github.com/lf-lang/lingua-franca/pull/1050) ([lhstrh](https://github.com/lhstrh))
- Port `CGenerator.xtend` to java [\#1049](https://github.com/lf-lang/lingua-franca/pull/1049) ([housengw](https://github.com/housengw))
- refactor `CGenerator.xtend` [\#1045](https://github.com/lf-lang/lingua-franca/pull/1045) ([housengw](https://github.com/housengw))
- Fix errors in tracing util. [\#1043](https://github.com/lf-lang/lingua-franca/pull/1043) ([hokeun](https://github.com/hokeun))
- Fix networkMessage action handling in TypeScript code generation, by considering action names prefixed with "networkMessage". [\#1042](https://github.com/lf-lang/lingua-franca/pull/1042) ([hokeun](https://github.com/hokeun))
- remove helper script used for refactoring [\#1041](https://github.com/lf-lang/lingua-franca/pull/1041) ([housengw](https://github.com/housengw))
- Improve Stability of Positioning Edges connected to Reactions in Diagrams [\#1040](https://github.com/lf-lang/lingua-franca/pull/1040) ([a-sr](https://github.com/a-sr))
- \[error reporting\] Correct bugs reported on Epoch. [\#1038](https://github.com/lf-lang/lingua-franca/pull/1038) ([petervdonovan](https://github.com/petervdonovan))
- Ganged connections [\#1037](https://github.com/lf-lang/lingua-franca/pull/1037) ([edwardalee](https://github.com/edwardalee))
- refactor `CGenerator.xtend` [\#1035](https://github.com/lf-lang/lingua-franca/pull/1035) ([housengw](https://github.com/housengw))
- Broaden a pylint ignore. [\#1029](https://github.com/lf-lang/lingua-franca/pull/1029) ([petervdonovan](https://github.com/petervdonovan))
- Automatically cancel old workflow actions [\#1028](https://github.com/lf-lang/lingua-franca/pull/1028) ([Soroosh129](https://github.com/Soroosh129))
- Fixed causality loop detection bug [\#1026](https://github.com/lf-lang/lingua-franca/pull/1026) ([edwardalee](https://github.com/edwardalee))
- \[CI\] Bring back PNPM cache. [\#1025](https://github.com/lf-lang/lingua-franca/pull/1025) ([petervdonovan](https://github.com/petervdonovan))
- ASTUtils cleanup [\#1022](https://github.com/lf-lang/lingua-franca/pull/1022) ([cmnrd](https://github.com/cmnrd))
- Bump Xtext from 2.25.0 to 2.26.0 [\#1021](https://github.com/lf-lang/lingua-franca/pull/1021) ([lhstrh](https://github.com/lhstrh))
- Suppress line-too-long warnings in the Python target. [\#1018](https://github.com/lf-lang/lingua-franca/pull/1018) ([petervdonovan](https://github.com/petervdonovan))
- Revert change in validator that caused Cast Exception [\#1017](https://github.com/lf-lang/lingua-franca/pull/1017) ([housengw](https://github.com/housengw))
- Improve layout options [\#1015](https://github.com/lf-lang/lingua-franca/pull/1015) ([soerendomroes](https://github.com/soerendomroes))
- Removed unnecessary xtend-gen folder from classpath. [\#1014](https://github.com/lf-lang/lingua-franca/pull/1014) ([soerendomroes](https://github.com/soerendomroes))
- Added ROS2 serialization tests [\#1012](https://github.com/lf-lang/lingua-franca/pull/1012) ([Soroosh129](https://github.com/Soroosh129))
- Refactor `CGenerator.xtend` [\#1011](https://github.com/lf-lang/lingua-franca/pull/1011) ([housengw](https://github.com/housengw))
- Support modal models in Python [\#1009](https://github.com/lf-lang/lingua-franca/pull/1009) ([edwardalee](https://github.com/edwardalee))
- Grammar cleanup [\#1008](https://github.com/lf-lang/lingua-franca/pull/1008) ([cmnrd](https://github.com/cmnrd))
- Merge `JavaAstUtils` into `ASTUtils` [\#1004](https://github.com/lf-lang/lingua-franca/pull/1004) ([housengw](https://github.com/housengw))
- Move benchmarks to separate repository [\#1001](https://github.com/lf-lang/lingua-franca/pull/1001) ([cmnrd](https://github.com/cmnrd))
- \[C\] do not generate code without main reactor [\#1000](https://github.com/lf-lang/lingua-franca/pull/1000) ([housengw](https://github.com/housengw))
- Check for null reactor to avoid NPE [\#998](https://github.com/lf-lang/lingua-franca/pull/998) ([edwardalee](https://github.com/edwardalee))
- Fix eclipse error reporting [\#995](https://github.com/lf-lang/lingua-franca/pull/995) ([cmnrd](https://github.com/cmnrd))
- Replace the 'threads' target property with the 'workers' and 'threading' properties [\#993](https://github.com/lf-lang/lingua-franca/pull/993) ([cmnrd](https://github.com/cmnrd))
- add FPS and update README of YOLO demo [\#989](https://github.com/lf-lang/lingua-franca/pull/989) ([housengw](https://github.com/housengw))
- Docker files property [\#987](https://github.com/lf-lang/lingua-franca/pull/987) ([housengw](https://github.com/housengw))
- Enable generation of ROS2 nodes directly from C++ code [\#984](https://github.com/lf-lang/lingua-franca/pull/984) ([cmnrd](https://github.com/cmnrd))
- Carla intersection refactoring [\#982](https://github.com/lf-lang/lingua-franca/pull/982) ([housengw](https://github.com/housengw))
- Added `--version` flag to `lfc`and improved error messages [\#979](https://github.com/lf-lang/lingua-franca/pull/979) ([cmnrd](https://github.com/cmnrd))
- FileConfig cleanups [\#978](https://github.com/lf-lang/lingua-franca/pull/978) ([cmnrd](https://github.com/cmnrd))
- Add invoke\_deadline\_handler parameter to AnytimePrime.lf. [\#976](https://github.com/lf-lang/lingua-franca/pull/976) ([hokeun](https://github.com/hokeun))
- Port `GeneratorBase.xtend` to Java [\#974](https://github.com/lf-lang/lingua-franca/pull/974) ([housengw](https://github.com/housengw))
- Matrix benchmark fix [\#972](https://github.com/lf-lang/lingua-franca/pull/972) ([jhaye](https://github.com/jhaye))
- Add reactor-cpp as a submodule and reorganize the C++ build process [\#971](https://github.com/lf-lang/lingua-franca/pull/971) ([cmnrd](https://github.com/cmnrd))
- Simplify conditional fed codegen [\#970](https://github.com/lf-lang/lingua-franca/pull/970) ([edwardalee](https://github.com/edwardalee))
- Fix port type mismatch in AnytimePrime.lf [\#968](https://github.com/lf-lang/lingua-franca/pull/968) ([hokeun](https://github.com/hokeun))
- Epoch error reporting [\#967](https://github.com/lf-lang/lingua-franca/pull/967) ([edwardalee](https://github.com/edwardalee))
- Detect and flag and as error multiple mains. [\#965](https://github.com/lf-lang/lingua-franca/pull/965) ([edwardalee](https://github.com/edwardalee))
- Improve warning message for unrecognized target parameters [\#964](https://github.com/lf-lang/lingua-franca/pull/964) ([cmnrd](https://github.com/cmnrd))
- FileConfig cleanup [\#963](https://github.com/lf-lang/lingua-franca/pull/963) ([cmnrd](https://github.com/cmnrd))
- Inheritance cleanups [\#962](https://github.com/lf-lang/lingua-franca/pull/962) ([edwardalee](https://github.com/edwardalee))
- Validator cleanups [\#961](https://github.com/lf-lang/lingua-franca/pull/961) ([edwardalee](https://github.com/edwardalee))
- Add C code generation to store currently executed reaction, add AnytimePrime.lf as a demo for check\_deadline\(\). [\#960](https://github.com/lf-lang/lingua-franca/pull/960) ([hokeun](https://github.com/hokeun))
- Ported `PythonGenerator.xtend` to Java and started refactoring of `GeneratorBase` [\#958](https://github.com/lf-lang/lingua-franca/pull/958) ([housengw](https://github.com/housengw))
- C benchmark repairs [\#957](https://github.com/lf-lang/lingua-franca/pull/957) ([petervdonovan](https://github.com/petervdonovan))
- clean up the file writing mechanism [\#956](https://github.com/lf-lang/lingua-franca/pull/956) ([cmnrd](https://github.com/cmnrd))
- Added the `--ignore-dependencies` flag to the uninstallation of `gcc` on MacOS \(fixes \#953\) [\#954](https://github.com/lf-lang/lingua-franca/pull/954) ([housengw](https://github.com/housengw))
- Fixes \#768 [\#952](https://github.com/lf-lang/lingua-franca/pull/952) ([housengw](https://github.com/housengw))
-  Port  `org.lflang.federated` to java [\#950](https://github.com/lf-lang/lingua-franca/pull/950) ([housengw](https://github.com/housengw))
- Fixed bug in centralized coordination related to time advancement [\#949](https://github.com/lf-lang/lingua-franca/pull/949) ([housengw](https://github.com/housengw))
- Update reactor-cpp version [\#946](https://github.com/lf-lang/lingua-franca/pull/946) ([cmnrd](https://github.com/cmnrd))
- Get C benchmarks working again. [\#943](https://github.com/lf-lang/lingua-franca/pull/943) ([petervdonovan](https://github.com/petervdonovan))
- Add bank & multiport support in TypeScript code generator with \> 30 multiport tests. [\#942](https://github.com/lf-lang/lingua-franca/pull/942) ([hokeun](https://github.com/hokeun))
- Report raw, unparsed error streams as a last resort. [\#941](https://github.com/lf-lang/lingua-franca/pull/941) ([petervdonovan](https://github.com/petervdonovan))
- Ported Xtend code in diagram package to Java [\#940](https://github.com/lf-lang/lingua-franca/pull/940) ([housengw](https://github.com/housengw))
- Refactoring: Purge code generators of IFileSystemAccess2. [\#938](https://github.com/lf-lang/lingua-franca/pull/938) ([petervdonovan](https://github.com/petervdonovan))
- Fix gradle setup by setting kotlin version to 1.4.30 [\#934](https://github.com/lf-lang/lingua-franca/pull/934) ([cmnrd](https://github.com/cmnrd))
- Fixes \#932 [\#933](https://github.com/lf-lang/lingua-franca/pull/933) ([Soroosh129](https://github.com/Soroosh129))
- Carla intersection updates [\#901](https://github.com/lf-lang/lingua-franca/pull/901) ([Soroosh129](https://github.com/Soroosh129))
- port `LFValidator.xtend` to java [\#886](https://github.com/lf-lang/lingua-franca/pull/886) ([housengw](https://github.com/housengw))
- attempt to fix failing benchmark tests in \#777 [\#852](https://github.com/lf-lang/lingua-franca/pull/852) ([housengw](https://github.com/housengw))
- AlarmClock example [\#780](https://github.com/lf-lang/lingua-franca/pull/780) ([revol-xut](https://github.com/revol-xut))
- Benchmark Runner for C Benchmarks [\#777](https://github.com/lf-lang/lingua-franca/pull/777) ([mattchorlian](https://github.com/mattchorlian))
- C new scheduler [\#743](https://github.com/lf-lang/lingua-franca/pull/743) ([Soroosh129](https://github.com/Soroosh129))
- Modal Models [\#501](https://github.com/lf-lang/lingua-franca/pull/501) ([a-sr](https://github.com/a-sr))
