### ISSUE TITLE
IDE Improvements

### ISSUE THREAD

**Issue by Feliix42** [lf-lang/lingua-franca#352]
After discussing this with @cmnrd I wanted to share a few things I noticed after using the Eclipse product I built from scratch using `maven` (based on commit 88c2dc02632ea8ff35e83523bfca9c097efbe5ba). Those are mainly just things I found odd, but maybe it makes sense to fix some of these issues:

- There does not seem to be a dedicated "Lingua Franca" project type. Instead, when creating a new project I'm offered the choice between either a _General Project_ or language-specific things like C/C++/Java/PyDev. Maybe having a Lingua Franca Project type with a project skeleton would be a good idea?
- Christian told me that having a `src/` directory for your code within a project is strongly encouraged. Maybe this could be part of aforementioned project skeleton?
- The diagram feature of the IDE is in my opinion a great help for developing reactor programs. Sadly, the feature is well-hidden in the IDE behind `Window > Show View > Other ... > KIELER Lightweight Diagrams > Diagram`, making it almost impossible to find if you don't know it exists. Maybe it would make sense to automatically open the diagram view when opening a LF file or making the view more accessible by placing it in the "Show View" menu? I possess no knowledge about what's possible to do in an Eclipse product, so these are just suggestions.

Let me know what you think, these are just my two cents as a new user.

**Comment by lhstrh** [comment]
These are all great points. But I'm sure not quite sure how to configure these things...

I've noticed this [tutorial](https://www.vogella.com/tutorials/EclipseRCP/article.html) that might hold some answers...

**Comment by a-sr** [comment]
I just added a [creation wizard for new LF files](https://github.com/icyphy/lingua-franca/commit/94c19bf8766ddcca5aea3cf339d0f20b32c3a631). Similarity, a creation wizard for LF projects could be created.

Furthermore, the LF perspective is now active by default, which has a diagram view already opened.

**Comment by lhstrh** [comment]
These are really great improvements! Yes, we should also have an LF project creation wizard...

**Comment by lhstrh** [comment]
It seems that the only thing holding us back from closing this issue at this point is a project creation wizard. @a-sr: would you be able to bootstrap this? I can create the icons and fine tune text etc...

**Comment by cmnrd** [comment]
I think we can close this now, right @lhstrh?

**Comment by lhstrh** [comment]
I plan to close this with #829 by collecting the example code  from files in the `example` directory rather than having copies of LF code in the Java/Xtend code because the stuff in the `example` directory gets tested in CI.
