### ISSUE TITLE
The gradle build on master breaks after changing ASTUtils.xtend

### ISSUE THREAD

**Issue by cmnrd** [lf-lang/lingua-franca#357]
This happens even in a fresh clone. Steps to reproduce:
```
git clone git@github.com:icyphy/lingua-franca.git
cd lingua-franca
./gradlew generateStandaloneCompiler
echo " " >> org.lflang/src/org/lflang/ASTUtils.xtend
./gradlew generateStandaloneCompiler
```
where the `echo " " >>` line adds an empty line to the file. This yields the following errors:
```
RROR:The method or field GEN_DELAY_CLASS_NAME is undefined for the type Class<GeneratorBase> (file:/home/cmenard/tmp/lingua-franca/org.lflang/src/org/lflang/ASTUtils.xtend line : 303 column : 27)
ERROR:The method or field GEN_DELAY_CLASS_NAME is undefined for the type Class<GeneratorBase> (file:/home/cmenard/tmp/lingua-franca/org.lflang/src/org/lflang/ASTUtils.xtend line : 306 column : 35)
ERROR:The method or field GEN_DELAY_CLASS_NAME is undefined for the type Class<GeneratorBase> (file:/home/cmenard/tmp/lingua-franca/org.lflang/src/org/lflang/ASTUtils.xtend line : 303 column : 27)
ERROR:The method or field GEN_DELAY_CLASS_NAME is undefined for the type Class<GeneratorBase> (file:/home/cmenard/tmp/lingua-franca/org.lflang/src/org/lflang/ASTUtils.xtend line : 306 column : 35)
```
Running `.gradlew clean` does not help. Strangely, this only happens when changing ASTUtils.xtend. I also tried with a few other files, but it seems to work fine.

@oowekyala was also able to reproduce this issue.

**Comment by lhstrh** [comment]
Bizarre! Perhaps treat is as a feature until we've completed our transition to Kotlin? :-)

**Comment by lhstrh** [comment]
Have you tried removing your `~/.gradle` directory before doing this? In my experience, it sometimes makes inexplicable Gradle errors go away...

**Comment by cmnrd** [comment]
I don't think we can transition so fast ;-) Actually this blocks me in porting the C++ generator, because I need to fix something in the code for after delay generation in ASTUtils.

I tried to delete the `~/.gradle` directory, which allowed me to compile the modified ASTUtils.xtend just fine. But adding yet another line to ASTUtils.xtend and compiling again triggeres the same errors as before. At least I can compile now by deleting `~/.gradle` every time ASTUtils.xtend changes :rocket:

**Comment by lhstrh** [comment]
Maybe it's worth attempting to switch to a newer version of Gradle?

**Comment by lhstrh** [comment]
See `gradle/wrapper/gradle-wrapper.properties`. Maybe change it to 7?

**Comment by cmnrd** [comment]
Gradle 7.0 produces this error for a clean build:
```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/cmenard/tmp/lingua-franca/org.lflang.ide/build.gradle' line: 26

* What went wrong:
A problem occurred evaluating project ':org.lflang.ide'.
> Could not get unknown property 'runtime' for configuration container of type org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.
```

For gradle 6.9 normal build works, but there are the same errors after changing ASTUtils.

**Comment by lhstrh** [comment]
The thing with ASTUtils is really mysterious...
