### ISSUE TITLE
Preconfigure Epoch with example projects

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/lingua-franca#374]
@cmnrd suggested we "add projects to the default workspace, where each project contains the examples of one LF target"

**Comment by a-sr** [comment]
There is no default workspace in an eclipse product. A workspace is selected/created by the user when the application starts for the first time.
However, we could add button to welcome page for importing the examples.
There is also the option to create example projects (File -> New -> Example...). I have never written an integration for that myself but Xtext has one that could be used as a template: https://github.com/eclipse/xtext-eclipse/tree/master/org.eclipse.xtext.xtext.ui.examples
