### ISSUE TITLE
Rename `master` to `main`

### ISSUE THREAD

**Issue by Soroosh129** [lf-lang/lingua-franca#423]
Verbatim from [GitHub documentation](https://github.com/github/renaming):

> Many communities, both on GitHub and in the wider Git community, are considering renaming the default branch name of their repository from master. GitHub is gradually renaming the default branch of our own repositories from master to main. We're committed to making the renaming process as seamless as possible for project maintainers and all of their contributors. This repository is our up-to-date guidance on how and when to rename your default branch.

This change could potentially break existing setups but it is increasingly becoming the default in Git repositories.

**Comment by lhstrh** [comment]
Yes, I agree we should do this at some point. Let's do it some time in the second half of August?

**Comment by cmnrd** [comment]
I think I am missing something here. Why the change?

**Comment by lhstrh** [comment]
It's part of an effort to move away from terms like master/slave, black list/white list, etc. Here's an NYT article: https://www.nytimes.com/2021/04/13/technology/racist-computer-engineering-terms-ietf.html

**Comment by cmnrd** [comment]
Ok, makes sense. I think this could be done together with moving the repository to the `lf-lang` organization. Then we only need to change our setup once.

**Comment by cmnrd** [comment]
We had too many breaking changes, we might as well tackle this one! Perhaps a good strategy is to establish a 'main' branch and let it mirror master for a while. Then we can switch all CI workflows (in other repos) from master to main and eventually make master read only and set 'main' as the main branch. Do we have someone who could be interested in working on this? @petervdonovan perhaps?

**Comment by petervdonovan** [comment]
I'm not sure how easy it will be to have another branch mirror `master`. Why not just do this all at once? Start a new branch called `main` that is based on `master`, update all the satellite repositories to track `main`, delete `master`, and then deal with anything else that breaks thereafter?

**Comment by lhstrh** [comment]
We don't have to delete `master`, we just have to make it not the default branch and make it read-only. That said, deleting it does make it apparent in which places stale references to `master` are lingering. I'm fine with the approach @petervdonovan outlines..
