### ISSUE TITLE
Make the lfc scripts more robust such that they don't need patching in our releases

### ISSUE THREAD

**Issue by cmnrd** [lf-lang/lingua-franca#434]
Our current release process requires patching of the lfc scripts (see #432). We should aim at making the scripts more robust, such that they work as expected both in the context of a release and in a developer's setup.

**Comment by lhstrh** [comment]
@cmnrd: can we close this, or are there still any rough edges?

**Comment by cmnrd** [comment]
AFAIK this is fixed
