### ISSUE TITLE
C++: Compilation fails if unusued imports.

### ISSUE THREAD

**Issue by HugoForrat** [lf-lang/lingua-franca#487]
Given

```
└── src
    ├── foo.lf
    └── Main.lf
```
with
```
# foo.lf
target Cpp;

reactor X {
  reaction(startup) {=
    std::cout << "Foo" << std::endl;
  =}
}
```
and
```
# Main.lf
target Cpp;

import X from "foo.lf"

main reactor {
  reaction(startup) {=
    std::cout << "Hello world" << std::endl;
  =}
}
```
The result of the compilation (`lfc src/Main.lf`) is:
```
// ...snip...
In file included from <project_dir>/src-gen/Main/Main/Main.hh:15,
                 from <project_dir>/src-gen/Main/Main/Main.cc:8:
<project_dir>/src-gen/Main/Main/_lf_preamble.hh:15:10: fatal error: foo/_lf_preamble.hh: No such file or directory
   15 | #include "foo/_lf_preamble.hh"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/Main.dir/build.make:90: CMakeFiles/Main.dir/Main/Main.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from <project_dir>/src-gen/Main/Main/_lf_preamble.cc:10:
<project_dir>/src-gen/Main/Main/_lf_preamble.hh:15:10: fatal error: foo/_lf_preamble.hh: No such file or directory
   15 | #include "foo/_lf_preamble.hh"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/Main.dir/build.make:104: CMakeFiles/Main.dir/Main/_lf_preamble.cc.o] Error 1
In file included from <project_dir>/src-gen/Main/Main/Main.hh:15,
                 from <project_dir>/src-gen/Main/main.cc:21:
<project_dir>/src-gen/Main/Main/_lf_preamble.hh:15:10: fatal error: foo/_lf_preamble.hh: No such file or directory
   15 | #include "foo/_lf_preamble.hh"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Since #199 specifies that unused imports should lead to warnings and not to errors, I assume this is a bug.
But it is obviously a very low-priority one since one can simply comment out the import.

**Comment by cmnrd** [comment]
Oh, interesting. Thanks for reporting!

Do we have a testcase for this in other targets?

**Comment by HugoForrat** [comment]
> Do we have a testcase for this in other targets?

I didn't find any; the bug apparently doesn't occur with the C and Python targets.

**Comment by revol-xut** [comment]
I was able to reproduce this in one of my projects. It appears that the C++ target looks at the entire wrong place.

It wants to include 
`./src-gen/Main/Main/foo/_lf_preamble.hh`
But the file exists at:
`./src-gen/foo/foo/_lf_preamble.hh`

**Comment by cmnrd** [comment]
That `./src-gen/foo/foo/_lf_preamble.hh` is created is interesting. It appears that we are not looking in the wrong place for the file, but it rather is created in wrong place. I am not sure why this is...

I think in your case, the `Filter` reactor is actually used, right? So this seems to be another issue. Could you try to provide a minimal example?
