### ISSUE TITLE
C generator produces unparsable code with fixed-sized arrays

### ISSUE THREAD

**Issue by oowekyala** [lf-lang/lingua-franca#493]
C doesn't support fixed-sized array types. However, the validator does not report this. Instead, the code generator produces unparsable code, which the C compiler then chokes on. For instance:
```
main reactor Foo {
   state foo: int[2](1, 2)
}
```
produces something like 
```C
static int[2] r_initial_foo = {1, 2};
//        ^^^ parse error
```

This should be caught by the validator and the generator should not be invoked at all.

**Comment by cmnrd** [comment]
Closing this as this appears to be working fine currently
