### ISSUE TITLE
Compile errors no longer show up in Epoch

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#519]
In the master branch, using the Epoch IDE, compiler errors no longer show up in the editor.  They are printed in the Console window, but no error marks appear in the editor window.  When did this stop working?  Perhaps as part of making cmake the default?

**Comment by Soroosh129** [comment]
This is fixed in #513 for the most part. 
The error reporting in general is a bit of a hit or miss since we attempt to do pattern matching on the output of the compiler.
I will try to create a more concise issue about the shortcomings of the IDE error reporting feature.
