### ISSUE TITLE
Improve caching in Github Actions

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/lingua-franca#526]
We can probably reduce install/initialization time of tests by doing more caching.

**Comment by cmnrd** [comment]
There is also the option to build a custom docker image and use this for our tests. We would need to update the image regularly though and push it to docker hub. Perhaps this could be automated in another periodic action.

**Comment by lhstrh** [comment]
Docker only works for Linux AFAIK. I've worked a bit on the caching (#1628), and it seems to work pretty well for `gradle`. We might want to do something similar for `pnpm`.

**Comment by lhstrh** [comment]
On second thought, `pnpm` already caches things between runs of individual tests, so I don't think caching the `pnpm` cache will buy us much. It's been mostly `gradle` that has been causing us grief with broken socket connections and failed downloads. Let's close this for now since it appears #1628 offers an adequate solution.

**Comment by edwardalee** [comment]
Docker works on Mac.

**Comment by cmnrd** [comment]
I think @lhstrh was referring to the environment inside the container, which is Linux based.
