### ISSUE TITLE
handle_t: Windows-specific name collision

### ISSUE THREAD

**Issue by petervdonovan** [lf-lang/lingua-franca#531]
There seems to be a Windows-specific name collision that results from `handle_t` being defined as an alias for `RPC_BINDING_HANDLE` on Windows. I'm not sure because I am not experienced with C, but [this page](https://docs.microsoft.com/en-us/windows/win32/midl/handle-t) seems to explain the problem.

### Minimal Example

Here is a minimal example required to reproduce the error.

Directory structure:
```
test
│  test.c
│  CMakeLists.txt
└─ build
```

Content of `test.c`:
```
#include <windows.h>
typedef int handle_t;
```

Content of `CMakeLists.txt`:
```
cmake_minimum_required(VERSION 3.10)
project(test)
add_executable(test test.c)
```

Error message after running `cmake ..` and `cmake --build .` in the `build` directory:
```
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  test.c
C:\Users\Peter\Downloads\test\test.c(3): error C2040: 'handle_t': 'int' differs in levels of indirection from 'RPC_BINDING_HANDLE' [C:\Us
ers\Peter\Downloads\test\build\test.vcxproj]
```

### Context
In case it matters, I ran into this issue while working on the language server because (after adding a semicolon in `windows_support.h`). CMake fails to build and gives a long list of errors, including this one. I do not know how many of the errors are cascading errors that result from this name collision. The relevant error message is
```
example\src-gen\reflexgame\core/reactor.h(340): error C2040: 'handle_t': 'int' differs in levels of indirect
ion from 'RPC_BINDING_HANDLE'
```

**Comment by Soroosh129** [comment]
This is already solved in [windows-c-target](https://github.com/lf-lang/lingua-franca/tree/windows-c-target). There are a few remaining issues to get the Windows support to fully work. Are you interested?

**Comment by lhstrh** [comment]
@Soroosh129: best create a draft PR for this to increase visibility.

**Comment by lhstrh** [comment]
Looks like this is subsumed by https://github.com/lf-lang/lingua-franca/pull/532
