### ISSUE TITLE
Nightly build fails with Maven errors

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/lingua-franca#539]
See: https://github.com/lf-lang/lingua-franca/runs/3706769597?check_suite_focus=true

Summary:

```
Error:  Cannot resolve target definition:
Error:    Software being installed: org.eclipse.lsp4e 0.13.5.202103011336
Error:    Software being installed: org.eclipse.wildwebdeveloper.feature.feature.group 0.10.9.202109141642
Error:    Only one of the following can be installed at once: [org.eclipse.lsp4e 0.13.6.202108060851, org.eclipse.lsp4e 0.13.5.202103011336]
Error:    Cannot satisfy dependency: org.eclipse.wildwebdeveloper 0.5.17.202109141642 depends on: osgi.bundle; org.eclipse.lsp4e 0.13.6
Error:    Cannot satisfy dependency: org.eclipse.wildwebdeveloper.feature.feature.group 0.10.9.202109141642 depends on: org.eclipse.equinox.p2.iu; org.eclipse.wildwebdeveloper [0.5.17.202109141642,0.5.17.202109141642]
Error:  
Error:  Failed to resolve target definition /home/runner/work/lingua-franca/lingua-franca/org.lflang.targetplatform/org.lflang.targetplatform.target: See log for details -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException
Error: Process completed with exit code 1.
```

**Comment by petervdonovan** [comment]
It seems like this was inevitable given that the `wildwebdeveloper` dependency was tied to the latest version whereas `lsp4e` was not. It works to change
```
<repository location="http://download.eclipse.org/wildwebdeveloper/releases/latest/"/>
```
to
```
<repository location="http://download.eclipse.org/wildwebdeveloper/releases/0.12.0/"/>
```
It also seems possible to move `lsp4e` to another `<location>` and use `<repository location="https://download.eclipse.org/lsp4e/releases/latest/">`

I don't know why we would prefer one of these to the other, however.

**Comment by cmnrd** [comment]
I guess such dependency issues will come up from time to time, but I would vote for always using the latest version, unless there are conflicts that we have to resolve manually by pinning versions.

**Comment by a-sr** [comment]
Eclipse 2021-09 was recently released. This often causes some version problems in the migration phase.
We did not yet switch to the new release which might be the reason for this error. Hence, I will first switch our version of Eclipse, maybe this will solve the problem by itself, if the dependency is provided implicitly. Otherwise, we need to provide the latest release explicitly.

**Comment by cmnrd** [comment]
I wonder how we should treat this in the future then. Should we pin all versions and manually update dependencies whenever there is a new Eclipse release?

**Comment by a-sr** [comment]
Upgrading to the latest Eclipse release solved the problem.

Yes, replacing "latest" update sites with specific version would reduce this problem.
I will adjust the PR accordingly.
