### ISSUE TITLE
Disable colored warnings/errors when running on Windows

### ISSUE THREAD

**Issue by Soroosh129** [lf-lang/lingua-franca#560]
Here is an example of an error in PowerShell:
```
←[1mlfc: ←[0m←[1;31merror←[0m←[1m:  returns error code 1←[0m
 --> (unknown file):null:null -  returns error code 1
```
And here is an example of a warning:
```
←[1mlfc: ←[0m←[1;33mwarning←[0m←[1m: Windows is not supported by the CCp target. Exiting code generation.←[0m
 --> (unknown file):null:null - Windows is not supported by the CCp target. Exiting code generation.
```

**Comment by cmnrd** [comment]
I assume this is when running lfc? Is this concerning Epoch?

**Comment by lhstrh** [comment]
https://stackoverflow.com/questions/51680709/colored-text-output-in-powershell-console-using-ansi-vt100-codes

**Comment by lhstrh** [comment]
I suppose the right solution would be to detect the platform and leave out the colors for Windows?

**Comment by oowekyala** [comment]
> I suppose the right solution would be to detect the platform and leave out the colors for Windows?

Yes this is totally possible, I think this is what many programs out there do

**Comment by lhstrh** [comment]
OK, I changed the title of the ticket accordingly.

**Comment by oowekyala** [comment]
(To note that these `(unknown file):null:null` are annoying and we should try to get rid of them.)

**Comment by cmnrd** [comment]
Better and more portable would be to check the terminals' capability to handle colors (independent of the platform). I don't know the Java API, but normally there is a method to check this. Also, on Linux there are terminals that don't support colors, and in some contexts like piping it's also better to omit colors.

**Comment by oowekyala** [comment]
@cmnrd you're right that this would be a more ideal solution, but there is no Java API to check this directly AFAIK. Here's how Picocli determines whether to emit colors: https://picocli.info/#_heuristics_for_enabling_ansi We'll probs need to implement something of that kind.

**Comment by lhstrh** [comment]
With the merge of https://github.com/lf-lang/lingua-franca/pull/1534, has been issue been address?

**Comment by cmnrd** [comment]
Works fine in PowerShell in my Windows VM. It does not work in the simple Windows command prompt. But for this the solution should be to simply use a proper shell...
