### ISSUE TITLE
Remove codecov PR annotations

### ISSUE THREAD

**Issue by oowekyala** [lf-lang/lingua-franca#571]
Codecov PR annotations make PR very hard to review by introducing noise, and I don't know how to disable them. I also think the information they provide is not worth much, and I'd rather like to look at coverage numbers from within the codecov interface itself.

Here's what #562 looks like to me:

![Capture d’écran de 2021-10-05 16-32-38](https://user-images.githubusercontent.com/24524930/136044032-ee4c6de4-3e8a-4277-84f8-8de327c35e34.png)

**Comment by cmnrd** [comment]
Also the codecov/patch task (whatever this is) always fails, leading to red crosses being shown on otherwise error-free PRs and commits.

**Comment by lhstrh** [comment]
Agreed. I'll disable this...

**Comment by lhstrh** [comment]
This is done, but now our code coverage badge also stopped working, see:

 [![codecov](https://codecov.io/gh/lf-lang/lingua-franca/branch/master/graph/badge.svg?token=b7LrpihI5a)](https://codecov.io/gh/lf-lang/lingua-franca)

No idea why. Help?
