### ISSUE TITLE
java.io.IOException: A required target resource could not be found: /lib/c/reactor-c/core/reactor_common.c

### ISSUE THREAD

**Issue by Soroosh129** [lf-lang/lingua-franca#615]
After pulling in the updates from master by doing the following at the top level:
```
git submodule update --init --recursive
git fetch --all
git pull
```
and performing a clean build, I get the following error in the Epoch IDE:
```
!MESSAGE org.eclipse.xtext.builder.BuilderParticipant  - Error during compilation of 'platform:/resource/C%20Tests/src/federated/HelloDistributed.lf'.

!STACK 0
java.io.IOException: A required target resource could not be found: /lib/c/reactor-c/core/reactor_common.c
Perhaps a git submodule is missing or not up to date.
See https://github.com/icyphy/lingua-franca/wiki/downloading-and-building#clone-the-lingua-franca-repository.
Also try to refresh and clean the project explorer if working from eclipse.
```

The file seems to be there:
```
soroush@Soroushs-MacBook-Air core % ls
federated		pqueue.c		reactor.h		tag.c			trace.h
platform		pqueue.h		reactor_common.c	tag.h			util.c
platform.h		reactor.c		reactor_threaded.c	trace.c			util.h
soroush@Soroushs-MacBook-Air core % pwd
/Users/soroush/lingua-franca-master/git/lingua-franca/org.lflang/src/lib/c/reactor-c/core
```

This is on MacOS on ARM (Apple M1). Any help would be appreciated.

**Comment by Soroosh129** [comment]
> Have you tried going into the location where the submodule is mounted and running `git pull origin main` in it? If that gives errors (perhaps due to history having been rewritten in that repo), do `git checkout bb437f6`.

Okay, thanks. This is good to know. Previously, `git pull` didn't work.

> You will also want to have rebuilt Epoch entirely. It looks up these files on the class path, so if Epoch isn't rebuilt from scratch, the files will likely not be there.

Do you mean I have to re-do the Oomph setup? I will give that a try.

**Comment by Soroosh129** [comment]
This is still unresolved. I suspect others with MacOS running on ARM might run into the same issue.

**Comment by lhstrh** [comment]
Have you created a completely fresh installation and got rid of any lingering state in your Maven/Gradle caches? If this is a MacOS/ARM-specific issue, then the title should reflect that. Our CI runs on MacOS show no problems...

**Comment by Soroosh129** [comment]
The problem is that our CI starts with a fresh setup every time if I'm not mistaken. But it also uses an Intel machine. Both can be a contributing factor here.

I will try to delete everything and start fresh when I'm finished with the current in-progress projects.
