### ISSUE TITLE
Switch to other code coverage reporting service

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/lingua-franca#617]
CodeCov hasn't been working so well. Perhaps we'll have more success with another service. We could try this Gradle plugin that would let us send coverage data to Coveralls.io instead.

https://github.com/nbaztec/coveralls-jacoco-gradle-plugin

**Comment by cmnrd** [comment]
What was the problem with CodeCov? Do you still want to switch or schould we close?

**Comment by lhstrh** [comment]
I think it works well now. We don't have to switch. If I recall correctly, the problems were actually tied to our non-standard Gradle configuration.
