### ISSUE TITLE
Summarizing target compiler error messages

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/lingua-franca#63]
While the C compiler catches missing dependency declarations, the resulting errors are a bit opaque. It might be helpful to run the error messages through some regular expressions and summarize the occurrence of common errors so that the feedback is easier to understand.

**Comment by edwardalee** [comment]
Also, in the Eclipse IDE, C compile errors are not visible. They go to stdout.

**Comment by cmnrd** [comment]
Closing this. We don't summarize (that would be tough to do anyway), but the handling of compile errors improved considerably.
