### ISSUE TITLE
Compilation of C programs is very slow for programs with large banks

### ISSUE THREAD

**Issue by cmnrd** [lf-lang/lingua-franca#635]
As pointed out by Edward in #481, compilation of larger programs such as Sleeping Barber with 5000 customers is very slow for the C target. On my machine, the C compiler needed almost 2 minutes to compile the program. This is likely due to the huge file size of the generated SleepingBarber.c (7.6MB!).

**Comment by Soroosh129** [comment]
> If I interpret the generated c code correctly, then the self struct of each of the 5000 customers is initialized individually.

That is correct.

> The C++ code generator simply creates a for loop to initialize banks

Hmm, shouldn't an unrolled for loop be faster?
