### ISSUE TITLE
People page needed on the Wiki

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#637]
We need a People page on the wiki, ideally with pictures of participants.  I'm not sure how to organize this. Suggestions?

**Comment by Soroosh129** [comment]
Would the list be limited to the participants in the repo itself? In that case, GitHub already has this: https://github.com/lf-lang/lingua-franca/graphs/contributors

**Comment by axmmisaka** [comment]
We have this now: https://www.lf-lang.org/community

Should we close this issue?
