### ISSUE TITLE
Reactor-level preambles in Python introduce shared state

### ISSUE THREAD

**Issue by cmnrd** [lf-lang/lingua-franca#640]
The python target places reactor level preambles in the scope of the reactor class. However, this is potentially dangerous as all preamble code (including all variables and state!) is shared between reactor instances. I believe the following example nicely illustrates the issue:
```
target Python

reactor Foo(value(0)) {
  preamble {=
    foo = []
  =}

  reaction(startup) {=
    self.foo.append(self.value)
    print(self.foo)
  =}
}

main reactor {
  foo1 = new Foo(value=1)
  foo2 = new Foo(value=2)
}
```
When executed, it prints
```
[1]
[1, 2]
```
Normally we would expect this program to print `[1]` and `[2]`, but both reactor instances operate on the same list.

**Comment by Soroosh129** [comment]
> Normally we would expect this program to print [1] and [2], but both reactor instances operate on the same list.

Why would you expect that? `foo = []` is a [class object](https://docs.python.org/3/tutorial/classes.html#class-objects) not an [instance object](https://docs.python.org/3/tutorial/classes.html#instance-objects).
