### ISSUE TITLE
Epoch does not invoke the code generator on save

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#666]
At least on MacOS, if a target-language compile error is triggered, then any further modifications made to the file fail to trigger the code generator. I have verified that this occurs with the nightly release of Epoch as well as Epoch launched from the Oomph IDE. This is a new behavior that has appeared in the last couple of days. Oddly, this behavior persists even if you close Epoch and reopen it, so there must be persistent state in the workspace.

**Comment by a-sr** [comment]
> I have a question for @a-sr: For me, the "Compile LF Program" option only appears when I right-click on the .lf file. Is there a way I can add that to the toolbar?

PR #719 adds a button to the toolbar that will compile the LF program of the activate editor.

**Comment by edwardalee** [comment]
I am closing this because Epoch has now become usable (thanks!). There are some improvements that would be helpful:
* Keyboard shortcut to compile a program.
* Better reporting of the results of compilation (you currently have to manually switch to the console view and read the output).
But these can wait.
