### ISSUE TITLE
Customize HyperlinkHelper to establish links to imported files

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/lingua-franca#70]
Some helpful info found here: https://stackoverflow.com/questions/39668062/xtext-hyperlinking-how-to

**Comment by cmnrd** [comment]
I am not sure what exactly the intention was here, but we have importing working reliably for a while now, so I am closing this.

**Comment by lhstrh** [comment]
The goal was is to allow a "go to definition" for imported files, which currently does not work. It works with the classes that are imported from it, but not if you select the filename.

**Comment by cmnrd** [comment]
Ok, should we reopen? Personally, I don't think this is a very important feature.
