### ISSUE TITLE
Timeout with value zero has different behaviour in C and Cpp

### ISSUE THREAD

**Issue by Rodario** [lf-lang/lingua-franca#725]
I have ported missing tests from the Cpp to C target and happened on a "bug" in one of them.
The test in question is the  [TimoutZero test.](https://github.com/lf-lang/lingua-franca/blob/ac2e091b5b52d50e67720db8b48bdd3b590b5921/test/C/src/TimeoutZero.lf).
My implementation looks like [this](https://github.com/lf-lang/lingua-franca/blob/62afd9652a12b67a972317f2fda47b7d52a0a787/test/Cpp/src/TimeoutZero.lf).

The "bug" is more of a implementation question it seems. A timeout of 0 in Cpp is handled as if there is no timeout where in C there is a termination after the 0th step.
I talked with @cmnrd about this and we wanted to ask, whats the correct behavior here?

**Comment by Soroosh129** [comment]
Others might want to discuss the requirements of the language.

However, from a practical standpoint, is there a way to stop the program at tag `(0,0)` in the Cpp target?

**Comment by cmnrd** [comment]
Yes, absolutely. Actually, the C++ runtime does not implement a timeout. Instead, the code generator simply injects a timeout reactor that sets a timer and it's reaction requests to stop the execution. In principle, the delay could be zero.

However, the issue at hand is the interpretation of zero. In C++, a timeout of zero is interpreted as invalid and hence there is no timeout. This is very convenient when using the CLI arguments. We can simply write `--timout 0` to disable a timeout.

How does the C runtime handle this? Which value has timeout if there is no timout configured?

**Comment by Soroosh129** [comment]
> Instead, the code generator simply injects a timeout reactor that sets a timer and it's reaction requests to stop the execution.

I don't see how with this implementation, a stop tag of `(0,0)` could be achieved. A `request_stop()` call should stop the program at least one microstep later.

> Which value has timeout if there is no timout configured?

I don't understand this question. Do you mean what the default timeout is? It is infinity by default (or FOREVER to be specific).
