### ISSUE TITLE
Support SI time units

### ISSUE THREAD

**Issue by oowekyala** [lf-lang/lingua-franca#742]
The grammar for time units doesn't support SI units like `ms` or `ns` (for resp. milli- and nanosecond). I believe these are widely used and understood so it would be nice for them to be supported.

Note that those are the units used in C++ duration literals:
https://github.com/lf-lang/lingua-franca/blob/fca5fa8391cf8a6482cdf73a6c7bfa53bcc3f9e3/test/Cpp/src/Schedule.lf#L7

https://en.cppreference.com/w/cpp/chrono/duration#Literals

The Rust runtime supports those units in its time-related macros:
https://github.com/lf-lang/lingua-franca/blob/fca5fa8391cf8a6482cdf73a6c7bfa53bcc3f9e3/test/Rust/src/ActionIsPresentDouble.lf#L9-L10

---

Any implementation attempt should probably happen after #620 has been salvaged, as that PR simplifies time units so that it will be trivial to implement this then.

**Comment by lhstrh** [comment]
I agree, the fact that we currently don't support `ms` and `ns` has annoyed me too...

**Comment by cmnrd** [comment]
Me three!
