### ISSUE TITLE
C trace tools - Failing to build on Mac

### ISSUE THREAD

**Issue by Elocien** [lf-lang/lingua-franca#757]
![image](https://user-images.githubusercontent.com/46900073/142202718-8b221b2d-f05a-4fd6-a8e6-fa575e26ec93.png)

I'm trying to build the C tracing tools from the utils/tracing directory. I'm getting the above error when attempting this.

Mac Book Pro, x86, Big Sur

**Comment by edwardalee** [comment]
I suspect you need to check out the reactor-c submodule. Unfortunately, this does not happen automatically when you clone the git repo for lingua-franca.  You need to do this:
```
git submodule update --init --recursive
```
Then check that the file `reactor.h` is in the right place:
```
> ls ../../org.lflang/src/lib/c/reactor-c/core
federated		pqueue.h		reactor_threaded.c	trace.h
platform		reactor.c		tag.c			util.c
platform.h		reactor.h		tag.h			util.h
pqueue.c		reactor_common.c	trace.c
```

**Comment by Elocien** [comment]
Ah okay, that fixed it. Thanks for the quick reply!
