### ISSUE TITLE
C Target: Memory for reactor structs seemingly is not freed

### ISSUE THREAD

**Issue by Soroosh129** [lf-lang/lingua-franca#793]
The code generator generates a `delete_FOO` function for each reactor class `FOO`. These functions free the allocated memory for each struct. However, these functions appear to not be called anywhere.

**Comment by edwardalee** [comment]
These functions are obsolete and poorly conceived.  What we need to do is have the self struct record a list of pointers to each malloc'd memory chunk and then just iterate over this list to free them. It would be best to wait until the scalability-banks is merged before fixing this however...

**Comment by petervdonovan** [comment]
If that is our approach, then maybe we can just use our own memory allocation function that records the pointers in a static global vector. Then we can just free everything in one function call, all the pointer-tracking is abstracted away, and it shouldn't interfere with the scalability branch too much.

I was actually tempted to do this already, but I wondered if those deletion functions would be useful for mutations. I know mutations might not be fully supported, but might we want to delete reactors at a time other than program termination?

**Comment by edwardalee** [comment]
Yes, I thought about this option as well, but if we ever want to support mutations, then we will need to be able to do individual deletions.  This will be needed even for fairly specialized forms of mutations.

**Comment by edwardalee** [comment]
My thought was to add a field to the self struct of each reactor, say `to_free`, that points to linked list of `void*` pointers, and then just iterate through that list in the destructor.  The challenge with doing this as library function replacing malloc/calloc is that the type of the self struct is specific to each reactor.  I'm not sure how to solve that problem.

**Comment by Soroosh129** [comment]
One way to get around this problem I think is to put `to_free` at the beginning of all self structs and then we can directly cast each self struct to its first member, e.g., `to_free`. 

A more sophisticated version of this trick is used in many C programs (including CPython) to "simulate" inheritance. For this to work, we can create a base generic struct and have all self structs create a pointer to that base generic struct as their first field:
```
struct base_self {
    void** to_free
};

struct foo_self {
    struct base_self* base;
    ...
}
```

**Comment by edwardalee** [comment]
That's a great idea.  There are a few other things we could put into base_self (perhaps this should be called self_base_t).
