### ISSUE TITLE
Diagram synthesis should be tested

### ISSUE THREAD

**Issue by cmnrd** [lf-lang/lingua-franca#802]
In some recent PR merges, the diagram synthesis broke for many of our tests and examples (see #801). That this could slip through unnoticed, shows that there is a big gap in our test infrastructure. We currently do not test the correct operation of the diagram package.

A simple test infrastructure for diagrams could simply generate diagrams for all of our tests and examples and see if any exceptions occur. While this is certainly not perfect and the output is not validated, this alone should give a high coverage and prevent issues such as #801. However, I suspect in order to make this work, we need to fix the compilation issues outlined in #398.

**Comment by lhstrh** [comment]
Related to #897.
