### ISSUE TITLE
When code generating federated programs from Epoch, the second generated program segfaults

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#827]
In Epoch, we have (thanks to @a-sr ) a button to generate code for a program.  In a federated program, such as `test/c/src/federated/HelloFederated.lf`, if you push this button twice without modifying the code, the first generated program works, but the second one segfaults.

This happens at least in the scalability-banks branch, but I suspect it happens in all branches.

The culprit is this line in GeneratorBase:
```
            // Remove the connections at the top level
            mainReactor.connections.clear()
```
The problem is that this line modifies the E-core model, and the second button push uses the modified E-core model to generate code.

A simple fix would be to augment the button added by @a-sr to first regenerate the E-core model, as happens when you make any modification to the file.  Any idea how to do that?

**Comment by Soroosh129** [comment]
Is this perhaps also related to #746?

**Comment by edwardalee** [comment]
Ah yes, this is the same issue. I will consolidate these.
