### ISSUE TITLE
Create a version bump script

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/lingua-franca#865]
Our build configuration is a bit complex, which makes it tricky to update version numbers. It would be helpful to have a script that lets us bump version numbers of arbitrary dependencies. We now do this manually. For instance, to bump our Xtend dependency (assuming there are no other dependencies with version number `2.25.0`), the following works:

To update the Xtext version for the Eclipse build:
```
find . -name *.MF -print0 | xargs -0 -n1 sed -i 's/2\.25\.0/2\.26\.0.M2/'
```
To update the Xtext version for Gradle:
```
find . -name 'gradle.properties' -print0 | xargs -0 -n1 sed -i 's/2\.25\.0/2\.26\.0.M2/'
```
To update the Xtext version for Maven:
```
find . -name 'pom.xml' -print0 | xargs -0 -n1 sed -i 's/2\.25\.0/2\.26\.0.M2/'
```

_Originally posted by @lhstrh in https://github.com/lf-lang/lingua-franca/issues/829#issuecomment-1016856250_

**Comment by housengw** [comment]
closing this issue since #870 has been merged
