### ISSUE TITLE
weird error message when STP or deadline is out of bound.

### ISSUE THREAD

**Issue by housengw** [lf-lang/lingua-franca#903]
minimal program:
```
target C;

reactor A {
    input i:int;
    reaction(i) {=

    =} STP(2147483648 nsec) {=

    =}
}
```

Error message:
```
For input string: "2147483648"
```

Same thing happens for deadlines

**Comment by housengw** [comment]
I suspect this issue is an integer overflow issue caused by the fact that `TimeValue.java` uses `long` for its time values and `Time.java` uses `int` for its time values.

**Comment by housengw** [comment]
I think we should parse the time values as strings in the grammar file and then do validation on the strings instead of ints or longs to prevent overflow

**Comment by edwardalee** [comment]
I tried to fix this but couldn't find a way that didn't make the grammar ambiguous.  I suggest we not fix this. I don't think it's worth it given that we have time units.
