### ISSUE TITLE
Add a `-v` / `--version` flag to `lfc`

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/lingua-franca#927]
Where should it read the version number from?

**Comment by cmnrd** [comment]
We could have a simple file `version.txt` in `org.lflang.lfc`. This should be easy to update by a script. Alternatively, we could define a constant in `Main`, which would be slightly more difficult to update.

`-v` is commonly used for verbose and I would reserve it for this use. It's probably fin to just have the long form `--version`.
