### ISSUE TITLE
lfc is broken on master and in our release artifacts

### ISSUE THREAD

**Issue by cmnrd** [lf-lang/lingua-franca#928]
lfc fails for the C++, Rust, and TypeScript targets, because it cannot load the Kotlin classes. I am clueless on what might be causing this, but something in the build setup must have changed recently. For this reason, the lfc 0.1.0-beta release artifacts to not work currently.

I also wonder why none of our tests revealed this problem.

**Comment by petervdonovan** [comment]
I think this problem actually did appear in CI in the `release` branch, and it seemed to be a problem with Gradle's incremental build feature. Our "solution" was to use `./gradlew clean`.

**Comment by housengw** [comment]
maybe we could add `try ./gradlew clean` in the error message as a pointer...

**Comment by lhstrh** [comment]
Confirming that the problem how the artifacts were built (without `clean`). There is nothing actionable w.r.t. the code. I will create a separate issue to address apparent deficiency in our Gradle configuration.

**Comment by lhstrh** [comment]
> maybe we could add `try ./gradlew clean` in the error message as a pointer...

I think we should just fix the build configuration (as per #930). While the suggested error message might be useful for us, it won't be useful for third-party users (who don't build from source).
