### ISSUE TITLE
Very strange error in C tests

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/lingua-franca#932]
See https://github.com/lf-lang/lingua-franca/actions/runs/1787860560
This failure deserves attention...

**Comment by Soroosh129** [comment]
The deadline on the reaction in Destination is set to 200 msec, which can easily be violated on GitHub Actions given the delays we have seen before. I'll add some slack to the test.

**Comment by lhstrh** [comment]
But the message is: `ERROR: Deadline miss handler invoked without deadline violation.` That suggests a logic error, not an unexpected deadline violation.

**Comment by Soroosh129** [comment]
The deadline handler freaks out if it is triggered when `count` is even, which could happen if the "lag" in the system is more than 200 msec when Source produces its first or third outputs.

**Comment by lhstrh** [comment]
Then why add slack? It seems that the test is insufficient. It can additionally check for elapsed physical time having exceeded a threshold. If it has, the test passes. If it hasn't, then it can fail with the original error message that indicates a logic error. Alternatively, the message could be adjusted to say something like `ERROR: Deadline miss handler was invoked without deadline violation -OR- the observed latency exceeded 200ms.`

**Comment by Soroosh129** [comment]
> It can additionally check for elapsed physical time having exceeded a threshold. If it has, the test passes.

This adds potential for a false positive though since “upstream” delays are indistinguishable. In other words, a faulty implementation (of a scheduler, for example) that happens to also introduce considerable lag (that surpasses this threshold) can pass this test.

> Alternatively, the message could be adjusted to say something like ERROR: Deadline miss handler was invoked without deadline violation -OR- the observed latency exceeded 200ms.

Okay, makes sense.
