### ISSUE TITLE
weird diagram when causality loop is detected

### ISSUE THREAD

**Issue by housengw** [lf-lang/lingua-franca#945]
Minimal program:
```
target Python;

reactor A {
    input i;
    output o;
    reaction (i) -> o {=

    =}
}

reactor B {
    input i;
    output o;
    reaction (i) -> o {=
        
    =}
}

main reactor {
    a = new A();
    b = new B();
    a.o -> b.i;
    b.o -> a.i;
}
```

Diagram in the VS Code extension
![Screenshot from 2022-02-07 14-43-56](https://user-images.githubusercontent.com/46389172/152884882-aa08a618-39b5-4e55-b518-7eccc1e39d78.png)

**Comment by soerendomroes** [comment]
What kind of monitor are you using? This may be an issue with KLighD and 4K monitors. Otherwise, this seems to be fixed.

**Comment by a-sr** [comment]
Given the comment by @soerendomroes and no further activity, I assume this issue to be fixed.

Please reopen if the problem persists.

**Comment by lhstrh** [comment]
I haven't seen this happen in a long time, so it must have been been fixed!
