### ISSUE TITLE
Ports in main or federated reactor

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#969]
I think we should disallow ports in the top-level reactor. Currently, the validator allows it, but the diagram does not render the ports. Minimal example:
```
target C;
main reactor {
    input x:int;
}
```
This gets rendered as follows:
<img width="365" alt="image" src="https://user-images.githubusercontent.com/8513334/154375444-238bf1bc-1634-457b-b7d5-e3105df512ee.png">

Note the missing port. I tried adding a check in the validator, but unfortunately, for federated systems, a dummy input port gets put at the top level called "outputControlReactionTrigger".  So I'm not sure what we should do.

**Comment by Soroosh129** [comment]
I think this is related to #618.

**Comment by Soroosh129** [comment]
The choice of making `outputControlReactionTrigger` a port was arbitrary. We could change it to an action. This trigger is supposed to be triggered by the runtime at the start of each tag, so I think it doesn’t matter what kind of trigger it is.

**Comment by housengw** [comment]
this issue has been fixed by 7204296a8e01edfb875abfb5e562fcbd3b3f40cf
