### ISSUE TITLE
Change the way we copy library sources into `src-gen`

### ISSUE THREAD

**Issue by lhstrh** [lf-lang/lingua-franca#97]
When using the compiler in `INTEGRATED` mode, library files copied into the `src-gen` directory are read from an Eclipse resource, which don't get updated if the source files change on the file system. This extremely annoying during debugging. Either a refresh should be triggered, or we should not use a resource for library files and instead copy them directly from the file system.

**Comment by cmnrd** [comment]
Closing this. I think we are used to recompiling when library files change by now. Also, we have the `external-runtime` property which allows to point to another copy of the runtime.
