### ISSUE TITLE
Tokens with destructors

### ISSUE THREAD

**Issue by edwardalee** [lf-lang/lingua-franca#973]
In our conversation with @rcakella today, it became clear that we need to enhance the token mechanism in the C infrastructure with a token that carries its own destructor. Specifically, you can currently use some of the SET functions, for example SET_NEW, to dynamically allocate memory for an outgoing message, and then a reference counting mechanism is used to later free this memory when it is no longer used. But this will not work if your message is, for example, a struct that contains pointers to dynamically allocated memory.  Only the struct will be freed, not the pointed to memory. A simple solution, I think, would be to augment the `token_t` struct with a destructor, a function pointer. If this is NULL, then `free()` will be used, as now. If it is non-null, then the specified function will be invoked instead.  We will then provide another variant of SET that takes the destructor as an argument.

**Comment by lhstrh** [comment]
Shall we move this issue to `reactor-c`?

**Comment by edwardalee** [comment]
Moving this reactor-c.

**Comment by lhstrh** [comment]
For future reference: you can use the `Transfer issue` link on the right to transfer an issue to another repo.
